In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

from selenium.webdriver.common.by import By

import pandas as pd
import time

In [2]:
driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

driver.maximize_window()

driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/")

In [3]:
time.sleep(5)

print(driver.title)

Voiture occasion| Moteur.ma

In [4]:
html = driver.page_source

print(html[:5000])

InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=150.0.7871.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff72ee50d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff72ee50d80+15600]
	chromedriver!(No symbol) [0x7ff72e9a594d]
	chromedriver!(No symbol) [0x7ff72e991102]
	chromedriver!(No symbol) [0x7ff72e9b704c]
	chromedriver!(No symbol) [0x7ff72ea30790]
	chromedriver!(No symbol) [0x7ff72ea4d902]
	chromedriver!(No symbol) [0x7ff72e9f2e6c]
	chromedriver!(No symbol) [0x7ff72e9f3d93]
	chromedriver!GetHandleVerifier [0x7ff72f436431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff72f430a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff72f455865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff72ee6dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff72ee7661c+3ae9c]
	chromedriver!GetHandleVerifier [0x7ff72ee5ab74+1f3f4]
	chromedriver!GetHandleVerifier [0x7ff72ee5ad04+1f584]
	chromedriver!GetHandleVerifier [0x7ff72ee3d9d7+2257]
	KERNEL32!BaseThreadInitThunk [0x7ffc6eaee957+17]
	ntdll!RtlUserThreadStart [0x7ffc6fa2ad6c+2c]

In [5]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

driver.maximize_window()

driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/")

time.sleep(5)

print(driver.title)

Voiture occasion| Moteur.ma

In [6]:

html = driver.page_source

print(html[:5000])

<html class="no-js" lang="fr" dir="ltr"><head>
    <script type="text/javascript" async="" src="https://analytics.tiktok.com/i18n/pixel/static/identify_b8133453.js"></script><script type="text/javascript" async="" src="https://analytics.tiktok.com/i18n/pixel/static/main.MTA2MWE1OWMwOQ.js" data-id="CTC6DRBC77U38DUS8CO0"></script><script async="" src="https://scripts.clarity.ms/0.8.67/clarity.js"></script><script type="text/javascript" async="" src="https://analytics.tiktok.com/i18n/pixel/events.js?sdkid=CTC6DRBC77U38DUS8CO0&amp;lib=ttq"></script><script async="" src="https://www.clarity.ms/tag/jjlg7xl4le?ref=gtm2"></script><script src="https://connect.facebook.net/signals/config/627061288872447?v=2.9.357&amp;r=stable&amp;domain=www.moteur.ma&amp;hme=1179b74563cacb97c6ebae600e40937237ab12824fb84996eee07eca65cabbd4&amp;ex_m=107%2C208%2C158%2C22%2C73%2C74%2C149%2C69%2C68%2C11%2C167%2C93%2C16%2C141%2C130%2C39%2C76%2C81%2C137%2C163%2C169%2C26%2C27%2C28%2C30%2C48%2C150%2C78%2C115%2C18%2C20%2C44%2C40%2C42%2C41%2C86%2C95%2C99%2C113%2C148%2C151%2C46%2C114%2C24%2C21%2C122%2C70%2C36%2C153%2C152%2C154%2C145%2C143%2C25%2C35%2C59%2C112%2C165%2C71%2C17%2C156%2C117%2C84%2C67%2C19%2C88%2C89%2C119%2C87%2C139%2C138%2C142%2C164%2C34%2C49%2C116%2C47%2C8%2C4%2C5%2C7%2C6%2C3%2C94%2C104%2C170%2C175%2C222%2C75%2C235%2C234%2C233%2C23%2C33%2C55%2C106%2C61%2C10%2C64%2C100%2C101%2C102%2C108%2C133%2C31%2C29%2C135%2C136%2C132%2C131%2C159%2C77%2C162%2C160%2C161%2C50%2C60%2C126%2C15%2C166%2C45%2C280%2C281%2C279%2C294%2C310%2C215%2C204%2C62%2C205%2C203%2C313%2C304%2C52%2C216%2C110%2C134%2C83%2C124%2C54%2C123%2C129%2C128%2C58%2C65%2C63%2C155%2C79%2C80%2C118%2C37%2C32%2C53%2C56%2C103%2C168%2C1%2C127%2C14%2C125%2C12%2C2%2C57%2C96%2C66%2C121%2C92%2C91%2C171%2C172%2C97%2C98%2C9%2C105%2C51%2C146%2C90%2C82%2C72%2C120%2C109%2C43%2C147%2C0%2C85%2C140%2C144%2C157%2C38%2C111%2C13%2C173%2C232%2C230%2C225%2C227%2C228%2C229%2C226%2C214%2C231%2C224%2C237%2C196%2C190%2C194%2C195%2C193%2C188%2C334%2C263%2C270%2C271%2C272%2C269%2C273%2C264%2C267%2C261%2C274%2C275%2C266%2C276%2C268%2C277%2C262%2C207%2C265%2C260%2C199%2C191%2C192%2C218%2C189%2C187%2C213%2C331%2C239%2C209%2C181%2C182%2C177%2C183%2C180%2C178%2C179%2C176%2C174%2C185%2C186%2C184%2C282%2C333%2C303%2C301%2C302%2C300%2C197%2C242%2C249%2C243%2C245%2C248%2C246%2C247%2C244%2C241%2C258%2C253%2C255%2C252%2C259%2C256%2C251%2C257%2C254%2C250%2C296%2C307" async=""></script><script src="https://connect.facebook.net/signals/config/204407031549583?v=2.9.357&amp;r=stable&amp;domain=www.moteur.ma&amp;hme=1179b74563cacb97c6ebae600e40937237ab12824fb84996eee07eca65cabbd4&amp;ex_m=107%2C208%2C158%2C22%2C73%2C74%2C149%2C69%2C68%2C11%2C167%2C93%2C16%2C141%2C130%2C39%2C76%2C81%2C137%2C163%2C169%2C26%2C27%2C28%2C30%2C48%2C150%2C78%2C115%2C18%2C20%2C44%2C40%2C42%2C41%2C86%2C95%2C99%2C113%2C148%2C151%2C46%2C114%2C24%2C21%2C122%2C70%2C36%2C153%2C152%2C154%2C145%2C143%2C25%2C35%2C59%2C112%2C165%2C71%2C17%2C156%2C117%2C84%2C67%2C19%2C88%2C89%2C119%2C87%2C139%2C138%2C142%2C164%2C34%2C49%2C116%2C47%2C8%2C4%2C5%2C7%2C6%2C3%2C94%2C104%2C170%2C175%2C222%2C75%2C235%2C234%2C233%2C23%2C33%2C55%2C106%2C61%2C10%2C64%2C100%2C101%2C102%2C108%2C133%2C31%2C29%2C135%2C136%2C132%2C131%2C159%2C77%2C162%2C160%2C161%2C50%2C60%2C126%2C15%2C166%2C45%2C280%2C281%2C279%2C294%2C310%2C215%2C204%2C62%2C205%2C203%2C313%2C304%2C52%2C216%2C110%2C134%2C83%2C124%2C54%2C123%2C129%2C128%2C58%2C65%2C63%2C155%2C79%2C80%2C118%2C37%2C32%2C53%2C56%2C103%2C168%2C1%2C127%2C14%2C125%2C12%2C2%2C57%2C96%2C66%2C121%2C92%2C91%2C171%2C172%2C97%2C98%2C9%2C105%2C51%2C146%2C90%2C82%2C72%2C120%2C109%2C43%2C147%2C0%2C85%2C140%2C144%2C157%2C38%2C111%2C13%2C173" async=""></script><script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-Q1NXR1BVFD&amp;cx=c&amp;gtm=4e67g0h2"></script><script async="" type="text/javascript" src="https://www.googletagservices.com/tag/js/gpt.js"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-TLMJHZ6"></script><script>
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-TLMJHZ6');
</script>
    <script>
        window.dataLayer = window.dataLayer || [];
                    window.dataLayer.push({"lang":"fr","section_type":"occasion","content_type":"listing","category":"car","content_group":"ads","event":"page_view"});
            </script>
    <meta name="robots" content="index, follow">
<meta charset="utf-8">
<script>
    window.googletag = window.googletag || { cmd: [] };
</script>
<meta http-equiv="x-ua-compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="

In [7]:
with open("page.html", "w", encoding="utf-8") as f:
    f.write(driver.page_source)

print("HTML sauvegardé")

HTML sauvegardé

In [8]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(driver.page_source, "html.parser")

print(soup.title)

<title>Voiture occasion| Moteur.ma</title>

In [9]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(driver.page_source, "html.parser")

# Trouver tous les liens de la page
liens = soup.find_all("a", href=True)

print("Nombre de liens :", len(liens))

# Afficher les 20 premiers liens
for lien in liens[:20]:
    print(lien["href"])

Nombre de liens : 476
https://www.moteur.ma/
https://www.moteur.ma/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
https://www.moteur.ma/
https://www.moteur.ma/
https://www.moteur.ma/
https://www.moteur.ma/fr/neuf/
https://www.moteur.ma/fr/neuf/
https://www.moteur.ma/fr/neuf/voiture/
https://www.moteur.ma/fr/neuf/voiture/
https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/
https://www.moteur.ma/fr/neuf/rubrique/
https://www.moteur.ma/fr/neuf/comparatif-voiture-neuf/
https://www.moteur.ma/fr/neuf/moto/
https://www.moteur.ma/fr/neuf/moto/
https://www.moteur.ma/fr/neuf/promotion-moto-neuve-maroc/
https://www.moteur.ma/fr/neuf/camion/
https://www.moteur.ma/fr/neuf/camion/
https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/
https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/

In [10]:
annonces = []

for lien in liens:
    href = lien.get("href")

    if href and "detail-annonce" in href:
        annonces.append(href)

print("Nombre d'annonces trouvées :", len(annonces))

# Afficher les 10 premières
for annonce in annonces[:10]:
    print(annonce)

Nombre d'annonces trouvées : 90
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508810/volkswagen-polo.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508810/volkswagen-polo.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508810/volkswagen-polo.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508809/volkswagen-tiguan.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508809/volkswagen-tiguan.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508809/volkswagen-tiguan.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508808/volvo-v40.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508808/volvo-v40.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508808/volvo-v40.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508807/hyundai-atos.html

In [11]:
annonces = list(set(annonces))

print("Nombre d'annonces uniques :", len(annonces))

for annonce in annonces[:10]:
    print(annonce)

Nombre d'annonces uniques : 30
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508784/hyundai-creta.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508789/renault-megane.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508793/nissan-sunny.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508788/citroen-c3.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508807/hyundai-atos.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508801/peugeot-206.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508797/dacia-logan.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508795/renault-kangoo.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508799/ford-fiesta.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508802/peugeot-3008.html

In [12]:
# Prendre la première annonce
url = annonces[0]

print(url)

driver.get(url)

time.sleep(3)

print(driver.title)

https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508784/hyundai-creta.html
Hyundai Creta Hyundai Creta tout option 09-11-21 1ère main 44k 2021 Diesel occasion 508784Agadir_phrase Maroc| Moteur.ma

In [16]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(driver.page_source, "html.parser")

texte = soup.get_text(separator="\n")

print(texte)

Hyundai Creta Hyundai Creta tout option 09-11-21 1ère main 44k 2021 Diesel occasion 508784Agadir_phrase Maroc| Moteur.ma











































































0








































Accueil


Neuf




Accueil


Voitures


Tarifs et prix des voitures neuves


Dernières promotions 2026


Offres du moment


Comparatif voitures neuves




Motos


Tarifs et prix des motos neuves


Dernières promotions 2026




Camions


 Tarifs et prix des camions neufs






Promotion




Dernières Promotions 2026


Offres du moment






Émissions






















Actualités




Marché Auto


Forum






Occasion




Voitures


Vendre une voiture


Acheter une voiture d'occasion


La Cote d'occasion




Motos


Vendre une moto


Acheter une moto d'occasion




Camions


Vendre un camion


Acheter un camion d'occasion




Showrooms Pro


Véhicules d'occasion


Voiture de location


Agences de location










﻿Se connecter









S'inscrire










                                Vendez Votre Voiture










                            Se connecter







 Vendez Votre Voiture










0













                                العربية
























































								opel astra
















								opel corsa
















								opel grandland
















								opel frontera
















								opel mokka
















								Seat Leon FR
















								Seat ibiza
















								SANTA FE Full Hybrid
















								taigo
















								golf 8
















								T-roc
















								tiguan
















								Offres du moment
















								DFSK E5
















								magnite
















								chery tiggo 7 pro
















								dacia sandero stepway
















								opel astra
















								opel corsa
















								opel grandland
















								opel frontera
















								opel mokka
















								Seat Leon FR
















								Seat ibiza
















								SANTA FE Full Hybrid
















								taigo
















								golf 8
















								T-roc
















								tiguan
















								Offres du moment
















								DFSK E5
















								magnite
















								chery tiggo 7 pro
















								dacia sandero stepway
















								opel astra
















								opel corsa
















								opel grandland
















								opel frontera
















								opel mokka
















								Seat Leon FR
















								Seat ibiza





‹
›


















 Accueil


Occasion


Acheter une voiture d'occasion


Hyundai Creta

















































            Comparatif voitures neuves

0




























Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr




Modèle






Version






































Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr




Modèle






Version






































Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr




Modèle






Version









































                Comparer


























                ×








































                                    Hyundai
                                    Creta







                                                                    225,000 MAD








                                    Voiture






                                    Agadir






                                    Jul 18, 2026






                                    0 vues





















































Informations Véhicule










Marque:


Hyundai


Modèle:


Creta






Année:


2021


Kilométrage:


44,000 km






Carburant:



                                            Diesel


Transmission:



                                            Automatique






Carrosserie:



                                            N/A


Couleur:



                                            N/A








Nombre de portes





                                            5





Puissance fiscale





                                            6











Spécifications rapides




Hyundai Creta tout option **** ère main 44k.. Veuillez nous contacter pour plus d'informations, bienvenue




Caractéristiques & Options














Premier propriétaire








Véhicule préparé












Historique d'accidents








Importation neuve












Statut de douane



                                                    N/A














options









                                                    État du véhicule










                                                    ABS










                                                    Climatisation










                                                    Airbags










                                                    Fermeture centralisée










                                                    Régulateur de vitesse










                                                    Vitres électriques










                                                    ESP










                                                    Navigation GPS










                                                    Ordinateur de bord










                                                    Radar de recul










                                                    Jantes










                                                    Limiteur de vitesse










                                                    CD / MP3 / Bluetooth





















Avis & Évaluations










4
/5
















Basé sur 0 avis








5








319






4








340






3








266






2








386






1








224






















Annonces Similaires















                                                Hyundai Atos




                                                                                                    37,000 MAD



il y a 10 minutes













                                                Hyundai Accent




                                                                                                    33,000 MAD



il y a 10 minutes













                                                Hyundai Accent




                                                                                                    122,000 MAD



il y a 43 minutes













                                                Hyundai Accent




                                                                                                    112,000 MAD



il y a 48 minutes













                                                Hyundai Accent




                                                                                                    47,000 MAD



il y a 48 minutes













































Dernières annonces premium





















                                            Premium




























                                                        Kia Picanto










                                                        Tétouan






                                                        2019






                                                                                                            94,000 MAD




























                                            Premium




























                                                        Toyota Verso










                                                        Rabat






                                                        2012






                                                                                                            95,000 MAD




























                                            Premium




























                                                        BMW X5










                                                        Casablanca






                                                        2012






                                                                                                            280,000 MAD




























                                            Premium




























                                                        Alfa Romeo MiTo










                                                        Rabat






                                                        2015






                                                                                                            123,000 MAD




























                                            Premium




























                                                        Hyundai Accent










                                                        El Jadida






                                                        2019






                                                                                                            163,000 MAD




























                                            Premium




























                                                        Mercedes-Benz 190










                                                        Tanger






                                                        1993






                                                                                                            65,000 MAD




























                                            Premium




























                                                        Mercedes-Benz Classe E










                                                        Casablanca






                                                        2012






                                                                                                            170,000 MAD




























                                            Premium




























                                                        Volvo XC60










                                                        Marrakech






                                                        2017






                                                                                                            250,000 MAD




























                                            Premium




























                                                        Land Rover Range Rover Velar










                                                        Agadir






                                                        2019






                                                                                                            Appeler pour le prix




























                                            Premium




























                                                        BMW Série 1










                                                        Casablanca






                                                        2011






                                                                                                            90,000 MAD




























                                            Premium




























                                                        Kia Picanto










                                                        Tétouan






                                                        2019






                                                                                                            94,000 MAD




























                                            Premium




























                                                        Toyota Verso










                                                        Rabat






                                                        2012






                                                                                                            95,000 MAD




























                                            Premium




























                                                        BMW X5










                                                        Casablanca






                                                        2012






                                                                                                            280,000 MAD




























                                            Premium




























                                                        Alfa Romeo MiTo










                                                        Rabat






                                                        2015






                                                                                                            123,000 MAD




























                                            Premium




























                                                        Hyundai Accent










                                                        El Jadida






                                                        2019






                                                                                                            163,000 MAD




























                                            Premium




























                                                        Mercedes-Benz 190










                                                        Tanger






                                                        1993






                                                                                                            65,000 MAD




























                                            Premium




























                                                        Mercedes-Benz Classe E










                                                        Casablanca






                                                        2012






                                                                                                            170,000 MAD




























                                            Premium




























                                                        Volvo XC60










                                                        Marrakech






                                                        2017






                                                                                                            250,000 MAD




























                                            Premium




























                                                        Land Rover Range Rover Velar










                                                        Agadir






                                                        2019






                                                                                                            Appeler pour le prix




























                                            Premium




























                                                        BMW Série 1










                                                        Casablanca






                                                        2011






                                                                                                            90,000 MAD













‹
›









































Publié par








AGARRR



                                                            Vendeur depuis Jul 2026







Informations Contact





                            Agadir








                                Appeler maintenant



















 Contacter le vendeur





 Appeler maintenant












                                    Prix Hyundai Creta neuve maroc


























                            HYUNDAI Creta







À partir de


264 900 Dhs







                                    3 Versions


























Prix promotionnels du moment


















Mahindra


PIK-UP




À partir de


185 900 Dhs


















Kia


EV6




À partir de


655 000 Dhs


















Kia


Picanto




À partir de


154 900 Dhs


















Honda


CR-V




À partir de


450 000 Dhs


















Audi


A3 Sportback




À partir de


351 000 Dhs


















Opel


Astra




À partir de


269 000 Dhs


















Citroën


C5 Aircross




À partir de


292 900 Dhs




























Dernières voitures neuves


















Nouveau










DENZA


D9


100 % électrique (BEV)



                                                                                            Prix sur demande




                                            2026 · SUV et 4x4





















Nouveau










DENZA


D9


DM-i Hybride rechargeable (PHEV)



                                                                                            889 900 Dhs




                                            2026 · SUV et 4x4





















Nouveau










DENZA


B8


2.0 Turbo essence  PHEV



                                                                                            869 900 Dhs




                                            2026 · SUV et 4x4





















Nouveau










DENZA


B5


1.5 Turbo essence  PHEV



                                                                                            629 900 Dhs




                                            2026 · SUV et 4x4





















Nouveau










Leapmotor


B10 REEV


1.5 AT 218



                                                                                            269 000 Dhs




                                            2026 · SUV et 4x4





















Nouveau










Citroën


C3


PLUS PACK ESSENCE BVM




In [17]:
print(driver.title)

Hyundai Creta Hyundai Creta tout option 09-11-21 1ère main 44k 2021 Diesel occasion 508784Agadir_phrase Maroc| Moteur.ma

In [18]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(driver.page_source, "html.parser")

# Chercher tous les textes de la page contenant "DH"
for element in soup.find_all(text=True):
    texte = element.strip()
    if "DH" in texte:
        print(texte)

window.topSheetBrandsData = [{"id":453,"label":"Abarth","slug":"abarth","models":[{"id":10210,"label":"595","slug":"595","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-595-369.png","versions":[{"id":4052,"label":"595 1.4 Turbo 165cv","version":"595 1.4 Turbo 165cv","slug":"595-14-turbo-165cv"}]},{"id":10675,"label":"695","slug":"695","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-695-984.png","versions":[{"id":2360,"label":"TURISMO 1.4 Turbo 180cv","version":"TURISMO 1.4 Turbo 180cv","slug":"turismo-14-turbo-180cv"},{"id":4053,"label":"COMPETIZIONE 1.4 Turbo 180cv","version":"COMPETIZIONE 1.4 Turbo 180cv","slug":"competizione-14-turbo-180cv"},{"id":4341,"label":"C 1.4 Turbo 180cv ","version":"C 1.4 Turbo 180cv ","slug":"c-14-turbo-180cv"}]}]},{"id":5,"label":"Alfa Romeo","slug":"alfa-romeo","models":[{"id":10009,"label":"Giulia","slug":"giulia","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-giulia-484.png","versions":[{"id":2950,"label":"2.2 JTDM 210 AT Veloce ","version":"2.2 JTDM 210 AT Veloce ","slug":"22-jtdm-210-at-veloce"},{"id":2951,"label":"2.2 JTDM 210 AT Competizione","version":"2.2 JTDM 210 AT Competizione","slug":"22-jtdm-210-at-competizione"}]},{"id":10962,"label":"Junior","slug":"junior","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-junior-515.png","versions":[{"id":3849,"label":"Ibrida 1.2 l MHEV 136 AT","version":"Ibrida 1.2 l MHEV 136 AT","slug":"ibrida-12-l-mhev-136-at"},{"id":3850,"label":"Ibrida+ 1.2 l MHEV 136 AT","version":"Ibrida+ 1.2 l MHEV 136 AT","slug":"ibrida-12-l-mhev-136-at"},{"id":3851,"label":"Speciale 1.2 l MHEV 136 AT","version":"Speciale 1.2 l MHEV 136 AT","slug":"speciale-12-l-mhev-136-at"},{"id":4540,"label":"EV 115 kW AT Elettrica Speciale","version":"EV 115 kW AT Elettrica Speciale","slug":"ev-115-kw-at-elettrica-speciale"}]},{"id":10098,"label":"Stelvio","slug":"stelvio","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-stelvio-276.png","versions":[{"id":2952,"label":"2.2 JTDM 160 AT Sprint","version":"2.2 JTDM 160 AT Sprint","slug":"22-jtdm-160-at-sprint"},{"id":2953,"label":"2.2 JTDM 210 AT Veloce","version":"2.2 JTDM 210 AT Veloce","slug":"22-jtdm-210-at-veloce"}]},{"id":10723,"label":"Tonale","slug":"tonale","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-tonale-190.png","versions":[{"id":3054,"label":"1.6 Diesel 130 TCT Sprint","version":"1.6 Diesel 130 TCT Sprint","slug":"16-diesel-130-tct-sprint"},{"id":3424,"label":"1.5 l MHEV 130 AT Tributo Italiano","version":"1.5 l MHEV 130 AT Tributo Italiano","slug":"15-l-mhev-130-at-tributo-italiano"},{"id":4209,"label":"1.5 l MHEV 130 AT Sprint","version":"1.5 l MHEV 130 AT Sprint","slug":"15-l-mhev-130-at-sprint"},{"id":4210,"label":"1.5 l MHEV 130 AT Veloce","version":"1.5 l MHEV 130 AT Veloce","slug":"15-l-mhev-130-at-veloce"},{"id":4211,"label":"1.6 Diesel 130 Tributo Italiano","version":"1.6 Diesel 130 Tributo Italiano","slug":"16-diesel-130-tributo-italiano"}]}]},{"id":6,"label":"Alpine","slug":"alpine","models":[{"id":10995,"label":"A110","slug":"a110","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-a110-311.png","versions":[{"id":3967,"label":"252 ch","version":"252 ch","slug":"252-ch"},{"id":3970,"label":"S 300cv","version":"S 300cv","slug":"s-300cv"},{"id":3971,"label":"Gt 300 ch","version":"Gt 300 ch","slug":"gt-300-ch"}]}]},{"id":8,"label":"Aston Martin","slug":"aston-martin","models":[{"id":10474,"label":"DB11","slug":"db11","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-db11-710.png","versions":[{"id":2559,"label":" 4.0-litre twin-turbo V8","version":" 4.0-litre twin-turbo V8","slug":"40-litre-twin-turbo-v8"},{"id":2560,"label":"Volante 4.0-litre twin-turbo V8","version":"Volante 4.0-litre twin-turbo V8","slug":"volante-40-litre-twin-turbo-v8"},{"id":2561,"label":"AMR 5.2l bi-turbo V12","version":"AMR 5.2l bi-turbo V12","slug":"amr-52l-bi-turbo-v12"}]},{"id":46,"label":"DBS","slug":"dbs","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-dbs-349.png","versions":[{"id":2562,"label":"5.2 litre bi-turbo V12 ","version":"5.2 litre bi-turbo V12 ","slug":"52-litre-bi-turbo-v12"},{"id":2563,"label":"volante 5.2 litre bi-turbo V12 ","version":"volante 5.2 litre bi-turbo V12 ","slug":"volante-52-litre-bi-turbo-v12"}]},{"id":10421,"label":"DBX","slug":"dbx","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-dbx-463.png","versions":[{"id":2556,"label":"4.0 litre twin turbo V8","version":"4.0 litre twin turbo V8","slug":"40-litre-twin-turbo-v8"}]},{"id":48,"label":"Vantage","slug":"vantage","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-vantage-492.png","versions":[{"id":2557,"label":"COUPE 4.0 litre twin turbo V8","version":"COUPE 4.0 litre twin turbo V8","slug":"coupe-40-litre-twin-turbo-v8"},{"id":2558,"label":"roadster 4.0 litre twin turbo V8","version":"roadster 4.0 litre twin turbo V8","slug":"roadster-40-litre-twin-turbo-v8"}]}]},{"id":9,"label":"Audi","slug":"audi","models":[{"id":54,"label":"A1","slug":"a1","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-a1-994.png","versions":[{"id":3733,"label":"Sportback - Ph1 - 30 TFSI URBAN BVA 116ch","version":"Sportback - Ph1 - 30 TFSI URBAN BVA 116ch","slug":"sportback-ph1-30-tfsi-urban-bva-116ch"},{"id":3734,"label":"Sportback  30 TFSI S-Line BVA 116ch","version":"Sportback  30 TFSI S-Line BVA 116ch","slug":"sportback-30-tfsi-s-line-bva-116ch"}]},{"id":56,"label":"A3 Berline","slug":"a3-berline","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-a3-berline-896.png","versions":[{"id":3831,"label":"35 TDI 150 S-Tronic Dynamic","version":"35 TDI 150 S-Tronic Dynamic","slug":"35-tdi-150-s-tronic-dynamic"},{"id":3832,"label":"35 TDI 150 S-Tronic Emotion","version":"35 TDI 150 S-Tronic Emotion","slug":"35-tdi-150-s-tronic-emotion"},{"id":3834,"label":"35 TDI 150 S-Tronic S-line","version":"35 TDI 150 S-Tronic S-line","slug":"35-tdi-150-s-tronic-s-line"},{"id":4358,"label":"35 TDI 150 S-Tronic Performance","version":"35 TDI 150 S-Tronic Performance","slug":"35-tdi-150-s-tronic-performance"},{"id":4491,"label":"35 TDI 150 S-Tronic Black Edition","version":"35 TDI 150 S-Tronic Black Edition","slug":"35-tdi-150-s-tronic-black-edition"}]},{"id":11137,"label":"A3 Sportback","slug":"a3-sportback","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-a3-sportback-885.png","versions":[{"id":3826,"label":"35 TDI 150 S-Tronic Dynamic","version":"35 TDI 150 S-Tronic Dynamic","slug":"35-tdi-150-s-tronic-dynamic"},{"id":3827,"label":"35 TDI 150 S-Tronic Emotion","version":"35 TDI 150 S-Tronic Emotion","slug":"35-tdi-150-s-tronic-emotion"},{"id":3828,"label":"35 TDI 150 S-Tronic Performance","version":"35 TDI 150 S-Tronic Performance","slug":"35-tdi-150-s-tronic-performance"},{"id":3829,"label":"35 TDI 150 S-Tronic S-line","version":"35 TDI 150 S-Tronic S-line","slug":"35-tdi-150-s-tronic-s-line"},{"id":4490,"label":"35 TDI 150 S-Tronic Black Edition","version":"35 TDI 150 S-Tronic Black Edition","slug":"35-tdi-150-s-tronic-black-edition"}]},{"id":58,"label":"A5","slug":"a5","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-a5-870.jpg","versions":[{"id":4132,"label":"2.0 TDI 204 MHEV S-Tronic Business","version":"2.0 TDI 204 MHEV S-Tronic Business","slug":"20-tdi-204-mhev-s-tronic-business"},{"id":4133,"label":"2.0 TDI 204 MHEV S-Tronic S-line","version":"2.0 TDI 204 MHEV S-Tronic S-line","slug":"20-tdi-204-mhev-s-tronic-s-line"},{"id":4134,"label":"2.0 TDI 204 MHEV S-Tronic S-Edition","version":"2.0 TDI 204 MHEV S-Tronic S-Edition","slug":"20-tdi-204-mhev-s-tronic-s-edition"}]},{"id":59,"label":"A6","slug":"a6","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-a6-906.png","versions":[{"id":3737,"label":"MHEV 2,0L TDI 204 S-Tronic Business","version":"MHEV 2,0L TDI 204 S-Tronic Business","slug":"mhev-20l-tdi-204-s-tronic-business"},{"id":3739,"label":"MHEV 2,0L TDI 204 S-Tronic S line","version":"MHEV 2,0L TDI 204 S-Tronic S line","slug":"mhev-20l-tdi-204-s-tronic-s-line"},{"id":3740,"label":"MHEV 2,0L TDI 204 S-Tronic S Edition","version":"MHEV 2,0L TDI 204 S-Tronic S Edition","slug":"mhev-20l-tdi-204-s-tronic-s-edition"},{"id":3933,"label":"PHEV 50 TFSI e 299 S-Tronic quattro Hybrid S","version":"PHEV 50 TFSI e 299 S-Tronic quattro Hybrid S","slug":"phev-50-tfsi-e-299-s-tronic-quattro-hybrid-s"}]},{"id":11138,"label":"A6 etron","slug":"a6-etron","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-a6-etron-941.png","versions":[{"id":4593,"label":"270 kW AT Business","version":"270 kW AT Business","slug":"270-kw-at-business"},{"id":4594,"label":"270 kW AT S-line","version":"270 kW AT S-line","slug":"270-kw-at-s-line"}]},{"id":60,"label":"A7","slug":"a7","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-a7-596.png","versions":[{"id":3742,"label":"Sportback DIESEL MHEV 40 TDI 204 S-Tronic S-line","version":"Sportback DIESEL MHEV 40 TDI 204 S-Tronic S-line","slug":"sportback-diesel-mhev-40-tdi-204-s-tronic-s-line"}]},{"id":61,"label":"A8","slug":"a8","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-a8-570.png","versions":[{"id":3229,"label":"MHEV 50 TDI 286 quattro Executive","version":"MHEV 50 TDI 286 quattro Executive","slug":"mhev-50-tdi-286-quattro-executive"}]},{"id":10052,"label":"Q2","slug":"q2","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-q2-435.png","versions":[{"id":4521,"label":"MHEV 35 TDI Techno 35 TDI","version":"MHEV 35 TDI Techno 35 TDI","slug":"mhev-35-tdi-techno-35-tdi"},{"id":4523,"label":"MHEV Sline Plus 35 TDI","version":"MHEV Sline Plus 35 TDI","slug":"mhev-sline-plus-35-tdi"}]},{"id":64,"label":"Q3","slug":"q3","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-q3-612.png","versions":[{"id":2420,"label":"2.0L TDI 193  S-Tronic S-EDITION","version":"2.0L TDI 193  S-Tronic S-EDITION","slug":"20l-tdi-193-s-tronic-s-edition"},{"id":4496,"label":"35 TDI 150 S-Tronic Performance","version":"35 TDI 150 S-Tronic Performance","slug":"35-tdi-150-s-tronic-performance"},{"id":4498,"label":"30 TDI 150 S-Tronic Dynamic","version":"30 TDI 150 S-Tronic Dynamic","slug":"30-tdi-150-s-tronic-dynamic"},{"id":4499,"label":"30 TDI 150 S-Tronic S-line","version":"30 TDI 150 S-Tronic S-line","slug":"30-tdi-150-s-tronic-s-line"},{"id":4500,"label":"30 TDI 150 S-Tronic S-\u00c9dition","version":"30 TDI 150 S-Tronic S-\u00c9dition","slug":"30-tdi-150-s-tronic-s-edition"}]},{"id":11130,"label":"Q3 Sportback","slug":"q3-sportback","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-q3-sportback-294.png","versions":[{"id":4492,"label":"sportback 35 TDI 150 S-Tronic Design","version":"sportback 35 TDI 150 S-Tronic Design","slug":"sportback-35-tdi-150-s-tronic-design"},{"id":4493,"label":"sportback 35 TDI 150 S-Tronic S-Edition","version":"sportback 35 TDI 150 S-Tronic S-Edition","slug":"sportback-35-tdi-150-s-tronic-s-edition"},{"id":4494,"label":"sportback  35 TDI 150 S-Tronic S-line","version":"sportback  35 TDI 150 S-Tronic S-line","slug":"sportback-35-tdi-150-s-tronic-s-line"},{"id":4495,"label":"5 TDI 150 S-Tronic Performance","version":"5 TDI 150 S-Tronic Performance","slug":"5-tdi-150-s-tronic-performance"}]},{"id":65,"label":"Q5","slug":"q5","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-q5-923.png","versions":[{"id":4365,"label":"MHEV 40 TDI 204 S-Tronic quattro Sport","version":"MHEV 40 TDI 204 S-Tronic quattro Sport","slug":"mhev-40-tdi-204-s-tronic-quattro-sport"},{"id":4366,"label":"MHEV 40 TDI 204 S-Tronic quattro S-line","version":"MHEV 40 TDI 204 S-Tronic quattro S-line","slug":"mhev-40-tdi-204-s-tronic-quattro-s-line"},{"id":4367,"label":"MHEV 40 TDI 204 S-Tronic quattro S-Edition","version":"MHEV 40 TDI 204 S-Tronic quattro S-Edition","slug":"mhev-40-tdi-204-s-tronic-quattro-s-edition"},{"id":4541,"label":"MHEV 40 TDI 204 S-Tronic quattro Dynamic","version":"MHEV 40 TDI 204 S-Tronic quattro Dynamic","slug":"mhev-40-tdi-204-s-tronic-quattro-dynamic"}]},{"id":11123,"label":"Q5 Sportback","slug":"q5-sportback","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-q5-sportback-419.png","versions":[{"id":4361,"label":"40 TDI 204 S-Tronic quattro Dynamic","version":"40 TDI 204 S-Tronic quattro Dynamic","slug":"40-tdi-204-s-tronic-quattro-dynamic"},{"id":4362,"label":"40 TDI 204 S-Tronic quattro Sport","version":"40 TDI 204 S-Tronic quattro Sport","slug":"40-tdi-204-s-tronic-quattro-sport"},{"id":4363,"label":"40 TDI 204 S-Tronic quattro S-line","version":"40 TDI 204 S-Tronic quattro S-line","slug":"40-tdi-204-s-tronic-quattro-s-line"},{"id":4364,"label":"40 TDI 204 S-Tronic quattro S-Edition","version":"40 TDI 204 S-Tronic quattro S-Edition","slug":"40-tdi-204-s-tronic-quattro-s-edition"}]},{"id":10977,"label":"Q6","slug":"q6","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-q6-508.png","versions":[{"id":3983,"label":"e-tron  S-line","version":"e-tron  S-line","slug":"e-tron-s-line"},{"id":3984,"label":"e-tron S-Edition quattro","version":"e-tron S-Edition quattro","slug":"e-tron-s-edition-quattro"}]},{"id":66,"label":"Q7","slug":"q7","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-q7-884.png","versions":[{"id":3947,"label":"50 TDI 286 S-Tronic quattro Exclusive","version":"50 TDI 286 S-Tronic quattro Exclusive","slug":"50-tdi-286-s-tronic-quattro-exclusive"},{"id":3948,"label":"V6 3,0L TDI 286 quattro Tiptronic Sline","version":"V6 3,0L TDI 286 quattro Tiptronic Sline","slug":"v6-30l-tdi-286-quattro-tiptronic-sline"},{"id":3949,"label":"PHEV 55 TFSIe 394 quattro Hybrid S","version":"PHEV 55 TFSIe 394 quattro Hybrid S","slug":"phev-55-tfsie-394-quattro-hybrid-s"}]},{"id":10186,"label":"Q8","slug":"q8","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-q8-167.png","versions":[{"id":3961,"label":"MHEV Performance V6 3,0L TDI 286 quattro Tiptronic","version":"MHEV Performance V6 3,0L TDI 286 quattro Tiptronic","slug":"mhev-performance-v6-30l-tdi-286-quattro-tiptronic"},{"id":3963,"label":"MHEV 50 TDI 286 quattro  Executive Black Edition","version":"MHEV 50 TDI 286 quattro  Executive Black Edition","slug":"mhev-50-tdi-286-quattro-executive-black-edition"},{"id":3966,"label":"MHEV Executive V6 3,0L TDI 286 quattro Tiptronic","version":"MHEV Executive V6 3,0L TDI 286 quattro Tiptronic","slug":"mhev-executive-v6-30l-tdi-286-quattro-tiptronic"},{"id":4230,"label":"MHEV 50 TDI 286 quattro Sport S","version":"MHEV 50 TDI 286 quattro Sport S","slug":"mhev-50-tdi-286-quattro-sport-s"},{"id":4356,"label":"Executive V6 3,0L TDI 286 quattro Tiptronic","version":"Executive V6 3,0L TDI 286 quattro Tiptronic","slug":"executive-v6-30l-tdi-286-quattro-tiptronic"},{"id":4542,"label":"MHEV 50 TDI 286 quattro  S-Edition","version":"MHEV 50 TDI 286 quattro  S-Edition","slug":"mhev-50-tdi-286-quattro-s-edition"}]},{"id":11081,"label":"RS 3","slug":"rs-3","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-rs-3-938.png","versions":[{"id":4342,"label":"Sportback 2.5 TFSI","version":"Sportback 2.5 TFSI","slug":"sportback-25-tfsi"}]},{"id":11109,"label":"RS Q8","slug":"rs-q8","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-rs-q8-428.png","versions":[{"id":4359,"label":"V8 4.0 TFSI biturbo","version":"V8 4.0 TFSI biturbo","slug":"v8-40-tfsi-biturbo"}]}]},{"id":534,"label":"BAIC","slug":"baic","models":[{"id":11115,"label":"BJ30e","slug":"bj30e","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-bj30e-545.png","versions":[{"id":4572,"label":"1.5 l 330 AT LV4","version":"1.5 l 330 AT LV4","slug":"15-l-330-at-lv4"},{"id":4573,"label":"1.5 l 404 AT LV5","version":"1.5 l 404 AT LV5","slug":"15-l-404-at-lv5"}]},{"id":11015,"label":"U5 Plus","slug":"u5-plus","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-u5 plus-543.png","versions":[{"id":4009,"label":"1.5 l 112 Luxury","version":"1.5 l 112 Luxury","slug":"15-l-112-luxury"},{"id":4010,"label":"1.5 l 112 AT Luxury","version":"1.5 l 112 AT Luxury","slug":"15-l-112-at-luxury"},{"id":4011,"label":"1.5 l 112 AT Honor","version":"1.5 l 112 AT Honor","slug":"15-l-112-at-honor"}]},{"id":11012,"label":"X35","slug":"x35","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-x35-420.png","versions":[{"id":4000,"label":"1.5 l 147 AT Luxury","version":"1.5 l 147 AT Luxury","slug":"15-l-147-at-luxury"},{"id":4001,"label":"1.5 l 147 AT Fashion+","version":"1.5 l 147 AT Fashion+","slug":"15-l-147-at-fashion"},{"id":4002,"label":"1.5 l 147 AT Fashion","version":"1.5 l 147 AT Fashion","slug":"15-l-147-at-fashion"}]},{"id":11013,"label":"X55","slug":"x55","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-x55-483.png","versions":[{"id":4003,"label":"1.5 l 185 AT LV2","version":"1.5 l 185 AT LV2","slug":"15-l-185-at-lv2"},{"id":4004,"label":"1.5 l 185 AT LV3","version":"1.5 l 185 AT LV3","slug":"15-l-185-at-lv3"},{"id":4005,"label":"1.5 l 185 AT LV4","version":"1.5 l 185 AT LV4","slug":"15-l-185-at-lv4"}]},{"id":11014,"label":"X7","slug":"x7","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-x7-846.png","versions":[{"id":4006,"label":"LV2","version":"LV2","slug":"lv2"},{"id":4007,"label":"LV3","version":"LV3","slug":"lv3"},{"id":4008,"label":"LV4","version":"LV4","slug":"lv4"}]}]},{"id":12,"label":"Bentley","slug":"bentley","models":[{"id":89,"label":"Bentayga","slug":"bentayga","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-bentayga-650.png","versions":[{"id":1424,"label":"BENTAYGA MULLINER","version":"BENTAYGA MULLINER","slug":"bentayga-mulliner"},{"id":1425,"label":"BENTAYGA","version":"BENTAYGA","slug":"bentayga"},{"id":1426,"label":"NEW BENTAYGA DIESEL","version":"NEW BENTAYGA DIESEL","slug":"new-bentayga-diesel"}]},{"id":92,"label":"Continental ","slug":"continental","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-continental-623.png","versions":[{"id":1417,"label":"GT","version":"GT","slug":"gt"}]},{"id":10113,"label":"Flying Spur","slug":"flying-spur","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-flying spur-110.png","versions":[{"id":1430,"label":"FLYING SPUR V8","version":"FLYING SPUR V8","slug":"flying-spur-v8"},{"id":1431,"label":"NEW FLYING SPUR V8 S","version":"NEW FLYING SPUR V8 S","slug":"new-flying-spur-v8-s"},{"id":1432,"label":"FLYING SPUR W12","version":"FLYING SPUR W12","slug":"flying-spur-w12"},{"id":1433,"label":"NEW FLYING SPUR W12 S","version":"NEW FLYING SPUR W12 S","slug":"new-flying-spur-w12-s"}]},{"id":10112,"label":"Mulsanne","slug":"mulsanne","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-mulsanne-356.png","versions":[{"id":1427,"label":"NEW MULSANNE EXTENDED WHEELBASE","version":"NEW MULSANNE EXTENDED WHEELBASE","slug":"new-mulsanne-extended-wheelbase"},{"id":1428,"label":"NEW MULSANNE SPEED","version":"NEW MULSANNE SPEED","slug":"new-mulsanne-speed"},{"id":1429,"label":"NEW MULSANNE","version":"NEW MULSANNE","slug":"new-mulsanne"}]}]},{"id":14,"label":"BMW","slug":"bmw","models":[{"id":11058,"label":"i5","slug":"i5","body_image_url":"https:\/\/www.moteur.ma\/storage\/media\/images\/models\/nouvelle-i5-656.png","versions":[{"id":4248,"label":"eDrive40 Magn\u00e9tique","ve

C:\Users\PC\AppData\Local\Temp\ipykernel_2836\2360595638.py:6: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  for element in soup.find_all(text=True):

In [19]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(driver.page_source, "html.parser")

# Afficher les 50 premières balises contenant du texte
for i, tag in enumerate(soup.find_all()):
    texte = tag.get_text(strip=True)
    if len(texte) > 5:
        print(f"{i} -> {tag.name} : {texte[:100]}")
    if i >= 50:
        break

0 -> html : Hyundai Creta Hyundai Creta tout option 09-11-21 1ère main 44k 2021 Diesel occasion 508784Agadir_phr
1 -> head : Hyundai Creta Hyundai Creta tout option 09-11-21 1ère main 44k 2021 Diesel occasion 508784Agadir_phr
13 -> script : (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'})
14 -> script : window.dataLayer = window.dataLayer || [];
                    window.dataLayer.push({"lang":"fr","s
17 -> script : window.googletag = window.googletag || { cmd: [] };
27 -> title : Hyundai Creta Hyundai Creta tout option 09-11-21 1ère main 44k 2021 Diesel occasion 508784Agadir_phr

In [20]:
html = driver.page_source

with open("annonce.html", "w", encoding="utf-8") as f:
    f.write(html)

print("Fichier annonce.html créé")

Fichier annonce.html créé

In [21]:
html = driver.page_source

print("__NEXT_DATA__" in html)
print("application/ld+json" in html)

False
False

In [22]:
from selenium.webdriver.common.by import By

elements = driver.find_elements(By.XPATH, "//*")

print("Nombre d'éléments :", len(elements))

for e in elements[:30]:
    text = e.text.strip()
    if text:
        print(text)

Nombre d'éléments : 2650
Neuf
Promotion
Émissions
Actualités
Occasion
Se connecter
Vendez Votre Voiture
0
العربية
opel astra
opel corsa
opel grandland
opel frontera
opel mokka
Seat Leon FR
Seat ibiza
SANTA FE Full Hybrid
taigo
golf 8
T-roc
tiguan
Accueil
Occasion
Acheter une voiture d'occasion
Hyundai Creta
Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Hyundai Creta
225,000 MAD
Voiture
Agadir
Jul 18, 2026
0 vues
Informations Véhicule
Marque: Hyundai Modèle: Creta
Année: 2021 Kilométrage: 44,000 km
Carburant: Diesel Transmission: Automatique
Carrosserie: N/A Couleur: N/A
Nombre de portes 5 Puissance fiscale 6
Spécifications rapides
Hyundai Creta tout option **** ère main 44k.. Veuillez nous contacter pour plus d'informations, bienvenue
Caractéristiques & Options
Premier propriétaire Véhicule préparé
Historique d'accidents Importation neuve
Statut de douane N/A
options
État du véhicule
ABS
Climatisation
Airbags
Fermeture centralisée
Régulateur de vitesse
Vitres électriques
ESP
Navigation GPS
Ordinateur de bord
Radar de recul
Jantes
Limiteur de vitesse
CD / MP3 / Bluetooth
Annonces Similaires
Hyundai Atos
37,000 MAD
il y a 10 minutes
Hyundai Accent
33,000 MAD
il y a 10 minutes
Hyundai Accent
122,000 MAD
il y a 43 minutes
Hyundai Accent
112,000 MAD
il y a 48 minutes
Hyundai Accent
47,000 MAD
il y a 48 minutes
Dernières annonces premium
Premium
BMW Série 1
Casablanca 2011
90,000 MAD
Premium
Kia Picanto
Tétouan 2019
94,000 MAD
Premium
Toyota Verso
Rabat 2012
95,000 MAD
Publié par
AGARRR
Vendeur depuis Jul 2026
Informations Contact
Agadir
Appeler maintenant
Prix Hyundai Creta neuve maroc
HYUNDAI Creta
À partir de
264 900 Dhs
3 Versions
Prix promotionnels du moment
Mahindra
PIK-UP
À partir de
185 900 Dhs
Kia
EV6
À partir de
655 000 Dhs
Kia
Picanto
À partir de
154 900 Dhs
Honda
CR-V
À partir de
450 000 Dhs
Audi
A3 Sportback
À partir de
351 000 Dhs
Opel
Astra
À partir de
269 000 Dhs
Citroën
C5 Aircross
À partir de
292 900 Dhs
Dernières voitures neuves
NOUVEAU
Fiat
Grizzly
1.2 MHEV Hybride léger
Prix sur demande
2026 · SUV et 4x4
NOUVEAU
DENZA
D9
100 % électrique (BEV)
Prix sur demande
2026 · SUV et 4x4
NOUVEAU
DENZA
D9
DM-i Hybride rechargeable (PHEV)
889 900 Dhs
2026 · SUV et 4x4
NOUVEAU
DENZA
B8
2.0 Turbo essence PHEV
869 900 Dhs
2026 · SUV et 4x4
Comparez les voitures neuves au Maroc
Analysez les prix, motorisations et équipements pour faire le meilleur choix.
BMW
X4
xDrive 20d XLINE
Porsche
Cayenne
Turbo E-Hybrid
BMW VS Porsche
Renault
Arkana
E-Tech full hybrid 145 ch Equi...
BMW
Z4
ROADSTER M40I M TwinPower Turb...
Renault VS BMW
Lynk & Co
08
1.5 T 380 PHEV
Ford
Territory
1.5 Duratec 150 AT Titanium X
Lynk & Co VS Ford
Toutes les comparaisons neuves
GUIDES PRIX VOITURES NEUVES AU MAROC
Voitures neuves Maroc
Voitures hybrides Maroc
Voitures électriques neuves Maroc
Voitures neuves moins de 200 000 DH
SUV neufs Maroc
Voitures Diesel neuves
Voitures essence maroc
Voitures automatiques Maroc
Voitures familiales neuves
Voitures neuves au Maroc
أبارث neuve Maroc
سمارت neuve Maroc
ميني neuve Maroc
لينك آند كو neuve Maroc
ماهيندرا neuve Maroc
دفسك neuve Maroc
لكزس neuve Maroc
ألفا روميو neuve Maroc
نيو-موتورز neuve Maroc
بي واي دي neuve Maroc
ألبين neuve Maroc
سيريس neuve Maroc
بايك neuve Maroc
كي جي إم neuve Maroc
سانغ يونغ neuve Maroc
دينزا neuve Maroc
مرسيدس-بنز neuve Maroc
سيات neuve Maroc
تاتا neuve Maroc
فيراري neuve Maroc
جاغوار neuve Maroc
فيات neuve Maroc
فورد neuve Maroc
مازيراتي neuve Maroc
بيجو neuve Maroc
Modèles neufs populaires
بي ام دبليو سيري 3 neuve Maroc
بي ام دبليو سيري 2 neuve Maroc
ستروين سي 4 neuve Maroc
ستروين سي 3 neuve Maroc
داسيا سبرينج neuve Maroc
داسيا لوجان neuve Maroc
فورد رينجر neuve Maroc
فورد تيريتوري neuve Maroc
هيونداي أكسنت neuve Maroc
هيونداي توسون neuve Maroc
كيا إي في 3 neuve Maroc
كيا بي في 5 باسنجر neuve Maroc
مرسيدس-بنز الفئة أ neuve Maroc
مرسيدس-بنز فئة GLC neuve Maroc
أوبل جراندلاند neuve Maroc
أوبل روكس-إي neuve Maroc
بيجو لاندتريك neuve Maroc
بيجو 408 neuve Maroc
رينو كانغو neuve Maroc
رينو 5 إي- تيك neuve Maroc
تويوتا لاند كروزر neuve Maroc
تويوتا كورولا neuve Maroc
فولكس فاجن تواريج neuve Maroc
فولكس فاجن تي كروس neuve Maroc
Voitures occasion Maroc
فولكس فاجن occasion Maroc
مرسيدس-بنز occasion Maroc
رينو occasion Maroc
بيجو occasion Maroc
داسيا occasion Maroc
هيونداي occasion Maroc
أودي occasion Maroc
بي ام دبليو occasion Maroc
فورد occasion Maroc
فيات occasion Maroc
كيا occasion Maroc
لاند روفر occasion Maroc
ستروين occasion Maroc
تويوتا occasion Maroc
أوبل occasion Maroc
نيسان occasion Maroc
جيب occasion Maroc
شكودا occasion Maroc
سيات occasion Maroc
بورش occasion Maroc
فولفو occasion Maroc
ألفا روميو occasion Maroc
هوندا occasion Maroc
جاغوار occasion Maroc
A propos
Accueil
Qui sommes-nous?
Offres Premium
Offres Premium Pro
Votre publicité sur MOTEUR.MA
Showrooms Pro
Dernières promotions 2026
La Comparaison des voitures neuves
Demander le prix de votre voiture
Service Bi3 lia
Les emissions
Actualités Auto
Forum d'aide automobile
Notre réseau de partenaires
Conditions générales d'utilisation
Conditions générales de vente
Contactez-nous
Ils parlent de nous - Presse
Plan du site
بالعــربيـة
© 2009-2026 MOTEUR.ma : Guide d'achat des voitures neuves et d'occasion au Maroc
Conformément à la loi 09-08, vous disposez d'un droit d'accès, de rectification et d'opposition au traitement de vos données personnelles. Ce traitement a été autorisé par la CNDP sous le numéro D-W-219/2017
Le site MOTEUR.ma ne joue que le rôle d'intermédiaire entre acheteurs et vendeurs. Nous n'intervenons pas dans les transactions d'achat et de vente. En conséquence, ne peut être tenu responsable de tous problèmes survenus après le déroulement des transactions entre les deux parties.

In [23]:
from selenium.webdriver.common.by import By

elements = driver.find_elements(By.XPATH, "//*[contains(text(),'Hyundai')]")

print("Nombre d'éléments :", len(elements))

for e in elements:
    print("--------------------------------")
    print(e.text)

Nombre d'éléments : 22
--------------------------------

--------------------------------

--------------------------------
Hyundai Creta
--------------------------------
Hyundai
--------------------------------
Hyundai
--------------------------------
Hyundai
--------------------------------
Hyundai Creta
--------------------------------
Hyundai
--------------------------------
Hyundai Creta tout option **** ère main 44k.. Veuillez nous contacter pour plus d'informations, bienvenue
--------------------------------
Hyundai Atos
--------------------------------
Hyundai Accent
--------------------------------
Hyundai Accent
--------------------------------
Hyundai Accent
--------------------------------
Hyundai Accent
--------------------------------

--------------------------------
Hyundai Accent
--------------------------------
Prix Hyundai Creta neuve maroc
--------------------------------

--------------------------------

--------------------------------

--------------------------------

--------------------------------

In [24]:
from selenium.webdriver.common.by import By

elements = driver.find_elements(By.XPATH, "//*[contains(text(),'DH')]")

print("Nombre :", len(elements))

for e in elements:
    print("----------------")
    print(e.text)

Nombre : 2
----------------

----------------
Voitures neuves moins de 200 000 DH

In [25]:
from selenium.webdriver.common.by import By

elements = driver.find_elements(By.XPATH, "//*")

for e in elements:
    texte = e.text.strip()

    if "2021" in texte or "Diesel" in texte or "44k" in texte:
        print("----------------")
        print(texte)

InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=150.0.7871.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff72ee50d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff72ee50d80+15600]
	chromedriver!(No symbol) [0x7ff72e9a594d]
	chromedriver!(No symbol) [0x7ff72e991102]
	chromedriver!(No symbol) [0x7ff72e9b704c]
	chromedriver!(No symbol) [0x7ff72ea30790]
	chromedriver!(No symbol) [0x7ff72ea4d902]
	chromedriver!(No symbol) [0x7ff72e9f2e6c]
	chromedriver!(No symbol) [0x7ff72e9f3d93]
	chromedriver!GetHandleVerifier [0x7ff72f436431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff72f430a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff72f455865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff72ee6dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff72ee7661c+3ae9c]
	chromedriver!GetHandleVerifier [0x7ff72ee5ab74+1f3f4]
	chromedriver!GetHandleVerifier [0x7ff72ee5ad04+1f584]
	chromedriver!GetHandleVerifier [0x7ff72ee3d9d7+2257]
	KERNEL32!BaseThreadInitThunk [0x7ffc6eaee957+17]
	ntdll!RtlUserThreadStart [0x7ffc6fa2ad6c+2c]

In [26]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)

In [27]:
driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/")

In [28]:
import time

time.sleep(5)

print(driver.title)

Voiture occasion| Moteur.ma

In [29]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(driver.page_source, "html.parser")

liens = soup.find_all("a", href=True)

print("Nombre de liens :", len(liens))

Nombre de liens : 473

In [30]:
annonces = []

for lien in liens:
    href = lien.get("href")

    if href and "detail-annonce" in href:
        annonces.append(href)

# Supprimer les doublons
annonces = list(set(annonces))

print("Nombre d'annonces uniques :", len(annonces))

Nombre d'annonces uniques : 30

In [31]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time

tous_les_liens = []

for page in range(1, 6):   # 5 pages pour commencer
    url = f"https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?page={page}"

    driver.get(url)
    time.sleep(3)

    soup = BeautifulSoup(driver.page_source, "html.parser")

    liens = soup.find_all("a", href=True)

    for lien in liens:
        href = lien.get("href")
        if href and "detail-annonce" in href:
            if href not in tous_les_liens:
                tous_les_liens.append(href)

    print(f"Page {page} terminée - Total : {len(tous_les_liens)}")

print("\nNombre total d'annonces :", len(tous_les_liens))

Page 1 terminée - Total : 30
Page 2 terminée - Total : 60
Page 3 terminée - Total : 90
Page 4 terminée - Total : 120
Page 5 terminée - Total : 150

Nombre total d'annonces : 150

In [32]:
url = tous_les_liens[0]

print(url)

driver.get(url)

import time
time.sleep(3)

print(driver.title)

https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508851/renault-talisman.html

InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=150.0.7871.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff72ee50d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff72ee50d80+15600]
	chromedriver!(No symbol) [0x7ff72e9a594d]
	chromedriver!(No symbol) [0x7ff72e991102]
	chromedriver!(No symbol) [0x7ff72e9b704c]
	chromedriver!(No symbol) [0x7ff72ea30790]
	chromedriver!(No symbol) [0x7ff72ea4d902]
	chromedriver!(No symbol) [0x7ff72e9f2e6c]
	chromedriver!(No symbol) [0x7ff72e9f3d93]
	chromedriver!GetHandleVerifier [0x7ff72f436431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff72f430a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff72f455865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff72ee6dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff72ee7661c+3ae9c]
	chromedriver!GetHandleVerifier [0x7ff72ee5ab74+1f3f4]
	chromedriver!GetHandleVerifier [0x7ff72ee5ad04+1f584]
	chromedriver!GetHandleVerifier [0x7ff72ee3d9d7+2257]
	KERNEL32!BaseThreadInitThunk [0x7ffc6eaee957+17]
	ntdll!RtlUserThreadStart [0x7ffc6fa2ad6c+2c]

In [33]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

print("Chrome Selenium lancé")

Chrome Selenium lancé

In [34]:
url = tous_les_liens[0]

print(url)

driver.get(url)

https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508851/renault-talisman.html

In [35]:
print(driver.title)

Renault Talisman Talisman 2.0 diesel 4control 2022 Diesel occasion 508851_phrase Maroc| Moteur.ma

In [36]:
from selenium.webdriver.common.by import By

# récupérer tout le texte visible de la page
texte = driver.find_element(By.TAG_NAME, "body").text

print(texte[:2000])

Neuf
Promotion
Émissions
Actualités
Occasion
Se connecter
Vendez Votre Voiture
0
العربية
Offres du moment
DFSK E5
magnite
chery tiggo 7 pro
dacia sandero stepway
opel astra
opel corsa
opel grandland
opel frontera
opel mokka
Seat Leon FR
Seat ibiza
Accueil
Occasion
Acheter une voiture d'occasion
Renault Talisman
Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki

In [37]:
from selenium.webdriver.common.by import By

# chercher les éléments contenant Renault Talisman
elements = driver.find_elements(By.XPATH, "//*[contains(text(),'Renault Talisman')]")

print("Nombre trouvé :", len(elements))

for e in elements:
    print("TAG :", e.tag_name)
    print("CLASSE :", e.get_attribute("class"))
    print("TEXTE :", e.text[:200])
    print("----------------")

Nombre trouvé : 2
TAG : title
CLASSE :
TEXTE :
----------------
TAG : li
CLASSE : breadcrumb-item1 active
TEXTE : Renault Talisman
----------------

In [38]:
from selenium.webdriver.common.by import By

mots = ["Prix", "Année", "Diesel", "Kilométrage", "Transmission", "Boîte"]

for mot in mots:
    elements = driver.find_elements(By.XPATH, f"//*[contains(text(),'{mot}')]")
    print("\n---", mot, "---")
    print("Nombre :", len(elements))
    
    for e in elements[:3]:
        print(e.tag_name, e.get_attribute("class"), "=>", e.text[:200])

--- Prix ---
Nombre : 11
a h3 card-title => Prix promotionnels du moment
div price-value text-primary mb-2 =>
div price-value text-primary mb-2 => Prix sur demande

--- Année ---
Nombre : 1
span font-weight-bold => Année:

--- Diesel ---
Nombre : 4
title  =>
script  =>
td  => Diesel

--- Kilométrage ---
Nombre : 1
span font-weight-bold => Kilométrage:

--- Transmission ---
Nombre : 1
span font-weight-bold => Transmission:

--- Boîte ---
Nombre : 0

In [39]:
from selenium.webdriver.common.by import By

# récupérer toutes les lignes du tableau des caractéristiques
rows = driver.find_elements(By.TAG_NAME, "tr")

for row in rows:
    print(row.text)

Marque: Renault Modèle: Talisman
Année: 2022 Kilométrage: 44,567 km
Carburant: Diesel Transmission: Automatique
Carrosserie: N/A Couleur: N/A
Puissance fiscale 8
Premier propriétaire Véhicule préparé
Historique d'accidents Importation neuve
Statut de douane N/A

In [40]:
from selenium.webdriver.common.by import By

def extraire_annonce(driver):
    data = {}

    rows = driver.find_elements(By.TAG_NAME, "tr")

    for row in rows:
        texte = row.text.strip()

        if ":" in texte:
            parties = texte.split()

            # extraction simple par mots clés
            if "Marque:" in texte:
                data["Marque"] = texte.split("Marque:")[1].split()[0]

            if "Modèle:" in texte:
                data["Modele"] = texte.split("Modèle:")[1].split()[0]

            if "Année:" in texte:
                data["Annee"] = texte.split("Année:")[1].split()[0]

            if "Kilométrage:" in texte:
                data["Kilometrage"] = texte.split("Kilométrage:")[1].split()[0]

            if "Carburant:" in texte:
                data["Carburant"] = texte.split("Carburant:")[1].split()[0]

            if "Transmission:" in texte:
                data["Transmission"] = texte.split("Transmission:")[1].split()[0]

    return data

In [41]:
annonce = extraire_annonce(driver)

print(annonce)

{'Marque': 'Renault', 'Modele': 'Talisman', 'Annee': '2022', 'Kilometrage': '44,567', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}

In [42]:
from selenium.webdriver.common.by import By

prix_elements = driver.find_elements(By.CLASS_NAME, "price-value")

print("Nombre :", len(prix_elements))

for p in prix_elements:
    print("PRIX :", p.text)

Nombre : 20
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX : 173 900 Dhs
PRIX : Prix sur demande
PRIX : Prix sur demande
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :

In [43]:
from selenium.webdriver.common.by import By

prix_elements = driver.find_elements(By.CLASS_NAME, "price-value")

print("Nombre :", len(prix_elements))

for p in prix_elements:
    print("PRIX :", p.text)

Nombre : 20
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX : 173 900 Dhs
PRIX : Prix sur demande
PRIX : Prix sur demande
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :

In [44]:
dataset = []

In [45]:
for url in tous_les_liens:
    driver.get(url)
    time.sleep(2)

    annonce = extraire_annonce(driver)
    dataset.append(annonce)

print(dataset[:3])

[{'Marque': 'Renault', 'Modele': 'Talisman', 'Annee': '2022', 'Kilometrage': '44,567', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}, {'Marque': 'Ford', 'Modele': 'B', 'Annee': '2014', 'Kilometrage': '225,000', 'Carburant': 'Essence', 'Transmission': 'Manuelle'}, {'Marque': 'Hyundai', 'Modele': 'i40', 'Annee': '2013', 'Kilometrage': '208,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}]

In [46]:
import pandas as pd

df = pd.DataFrame(dataset)

df.to_csv("voitures_moteur.csv", index=False)

df.head()

    Marque    Modele Annee Kilometrage Carburant Transmission
0  Renault  Talisman  2022      44,567    Diesel  Automatique
1     Ford         B  2014     225,000   Essence     Manuelle
2  Hyundai       i40  2013     208,000    Diesel  Automatique
3  Renault    Megane  2018     150,000    Diesel     Manuelle
4  Renault      Clio  2024     123,000    Diesel     Manuelle

In [1]:
prix_elements = driver.find_elements(By.CLASS_NAME, "price-value")

for p in prix_elements:
    print(p.text)

NameError: name 'driver' is not defined

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

from selenium.webdriver.common.by import By

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

print("Driver OK")

Driver OK

In [3]:
url = tous_les_liens[0]

driver.get(url)

NameError: name 'tous_les_liens' is not defined

In [4]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

from selenium.webdriver.common.by import By

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

In [5]:
url = "https://www.moteur.ma/fr/voiture/occasion/"

driver.get(url)

In [6]:
import time
time.sleep(5)

In [7]:
liens = driver.find_elements(By.TAG_NAME, "a")

tous_les_liens = []

for lien in liens:
    href = lien.get_attribute("href")
    
    if href and "/detail-annonce/" in href:
        tous_les_liens.append(href)

# supprimer les doublons
tous_les_liens = list(set(tous_les_liens))

print("Nombre d'annonces :", len(tous_les_liens))
print(tous_les_liens[:5])

Nombre d'annonces : 0
[]

In [8]:
from selenium.webdriver.common.by import By

liens = driver.find_elements(By.TAG_NAME, "a")

print("Nombre total de liens :", len(liens))

for lien in liens[:50]:
    print(lien.text, "---->", lien.get_attribute("href"))

Nombre total de liens : 474
 ----> None
 ----> https://www.moteur.ma/
 ----> https://www.moteur.ma/
 ----> https://www.moteur.ma/fr/neuf/voiture/
 ----> https://www.moteur.ma/
 ----> https://www.moteur.ma/
 ----> https://www.moteur.ma/
Neuf ----> https://www.moteur.ma/fr/neuf/
 ----> https://www.moteur.ma/fr/neuf/
 ----> https://www.moteur.ma/fr/neuf/voiture/
 ----> https://www.moteur.ma/fr/neuf/voiture/
 ----> https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/
 ----> https://www.moteur.ma/fr/neuf/rubrique/
 ----> https://www.moteur.ma/fr/neuf/comparatif-voiture-neuf/
 ----> https://www.moteur.ma/fr/neuf/moto/
 ----> https://www.moteur.ma/fr/neuf/moto/
 ----> https://www.moteur.ma/fr/neuf/promotion-moto-neuve-maroc/
 ----> https://www.moteur.ma/fr/neuf/camion/
 ----> https://www.moteur.ma/fr/neuf/camion/
Promotion ----> https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/
 ----> https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/
 ----> https://www.moteur.ma/fr/neuf/rubrique/
Émissions ----> https://www.moteur.ma/fr/guide-achat/
 ----> https://www.moteur.ma/fr/guide-achat/ajinjerbo/
 ----> https://www.moteur.ma/fr/guide-achat/parlons-auto/
 ----> https://www.moteur.ma/fr/guide-achat/zoom-auto/
 ----> https://www.moteur.ma/fr/guide-achat/live-events/
Actualités ----> https://www.moteur.ma/fr/guide-achat/actualite/
 ----> https://www.moteur.ma/fr/guide-achat/actualite/
 ----> https://www.moteur.ma/fr/forum/
Occasion ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
 ----> https://www.moteur.ma/fr/voiture/vendez-voiture-occasion/
 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
 ----> https://www.moteur.ma/fr/voiture/prix-voiture-occasion-maroc/?src=menu
 ----> https://www.moteur.ma/fr/moto/achat-moto-occasion/
 ----> https://www.moteur.ma/fr/moto/vendez-moto-occasion/
 ----> https://www.moteur.ma/fr/moto/achat-moto-occasion/
 ----> https://www.moteur.ma/fr/camion/achat-camion-occasion/
 ----> https://www.moteur.ma/fr/camion/vendez-camion-occasion/
 ----> https://www.moteur.ma/fr/camion/achat-camion-occasion/
 ----> https://www.moteur.ma/fr/voiture/concessionnaire-voiture-occasion/
 ----> https://www.moteur.ma/fr/voiture/concessionnaire-voiture-occasion/
 ----> https://www.moteur.ma/fr/voiture/location-voiture/
 ----> https://www.moteur.ma/fr/voiture/agences-location/
 ----> https://www.moteur.ma/fr/advertisers/login/
 ----> https://www.moteur.ma/fr/advertisers/register/
 ----> https://www.moteur.ma/fr/voiture/vendez-voiture-occasion/
Se connecter ----> https://www.moteur.ma/fr/advertisers/login/
Vendez Votre Voiture ----> https://www.moteur.ma/fr/voiture/vendez-voiture-occasion/

In [9]:
liens_annonces = []

for lien in liens:
    href = lien.get_attribute("href")
    
    if href:
        if "annonce" in href or "detail" in href:
            liens_annonces.append(href)

print("Nombre trouvé :", len(liens_annonces))

for l in liens_annonces[:10]:
    print(l)

Nombre trouvé : 0

In [10]:
from selenium.webdriver.common.by import By

# chercher les liens qui contiennent des modèles de voitures
elements = driver.find_elements(By.TAG_NAME, "a")

compteur = 0

for e in elements:
    texte = e.text.strip()
    href = e.get_attribute("href")

    if texte and len(texte) > 5:
        if any(marque in texte for marque in ["Renault", "Audi", "BMW", "Mercedes", "Dacia", "Peugeot", "Ford"]):
            print("TEXTE :", texte)
            print("LIEN :", href)
            print("----------------")
for e in elements:
    texte = e.text.strip()
    href = e.get_attribute("href")

    if href:
        print(texte[:50], "---->", href)            compteur += 1

print("Total :", compteur)

TEXTE : Mercedes‑Benz
LIEN : https://www.moteur.ma/fr/neuf/camion/mercedes-benz/
----------------
TEXTE : Mercedes‑Benz
LIEN : https://www.moteur.ma/fr/neuf/camion/mercedes-benz/
----------------
TEXTE : BMW VS Zeekr
LIEN : https://www.moteur.ma/fr/neuf/comparatif-voiture-neuf/bmw-x5-mhev-xdrive-50e-pack-m-edition-vs-zeekr-7x-475-kw-at-awd-privilege-3052-4399.html
----------------
TEXTE : Mercedes-Benz VS BMW
LIEN : https://www.moteur.ma/fr/neuf/comparatif-voiture-neuf/mercedes-benz-classe-gls-mhev-450-d-4matic-amg-line-vs-bmw-x7-mhev-xdrive-40i-sport-1388-4552.html
----------------
Total : 4

In [11]:
for e in elements:
    texte = e.text.strip()
    href = e.get_attribute("href")

    if href:
        print(texte[:50], "---->", href)

 ----> https://www.moteur.ma/
 ----> https://www.moteur.ma/
 ----> https://www.moteur.ma/fr/neuf/voiture/
 ----> https://www.moteur.ma/
 ----> https://www.moteur.ma/
 ----> https://www.moteur.ma/
Neuf ----> https://www.moteur.ma/fr/neuf/
 ----> https://www.moteur.ma/fr/neuf/
 ----> https://www.moteur.ma/fr/neuf/voiture/
 ----> https://www.moteur.ma/fr/neuf/voiture/
 ----> https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/
 ----> https://www.moteur.ma/fr/neuf/rubrique/
 ----> https://www.moteur.ma/fr/neuf/comparatif-voiture-neuf/
 ----> https://www.moteur.ma/fr/neuf/moto/
 ----> https://www.moteur.ma/fr/neuf/moto/
 ----> https://www.moteur.ma/fr/neuf/promotion-moto-neuve-maroc/
 ----> https://www.moteur.ma/fr/neuf/camion/
 ----> https://www.moteur.ma/fr/neuf/camion/
Promotion ----> https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/
 ----> https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/
 ----> https://www.moteur.ma/fr/neuf/rubrique/
Émissions ----> https://www.moteur.ma/fr/guide-achat/
 ----> https://www.moteur.ma/fr/guide-achat/ajinjerbo/
 ----> https://www.moteur.ma/fr/guide-achat/parlons-auto/
 ----> https://www.moteur.ma/fr/guide-achat/zoom-auto/
 ----> https://www.moteur.ma/fr/guide-achat/live-events/
Actualités ----> https://www.moteur.ma/fr/guide-achat/actualite/
 ----> https://www.moteur.ma/fr/guide-achat/actualite/
 ----> https://www.moteur.ma/fr/forum/
Occasion ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
 ----> https://www.moteur.ma/fr/voiture/vendez-voiture-occasion/
 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
 ----> https://www.moteur.ma/fr/voiture/prix-voiture-occasion-maroc/?src=menu
 ----> https://www.moteur.ma/fr/moto/achat-moto-occasion/
 ----> https://www.moteur.ma/fr/moto/vendez-moto-occasion/
 ----> https://www.moteur.ma/fr/moto/achat-moto-occasion/
 ----> https://www.moteur.ma/fr/camion/achat-camion-occasion/
 ----> https://www.moteur.ma/fr/camion/vendez-camion-occasion/
 ----> https://www.moteur.ma/fr/camion/achat-camion-occasion/
 ----> https://www.moteur.ma/fr/voiture/concessionnaire-voiture-occasion/
 ----> https://www.moteur.ma/fr/voiture/concessionnaire-voiture-occasion/
 ----> https://www.moteur.ma/fr/voiture/location-voiture/
 ----> https://www.moteur.ma/fr/voiture/agences-location/
 ----> https://www.moteur.ma/fr/advertisers/login/
 ----> https://www.moteur.ma/fr/advertisers/register/
 ----> https://www.moteur.ma/fr/voiture/vendez-voiture-occasion/
Se connecter ----> https://www.moteur.ma/fr/advertisers/login/
Vendez Votre Voiture ----> https://www.moteur.ma/fr/voiture/vendez-voiture-occasion/
 ----> https://www.moteur.ma/fr/neuf/opel/astra/promotion/73173db04d247583e8f967ecfd5825fa/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-astra-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/corsa/promotion/da67bee274cc7ae9e437a9d539b0e564/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-corsa-german-days-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/grandland/promotion/53fb9c0e1f205046d3b2f55dbe1a23b6/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-grandland-german-days-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/frontera/promotion/6c03c9feb4e3e55df5024be14e7fb4d7/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-frontera-german-days-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/mokka/promotion/2d01aa90127402b75416803ca7e6a563/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-mokka-german-days-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/seat/leon/promotion/309774539c62e34b46dd196402551cd6/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=seat-leon-fr-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/seat/ibiza/promotion/e11353238816b345c9caadacdaf714b6/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=seat-ibiza-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/hyundai/santa-fe/promotion/9136333844b4f9237ac101d0e67faff9/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=hyundai-santafe-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/volkswagen/taigo/promotion/99347b16e4891ad24a6d30082ac036e4/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=vw-taigo-juillet-aout-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/volkswagen/golf-8/promotion/7ea23356650b47748c85413d2303a37d/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=vw-golf-jullet-aout-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/volkswagen/t-roc/promotion/126a8e24f0a07dd183a8a3ad0e0d9f69/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=vw-t-roc-juillet-aout-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/volkswagen/tiguan/promotion/28d65fc52987d4bdbc023377e20fdd95/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=vw-tiguan-juillet-aout-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/rubrique/
 ----> https://www.moteur.ma/fr/neuf/dfsk/e5/promotion/14d406a18f5300fb4a7eaa05837877e2/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=dfsk-e5-mars-decembre-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/nissan/magnite/promotion/44d9ba17c5ca1561cf9cb915fc8cd42e/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=nissan-magnite-avril-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/chery/tiggo-7-pro/promotion/7b655ab61843a82e103ffdb2921e6125/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=chery-tiggo-7-pro-juin-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/dacia/sandero/promotion/8e6dbd2e0c02e2058f5536744a14675f/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=dacia-sandero-juin-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/astra/promotion/73173db04d247583e8f967ecfd5825fa/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-astra-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/corsa/promotion/da67bee274cc7ae9e437a9d539b0e564/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-corsa-german-days-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/grandland/promotion/53fb9c0e1f205046d3b2f55dbe1a23b6/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-grandland-german-days-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/frontera/promotion/6c03c9feb4e3e55df5024be14e7fb4d7/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-frontera-german-days-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/mokka/promotion/2d01aa90127402b75416803ca7e6a563/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-mokka-german-days-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/seat/leon/promotion/309774539c62e34b46dd196402551cd6/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=seat-leon-fr-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/seat/ibiza/promotion/e11353238816b345c9caadacdaf714b6/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=seat-ibiza-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/hyundai/santa-fe/promotion/9136333844b4f9237ac101d0e67faff9/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=hyundai-santafe-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/volkswagen/taigo/promotion/99347b16e4891ad24a6d30082ac036e4/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=vw-taigo-juillet-aout-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/volkswagen/golf-8/promotion/7ea23356650b47748c85413d2303a37d/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=vw-golf-jullet-aout-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/volkswagen/t-roc/promotion/126a8e24f0a07dd183a8a3ad0e0d9f69/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=vw-t-roc-juillet-aout-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/volkswagen/tiguan/promotion/28d65fc52987d4bdbc023377e20fdd95/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=vw-tiguan-juillet-aout-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/rubrique/
 ----> https://www.moteur.ma/fr/neuf/dfsk/e5/promotion/14d406a18f5300fb4a7eaa05837877e2/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=dfsk-e5-mars-decembre-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/nissan/magnite/promotion/44d9ba17c5ca1561cf9cb915fc8cd42e/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=nissan-magnite-avril-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/chery/tiggo-7-pro/promotion/7b655ab61843a82e103ffdb2921e6125/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=chery-tiggo-7-pro-juin-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/dacia/sandero/promotion/8e6dbd2e0c02e2058f5536744a14675f/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=dacia-sandero-juin-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/astra/promotion/73173db04d247583e8f967ecfd5825fa/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-astra-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/corsa/promotion/da67bee274cc7ae9e437a9d539b0e564/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-corsa-german-days-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/grandland/promotion/53fb9c0e1f205046d3b2f55dbe1a23b6/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-grandland-german-days-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/frontera/promotion/6c03c9feb4e3e55df5024be14e7fb4d7/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-frontera-german-days-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/opel/mokka/promotion/2d01aa90127402b75416803ca7e6a563/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-mokka-german-days-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/seat/leon/promotion/309774539c62e34b46dd196402551cd6/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=seat-leon-fr-juillet-2026&utm_content=btn-header-category
 ----> https://www.moteur.ma/fr/neuf/seat/ibiza/promotion/e11353238816b345c9caadacdaf714b6/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=seat-ibiza-juillet-2026&utm_content=btn-header-category
Voitures ----> https://www.moteur.ma/fr/neuf/voiture/
Motos ----> https://www.moteur.ma/fr/neuf/moto/
Camions ----> https://www.moteur.ma/fr/neuf/camion/
 ----> https://www.moteur.ma/fr/neuf/voiture/jetour/
 ----> https://www.moteur.ma/fr/neuf/voiture/kgm/
 ----> https://www.moteur.ma/fr/neuf/voiture/kia/
 ----> https://www.moteur.ma/fr/neuf/voiture/land-rover/
 ----> https://www.moteur.ma/fr/neuf/voiture/leapmotor/
 ----> https://www.moteur.ma/fr/neuf/voiture/lexus/
 ----> https://www.moteur.ma/fr/neuf/voiture/lynk-co/
 ----> https://www.moteur.ma/fr/neuf/voiture/mahindra/
 ----> https://www.moteur.ma/fr/neuf/voiture/maserati/
 ----> https://www.moteur.ma/fr/neuf/voiture/mazda/
 ----> https://www.moteur.ma/fr/neuf/voiture/mercedes-benz/
 ----> https://www.moteur.ma/fr/neuf/voiture/mg/
 ----> https://www.moteur.ma/fr/neuf/voiture/mini/
 ----> https://www.moteur.ma/fr/neuf/voiture/mitsubishi/
 ----> https://www.moteur.ma/fr/neuf/voiture/neo-motors/
 ----> https://www.moteur.ma/fr/neuf/voiture/nissan/
 ----> https://www.moteur.ma/fr/neuf/voiture/omoda/
 ----> https://www.moteur.ma/fr/neuf/voiture/opel/
 ----> https://www.moteur.ma/fr/neuf/voiture/peugeot/
 ----> https://www.moteur.ma/fr/neuf/voiture/porsche/
 ----> https://www.moteur.ma/fr/neuf/voiture/renault/
 ----> https://www.moteur.ma/fr/neuf/voiture/rox/
 ----> https://www.moteur.ma/fr/neuf/voiture/seat/
 ----> https://www.moteur.ma/fr/neuf/voiture/seres/
 ----> https://www.moteur.ma/fr/neuf/voiture/skoda/
 ----> https://www.moteur.ma/fr/neuf/voiture/smart/
 ----> https://www.moteur.ma/fr/neuf/voiture/soueast/
 ----> https://www.moteur.ma/fr/neuf/voiture/ssangyong/
 ----> https://www.moteur.ma/fr/neuf/voiture/suzuki/
 ----> https://www.moteur.ma/fr/neuf/voiture/tata/
 ----> https://www.moteur.ma/fr/neuf/voiture/tesla/
 ----> https://www.moteur.ma/fr/neuf/voiture/toyota/
 ----> https://www.moteur.ma/fr/neuf/voiture/volkswagen/
 ----> https://www.moteur.ma/fr/neuf/voiture/volvo/
 ----> https://www.moteur.ma/fr/neuf/voiture/xpeng/
 ----> https://www.moteur.ma/fr/neuf/voiture/zeekr/
Abarth ----> https://www.moteur.ma/fr/neuf/voiture/abarth/
Alfa Romeo ----> https://www.moteur.ma/fr/neuf/voiture/alfa-romeo/
Alpine ----> https://www.moteur.ma/fr/neuf/voiture/alpine/
Aston Martin ----> https://www.moteur.ma/fr/neuf/voiture/aston-martin/
Audi ----> https://www.moteur.ma/fr/neuf/voiture/audi/
BAIC ----> https://www.moteur.ma/fr/neuf/voiture/baic/
Bentley ----> https://www.moteur.ma/fr/neuf/voiture/bentley/
BMW ----> https://www.moteur.ma/fr/neuf/voiture/bmw/
 ----> https://www.moteur.ma/fr/neuf/voiture/byd/
 ----> https://www.moteur.ma/fr/neuf/voiture/changan/
 ----> https://www.moteur.ma/fr/neuf/voiture/chery/
 ----> https://www.moteur.ma/fr/neuf/voiture/chevrolet/
 ----> https://www.moteur.ma/fr/neuf/voiture/citroen/
 ----> https://www.moteur.ma/fr/neuf/voiture/cupra/
 ----> https://www.moteur.ma/fr/neuf/voiture/dacia/
 ----> https://www.moteur.ma/fr/neuf/voiture/deepal/
 ----> https://www.moteur.ma/fr/neuf/voiture/denza/
 ----> https://www.moteur.ma/fr/neuf/voiture/dfsk/
 ----> https://www.moteur.ma/fr/neuf/voiture/dongfeng/
 ----> https://www.moteur.ma/fr/neuf/voiture/ds/
 ----> https://www.moteur.ma/fr/neuf/voiture/exeed/
 ----> https://www.moteur.ma/fr/neuf/voiture/ferrari/
 ----> https://www.moteur.ma/fr/neuf/voiture/fiat/
 ----> https://www.moteur.ma/fr/neuf/voiture/ford/
 ----> https://www.moteur.ma/fr/neuf/voiture/foton/
 ----> https://www.moteur.ma/fr/neuf/voiture/gac/
 ----> https://www.moteur.ma/fr/neuf/voiture/gaz/
 ----> https://www.moteur.ma/fr/neuf/voiture/geely/
 ----> https://www.moteur.ma/fr/neuf/voiture/gwm/
 ----> https://www.moteur.ma/fr/neuf/voiture/honda/
 ----> https://www.moteur.ma/fr/neuf/voiture/hyundai/
 ----> https://www.moteur.ma/fr/neuf/voiture/isuzu/
 ----> https://www.moteur.ma/fr/neuf/voiture/jac/
 ----> https://www.moteur.ma/fr/neuf/voiture/jaecoo/
 ----> https://www.moteur.ma/fr/neuf/voiture/jaguar/
 ----> https://www.moteur.ma/fr/neuf/voiture/jeep/
 ----> https://www.moteur.ma/fr/neuf/voiture/jetour/
 ----> https://www.moteur.ma/fr/neuf/voiture/kgm/
 ----> https://www.moteur.ma/fr/neuf/voiture/kia/
 ----> https://www.moteur.ma/fr/neuf/voiture/land-rover/
 ----> https://www.moteur.ma/fr/neuf/voiture/leapmotor/
 ----> https://www.moteur.ma/fr/neuf/voiture/lexus/
 ----> https://www.moteur.ma/fr/neuf/voiture/lynk-co/
 ----> https://www.moteur.ma/fr/neuf/voiture/mahindra/
 ----> https://www.moteur.ma/fr/neuf/voiture/maserati/
 ----> https://www.moteur.ma/fr/neuf/voiture/mazda/
 ----> https://www.moteur.ma/fr/neuf/voiture/mercedes-benz/
 ----> https://www.moteur.ma/fr/neuf/voiture/mg/
 ----> https://www.moteur.ma/fr/neuf/voiture/mini/
 ----> https://www.moteur.ma/fr/neuf/voiture/mitsubishi/
 ----> https://www.moteur.ma/fr/neuf/voiture/neo-motors/
 ----> https://www.moteur.ma/fr/neuf/voiture/nissan/
 ----> https://www.moteur.ma/fr/neuf/voiture/omoda/
 ----> https://www.moteur.ma/fr/neuf/voiture/opel/
 ----> https://www.moteur.ma/fr/neuf/voiture/peugeot/
 ----> https://www.moteur.ma/fr/neuf/voiture/porsche/
 ----> https://www.moteur.ma/fr/neuf/voiture/renault/
 ----> https://www.moteur.ma/fr/neuf/voiture/rox/
 ----> https://www.moteur.ma/fr/neuf/voiture/seat/
 ----> https://www.moteur.ma/fr/neuf/voiture/seres/
 ----> https://www.moteur.ma/fr/neuf/voiture/skoda/
 ----> https://www.moteur.ma/fr/neuf/voiture/smart/
 ----> https://www.moteur.ma/fr/neuf/voiture/soueast/
 ----> https://www.moteur.ma/fr/neuf/voiture/ssangyong/
 ----> https://www.moteur.ma/fr/neuf/voiture/suzuki/
 ----> https://www.moteur.ma/fr/neuf/voiture/tata/
 ----> https://www.moteur.ma/fr/neuf/voiture/tesla/
 ----> https://www.moteur.ma/fr/neuf/voiture/toyota/
 ----> https://www.moteur.ma/fr/neuf/voiture/volkswagen/
 ----> https://www.moteur.ma/fr/neuf/voiture/volvo/
 ----> https://www.moteur.ma/fr/neuf/voiture/xpeng/
 ----> https://www.moteur.ma/fr/neuf/voiture/zeekr/
 ----> https://www.moteur.ma/fr/neuf/voiture/abarth/
 ----> https://www.moteur.ma/fr/neuf/voiture/alfa-romeo/
 ----> https://www.moteur.ma/fr/neuf/voiture/alpine/
 ----> https://www.moteur.ma/fr/neuf/voiture/aston-martin/
 ----> https://www.moteur.ma/fr/neuf/voiture/audi/
 ----> https://www.moteur.ma/fr/neuf/voiture/baic/
 ----> https://www.moteur.ma/fr/neuf/voiture/bentley/
 ----> https://www.moteur.ma/fr/neuf/voiture/bmw/
 ----> https://www.moteur.ma/fr/neuf/voiture/byd/
 ----> https://www.moteur.ma/fr/neuf/voiture/changan/
 ----> https://www.moteur.ma/fr/neuf/voiture/chery/
 ----> https://www.moteur.ma/fr/neuf/voiture/chevrolet/
 ----> https://www.moteur.ma/fr/neuf/voiture/citroen/
 ----> https://www.moteur.ma/fr/neuf/voiture/cupra/
 ----> https://www.moteur.ma/fr/neuf/voiture/dacia/
 ----> https://www.moteur.ma/fr/neuf/voiture/deepal/
 ----> https://www.moteur.ma/fr/neuf/voiture/denza/
 ----> https://www.moteur.ma/fr/neuf/voiture/dfsk/
 ----> https://www.moteur.ma/fr/neuf/voiture/dongfeng/
 ----> https://www.moteur.ma/fr/neuf/voiture/ds/
 ----> https://www.moteur.ma/fr/neuf/voiture/exeed/
 ----> https://www.moteur.ma/fr/neuf/voiture/ferrari/
 ----> https://www.moteur.ma/fr/neuf/voiture/fiat/
 ----> https://www.moteur.ma/fr/neuf/voiture/ford/
 ----> https://www.moteur.ma/fr/neuf/voiture/foton/
 ----> https://www.moteur.ma/fr/neuf/voiture/gac/
 ----> https://www.moteur.ma/fr/neuf/voiture/gaz/
 ----> https://www.moteur.ma/fr/neuf/voiture/geely/
 ----> https://www.moteur.ma/fr/neuf/voiture/gwm/
 ----> https://www.moteur.ma/fr/neuf/voiture/honda/
 ----> https://www.moteur.ma/fr/neuf/voiture/hyundai/
 ----> https://www.moteur.ma/fr/neuf/voiture/isuzu/
 ----> https://www.moteur.ma/fr/neuf/voiture/jac/
 ----> https://www.moteur.ma/fr/neuf/voiture/jaecoo/
 ----> https://www.moteur.ma/fr/neuf/voiture/jaguar/
 ----> https://www.moteur.ma/fr/neuf/voiture/jeep/
 ----> https://www.moteur.ma/fr/neuf/voiture/kia/k-2500/
 ----> https://www.moteur.ma/fr/neuf/voiture/audi/a3-sportback/
 ----> https://www.moteur.ma/fr/neuf/voiture/baic/x55/
 ----> https://www.moteur.ma/fr/neuf/voiture/kia/seltos/
 ----> https://www.moteur.ma/fr/neuf/voiture/citroen/c5-aircross/
 ----> https://www.moteur.ma/fr/neuf/voiture/honda/hr-v/
 ----> https://www.moteur.ma/fr/neuf/voiture/geely/emgrand/
 ----> https://www.moteur.ma/fr/neuf/voiture/kia/k-2500/
 ----> https://www.moteur.ma/fr/neuf/voiture/audi/a3-sportback/
 ----> https://www.moteur.ma/fr/neuf/voiture/baic/x55/
 ----> https://www.moteur.ma/fr/neuf/voiture/kia/seltos/
 ----> https://www.moteur.ma/fr/neuf/voiture/citroen/c5-aircross/
 ----> https://www.moteur.ma/fr/neuf/voiture/honda/hr-v/
 ----> https://www.moteur.ma/fr/neuf/voiture/geely/emgrand/
 ----> https://www.moteur.ma/fr/neuf/voiture/kia/k-2500/
 ----> https://www.moteur.ma/fr/neuf/moto/kymco/
 ----> https://www.moteur.ma/fr/neuf/moto/oba-motors/
 ----> https://www.moteur.ma/fr/neuf/moto/phoenix/
 ----> https://www.moteur.ma/fr/neuf/moto/piaggio/
 ----> https://www.moteur.ma/fr/neuf/moto/qjmotor/

In [12]:
url = "https://www.moteur.ma/fr/voiture/achat-voiture-occasion/"

driver.get(url)

In [13]:
import time
time.sleep(8)

In [14]:
print(driver.title)
print(driver.current_url)

Voiture occasion| Moteur.ma
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/

In [15]:
from selenium.webdriver.common.by import By

liens = driver.find_elements(By.TAG_NAME, "a")

tous_les_liens = []

for lien in liens:
    href = lien.get_attribute("href")
    
    if href and "/occasion/" in href:
        tous_les_liens.append(href)

tous_les_liens = list(set(tous_les_liens))

print("Nombre annonces :", len(tous_les_liens))

for l in tous_les_liens[:10]:
    print(l)

Nombre annonces : 0

In [16]:
driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/")

In [17]:
from selenium.webdriver.common.by import By

liens = driver.find_elements(By.TAG_NAME, "a")

print("Nombre total :", len(liens))

for lien in liens:
    href = lien.get_attribute("href")
    texte = lien.text.strip()

    if href and texte:
        print(texte[:40], "---->", href)

Nombre total : 471
Neuf ----> https://www.moteur.ma/fr/neuf/
Promotion ----> https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/
Émissions ----> https://www.moteur.ma/fr/guide-achat/
Actualités ----> https://www.moteur.ma/fr/guide-achat/actualite/
Occasion ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
Se connecter ----> https://www.moteur.ma/fr/advertisers/login/
Vendez Votre Voiture ----> https://www.moteur.ma/fr/voiture/vendez-voiture-occasion/
Offres du moment ----> https://www.moteur.ma/fr/neuf/rubrique/
DFSK E5 ----> https://www.moteur.ma/fr/neuf/dfsk/e5/promotion/14d406a18f5300fb4a7eaa05837877e2/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=dfsk-e5-mars-decembre-2026&utm_content=btn-header-category
magnite ----> https://www.moteur.ma/fr/neuf/nissan/magnite/promotion/44d9ba17c5ca1561cf9cb915fc8cd42e/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=nissan-magnite-avril-juillet-2026&utm_content=btn-header-category
chery tiggo 7 pro ----> https://www.moteur.ma/fr/neuf/chery/tiggo-7-pro/promotion/7b655ab61843a82e103ffdb2921e6125/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=chery-tiggo-7-pro-juin-juillet-2026&utm_content=btn-header-category
dacia sandero stepway ----> https://www.moteur.ma/fr/neuf/dacia/sandero/promotion/8e6dbd2e0c02e2058f5536744a14675f/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=dacia-sandero-juin-2026&utm_content=btn-header-category
opel astra ----> https://www.moteur.ma/fr/neuf/opel/astra/promotion/73173db04d247583e8f967ecfd5825fa/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-astra-juillet-2026&utm_content=btn-header-category
opel corsa ----> https://www.moteur.ma/fr/neuf/opel/corsa/promotion/da67bee274cc7ae9e437a9d539b0e564/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-corsa-german-days-juillet-2026&utm_content=btn-header-category
opel grandland ----> https://www.moteur.ma/fr/neuf/opel/grandland/promotion/53fb9c0e1f205046d3b2f55dbe1a23b6/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-grandland-german-days-juillet-2026&utm_content=btn-header-category
opel frontera ----> https://www.moteur.ma/fr/neuf/opel/frontera/promotion/6c03c9feb4e3e55df5024be14e7fb4d7/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-frontera-german-days-juillet-2026&utm_content=btn-header-category
opel mokka ----> https://www.moteur.ma/fr/neuf/opel/mokka/promotion/2d01aa90127402b75416803ca7e6a563/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=opel-mokka-german-days-juillet-2026&utm_content=btn-header-category
Seat Leon FR ----> https://www.moteur.ma/fr/neuf/seat/leon/promotion/309774539c62e34b46dd196402551cd6/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=seat-leon-fr-juillet-2026&utm_content=btn-header-category
Seat ibiza ----> https://www.moteur.ma/fr/neuf/seat/ibiza/promotion/e11353238816b345c9caadacdaf714b6/?utm_source=moteur-ma&utm_medium=referral&utm_campaign=seat-ibiza-juillet-2026&utm_content=btn-header-category
Accueil ----> https://www.moteur.ma/
Jeep Renegade ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508936/jeep-renegade.html
Rabat ----> javascript:void(0);
il y a 3 minutes ----> javascript:void(0);
je mets en vente ma voiture jeep très bo ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508936/jeep-renegade.html
Ford Kuga ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508935/ford-kuga.html
Agadir ----> javascript:void(0);
il y a 3 minutes ----> javascript:void(0);
À vendre Ford Kuga de 2015 en très bon é ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508935/ford-kuga.html
Skoda Octavia ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508934/skoda-octavia.html
Agadir ----> javascript:void(0);
il y a 3 minutes ----> javascript:void(0);
Skoda Octavia ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508934/skoda-octavia.html
Hyundai Tucson ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508933/hyundai-tucson.html
Agadir ----> javascript:void(0);
il y a 3 minutes ----> javascript:void(0);
je met en vente ma voiture hyundai tucso ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508933/hyundai-tucson.html
Volkswagen T-Roc ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508932/volkswagen-t-roc.html
Agadir ----> javascript:void(0);
il y a 3 minutes ----> javascript:void(0);
T-roc à vendre 07/2021. ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508932/volkswagen-t-roc.html
Mercedes-Benz 180 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508931/mercedes-benz-180.html
Meknès ----> javascript:void(0);
il y a 3 minutes ----> javascript:void(0);
مرسيدس-بنز 180 ديزل موديل 2010 بحالة ممت ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508931/mercedes-benz-180.html
Fiat 500 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508930/fiat-500.html
Casablanca ----> javascript:void(0);
il y a 3 minutes ----> javascript:void(0);
جيد جدن في كزا ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508930/fiat-500.html
Renault Express ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508929/renault-express.html
Fès ----> javascript:void(0);
il y a 3 minutes ----> javascript:void(0);
À vendre : Renault Express de 2022 en tr ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508929/renault-express.html
Hyundai Tucson ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508928/hyundai-tucson.html
Agadir ----> javascript:void(0);
il y a 3 minutes ----> javascript:void(0);
je met en vente ma voiture hyundai tucso ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508928/hyundai-tucson.html
Dacia Logan ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508927/dacia-logan.html
Casablanca ----> javascript:void(0);
il y a 3 minutes ----> javascript:void(0);
Modèle 2018 promyan mah pantur doriji cl ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508927/dacia-logan.html
Dacia Duster ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508926/dacia-duster.html
Fès ----> javascript:void(0);
il y a 3 minutes ----> javascript:void(0);
موديل 2014 ضاربة 240 الف كم ، اليد تانية ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508926/dacia-duster.html
Peugeot 2008 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508925/peugeot-2008.html
Meknès ----> javascript:void(0);
il y a 3 minutes ----> javascript:void(0);
Peugeot 2008 GT Line modèle 2020/12 dédo ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508925/peugeot-2008.html
Ford Fiesta ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508924/ford-fiesta.html
Agadir ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Ford Fiesta ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508924/ford-fiesta.html
Ford Fiesta ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508923/ford-fiesta.html
Tanger ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Ford fiesta ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508923/ford-fiesta.html
Dacia Lodgy ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508922/dacia-lodgy.html
Agadir ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
vend DSCIA LODGY 7 PLACES modèle 2012 dé ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508922/dacia-lodgy.html
Renault Clio ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508921/renault-clio.html
Agadir ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Renault Clio4 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508921/renault-clio.html
Ford Focus ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508920/ford-focus.html
Rabat ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Ford focus 2008 très bon état ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508920/ford-focus.html
Fiat 500 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508919/fiat-500.html
Agadir ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Fiat 500.. ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508919/fiat-500.html
Volkswagen Caddy ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508918/volkswagen-caddy.html
Agadir ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Volkswagen caddy ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508918/volkswagen-caddy.html
Fiat Punto ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508917/fiat-punto.html
Casablanca ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Je mets en vente une fiat Punto Evo en b ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508917/fiat-punto.html
Ford Kuga ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508916/ford-kuga.html
il y a 14 minutes ----> javascript:void(0);
je mets en vente ma voiture particulière ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508916/ford-kuga.html
Hyundai Santa Fe ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508915/hyundai-santa-fe.html
Rabat ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Hyundai Santa fe l3amra model 2014 très  ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508915/hyundai-santa-fe.html
Volkswagen Golf 7 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508914/volkswagen-golf-7.html
Agadir ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Volkswagen golf 7 modèle.2014 dwana 2019 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508914/volkswagen-golf-7.html
Renault Kangoo ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508913/renault-kangoo.html
Rabat ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Renault Kangoo Diesel Manuelle 2009 Doub ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508913/renault-kangoo.html
Audi Q5 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508912/audi-q5.html
Agadir ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Audi Q5... ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508912/audi-q5.html
Skoda Octavia ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508911/skoda-octavia.html
Agadir ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Skoda Octavia ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508911/skoda-octavia.html
Renault Clio ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508910/renault-clio.html
Casablanca ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
clio 4 diesel 6cv 2015 très bon état jam ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508910/renault-clio.html
Peugeot 208 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508909/peugeot-208.html
Agadir ----> javascript:void(0);
il y a 14 minutes ----> javascript:void(0);
Peugeot 208 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508909/peugeot-208.html
Dacia Dokker ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508908/dacia-dokker.html
Agadir ----> javascript:void(0);
il y a 25 minutes ----> javascript:void(0);
Je vends une Dacia Dokker de 2019 en trè ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508908/dacia-dokker.html
Ford Kuga ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508907/ford-kuga.html
Meknès ----> javascript:void(0);
il y a 25 minutes ----> javascript:void(0);
Je vends une Ford Kuga Diesel Manuelle d ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508907/ford-kuga.html
2 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion?page=2
3 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion?page=3
4 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion?page=4
5 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion?page=5
6 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion?page=6
7 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion?page=7
8 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion?page=8
9 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion?page=9
10 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion?page=10
› ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion?page=2
Réinitialiser ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
Agadir ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?ville=Agadir
Beni Mellal ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?ville=Beni+Mellal
Casablanca ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?ville=Casablanca
Marrakech ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?ville=Marrakech
Nador ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?ville=Nador
Oujda ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?ville=Oujda
Rabat ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?ville=Rabat
Tanger ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?ville=Tanger
Essence ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?carburant=Essence
Diesel ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?carburant=Diesel
Cabriolet ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?carrosserie=Cabriolet
SUV et 4x4 ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?carrosserie=SUV+et+4x4
Coupé ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?carrosserie=Coup%C3%A9
Citadine ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?carrosserie=Citadine
Break ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?carrosserie=Break
Monospace ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?carrosserie=Monospace
Berline ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?carrosserie=Berline
CC ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?carrosserie=CC
Micro-citadine ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?carrosserie=Micro-citadine
Compact ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?carrosserie=Compact
Moins de
50 000 Dhs ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?prix_max=50000
entre
50 000 Dhs
et
100 000 Dhs ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?prix_min=50000&prix_max=100000
entre
100 000 Dhs
et
150 000 Dhs ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?prix_min=100000&prix_max=150000
entre
150 000 Dhs
et
200 000 Dhs ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?prix_min=150000&prix_max=200000
entre
200 000 Dhs
et
250 000 Dhs ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?prix_min=200000&prix_max=250000
entre
250 000 Dhs
et
300 000 Dhs ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?prix_min=250000&prix_max=300000
entre
300 000 Dhs
et
350 000 Dhs ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?prix_min=300000&prix_max=350000
entre
350 000 Dhs
et
400 000 Dhs ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?prix_min=350000&prix_max=400000
entre
400 000 Dhs
et
450 000 Dhs ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?prix_min=400000&prix_max=450000
entre
450 000 Dhs
et
500 000 Dhs ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?prix_min=450000&prix_max=500000
Plus de
500 000 Dhs ----> https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?prix_min=500000
Ford VS Leapmotor ----> https://www.moteur.ma/fr/neuf/comparatif-voiture-neuf/ford-territory-15l-hybride-fhev-titanium-vs-leapmotor-c10-15-reev-215-at-style-4328-4679.html
Audi VS Lynk & Co ----> https://www.moteur.ma/fr/neuf/comparatif-voiture-neuf/audi-q8-mhev-performance-v6-30l-tdi-286-quattro-tiptronic-vs-lynk-co-08-15-t-380-phev-3961-4322.html
Volkswagen VS Renault ----> https://www.moteur.ma/fr/neuf/comparatif-voiture-neuf/volkswagen-t-roc-design-vs-renault-austral-12-e-tech-200-techno-3809-4405.html
Toutes les comparaisons neuves ----> https://www.moteur.ma/fr/neuf/comparatif-voiture-neuf/
Voitures neuves Maroc ----> https://www.moteur.ma/fr/sp/neuf/voiture-neuve-maroc/
Voitures hybrides Maroc ----> https://www.moteur.ma/fr/sp/neuf/voiture-hybride-maroc/
Voitures électriques neuves Maroc ----> https://www.moteur.ma/fr/sp/neuf/voiture-electrique-maroc/
Voitures neuves moins de 200 000 DH ----> https://www.moteur.ma/fr/sp/neuf/voiture-pas-chere-maroc/
SUV neufs Maroc ----> https://www.moteur.ma/fr/sp/neuf/suv-neuf-maroc/
Voitures Diesel neuves ----> https://www.moteur.ma/fr/sp/neuf/voiture-diesel-maroc/
Voitures essence maroc ----> https://www.moteur.ma/fr/sp/neuf/voiture-essence-maroc/
Voitures automatiques Maroc ----> https://www.moteur.ma/fr/sp/neuf/voiture-automatique-maroc/
Voitures familiales neuves ----> https://www.moteur.ma/fr/sp/neuf/voiture-familiale-maroc/
أبارث neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/abarth/
سمارت neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/smart/
ميني neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/mini/
لينك آند كو neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/lynk-co/
ماهيندرا neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/mahindra/
دفسك neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/dfsk/
لكزس neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/lexus/
ألفا روميو neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/alfa-romeo/
نيو-موتورز neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/neo-motors/
بي واي دي neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/byd/
ألبين neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/alpine/
سيريس neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/seres/
بايك neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/baic/
كي جي إم neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/kgm/
سانغ يونغ neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/ssangyong/
دينزا neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/denza/
مرسيدس-بنز neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/mercedes-benz/
سيات neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/seat/
تاتا neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/tata/
فيراري neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/ferrari/
جاغوار neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/jaguar/
فيات neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/fiat/
فورد neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/ford/
مازيراتي neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/maserati/
بيجو neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/peugeot/
بي ام دبليو سيري 3 neuve Maroc ----> https://www.moteur.ma/fr/neuf/voiture/bmw/serie-3/

In [18]:
from selenium.webdriver.common.by import By

tous_les_liens = []

liens = driver.find_elements(By.TAG_NAME, "a")

for lien in liens:
    href = lien.get_attribute("href")
    
    if href and "detail-annonce" in href:
        tous_les_liens.append(href)

# supprimer les doublons
tous_les_liens = list(set(tous_les_liens))

print("Nombre d'annonces :", len(tous_les_liens))

for url in tous_les_liens[:10]:
    print(url)

Nombre d'annonces : 30
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508929/renault-express.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508936/jeep-renegade.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508924/ford-fiesta.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508932/volkswagen-t-roc.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508920/ford-focus.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508916/ford-kuga.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508923/ford-fiesta.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508928/hyundai-tucson.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508912/audi-q5.html
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508911/skoda-octavia.html

In [19]:
url = tous_les_liens[0]

driver.get(url)

import time
time.sleep(3)

print(driver.title)

Renault Express Renault Express 2022 Diesel – 84 000 km 2022 Diesel occasion 508929Fès_phrase Maroc| Moteur.ma

In [20]:
texte = driver.find_element(By.TAG_NAME, "body").text

print(texte[:2000])

Neuf
Promotion
Émissions
Actualités
Occasion
Se connecter
Vendez Votre Voiture
0
العربية
Offres du moment
DFSK E5
magnite
chery tiggo 7 pro
dacia sandero stepway
opel astra
opel corsa
opel grandland
opel frontera
opel mokka
Seat Leon FR
Seat ibiza
Accueil
Occasion
Acheter une voiture d'occasion
Renault Express
Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki

In [21]:
def extraire_annonce(url):
    driver.get(url)
    time.sleep(2)

    texte = driver.find_element(By.TAG_NAME, "body").text

    return texte

In [22]:
annonce = extraire_annonce(tous_les_liens[0])

print(annonce[:1000])

Neuf
Promotion
Émissions
Actualités
Occasion
Se connecter
Vendez Votre Voiture
0
العربية
Offres du moment
DFSK E5
magnite
chery tiggo 7 pro
dacia sandero stepway
opel astra
opel corsa
opel grandland
opel frontera
opel mokka
Seat Leon FR
Seat ibiza
Accueil
Occasion
Acheter une voiture d'occasion
Renault Express
Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BY

In [23]:
from selenium.webdriver.common.by import By

# récupérer tout le texte
texte = driver.find_element(By.TAG_NAME, "body").text

# chercher les lignes importantes
lignes = texte.split("\n")

for ligne in lignes:
    if ("Année" in ligne or 
        "Kilométrage" in ligne or 
        "Carburant" in ligne or 
        "Transmission" in ligne or
        "Prix" in ligne):
        print(ligne)

Année: 2022 Kilométrage: 84,000 km
Carburant: Diesel Transmission: Manuelle
Prix Renault Express neuve maroc
Prix promotionnels du moment
Prix sur demande
Prix sur demande

In [24]:
titre = driver.find_element(By.TAG_NAME, "h1").text

print(titre)

Renault Express

In [25]:
from selenium.webdriver.common.by import By
import time
import re

def extraire_annonce(url):
    driver.get(url)
    time.sleep(2)

    data = {}

    # Titre (marque + modèle)
    try:
        titre = driver.find_element(By.TAG_NAME, "h1").text
        data["Titre"] = titre
    except:
        data["Titre"] = "N/A"


    # Texte complet
    texte = driver.find_element(By.TAG_NAME, "body").text


    # Année
    match = re.search(r"Année:\s*(\d{4})", texte)
    data["Annee"] = match.group(1) if match else "N/A"


    # Kilométrage
    match = re.search(r"Kilométrage:\s*([\d,\s]+)", texte)
    data["Kilometrage"] = match.group(1).strip() if match else "N/A"


    # Carburant
    match = re.search(r"Carburant:\s*(\w+)", texte)
    data["Carburant"] = match.group(1) if match else "N/A"


    # Transmission
    match = re.search(r"Transmission:\s*(\w+)", texte)
    data["Transmission"] = match.group(1) if match else "N/A"


    return data

In [26]:
annonce = extraire_annonce(tous_les_liens[0])

print(annonce)

{'Titre': 'Renault Express', 'Annee': '2022', 'Kilometrage': '84,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}

In [27]:
dataset = []

for url in tous_les_liens:
    try:
        annonce = extraire_annonce(url)
        dataset.append(annonce)
        print(annonce)
    except Exception as e:
        print("Erreur :", e)

print("Nombre total :", len(dataset))

{'Titre': 'Renault Express', 'Annee': '2022', 'Kilometrage': '84,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Jeep Renegade', 'Annee': '2018', 'Kilometrage': '141,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
{'Titre': 'Ford Fiesta', 'Annee': '2017', 'Kilometrage': '140,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Volkswagen T-Roc', 'Annee': '2021', 'Kilometrage': '159,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
{'Titre': 'Ford Focus', 'Annee': '2008', 'Kilometrage': '260,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Ford Kuga', 'Annee': '2019', 'Kilometrage': '161', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Ford Fiesta', 'Annee': '2019', 'Kilometrage': '117,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Hyundai Tucson', 'Annee': '2022', 'Kilometrage': '146,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Audi Q5', 'Annee': '2020', 'Kilometrage': '135,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
{'Titre': 'Skoda Octavia', 'Annee': '2019', 'Kilometrage': '200,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Ford Kuga', 'Annee': '2015', 'Kilometrage': '218,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Hyundai Tucson', 'Annee': '2022', 'Kilometrage': '146,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Peugeot 208', 'Annee': '2022', 'Kilometrage': '130,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Volkswagen Caddy', 'Annee': '2011', 'Kilometrage': '200,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Dacia Logan', 'Annee': '2018', 'Kilometrage': '120,000', 'Carburant': 'Essence', 'Transmission': 'Manuelle'}
{'Titre': 'Mercedes-Benz 180', 'Annee': '2010', 'Kilometrage': '293,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Volkswagen Golf 7', 'Annee': '2014', 'Kilometrage': '174,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
{'Titre': 'Dacia Duster', 'Annee': '2014', 'Kilometrage': '240,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Peugeot 2008', 'Annee': '2020', 'Kilometrage': '184', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
{'Titre': 'Fiat Punto', 'Annee': '2016', 'Kilometrage': '200,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Fiat 500', 'Annee': '2020', 'Kilometrage': '90', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Renault Clio', 'Annee': '2019', 'Kilometrage': '150,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Hyundai Santa Fe', 'Annee': '2014', 'Kilometrage': '256,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Dacia Dokker', 'Annee': '2019', 'Kilometrage': '160,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Renault Kangoo', 'Annee': '2009', 'Kilometrage': '300,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Skoda Octavia', 'Annee': '2022', 'Kilometrage': '130,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
{'Titre': 'Renault Clio', 'Annee': '2015', 'Kilometrage': '148', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Fiat 500', 'Annee': '2016', 'Kilometrage': '115,000', 'Carburant': 'Essence', 'Transmission': 'Automatique'}
{'Titre': 'Ford Kuga', 'Annee': '2022', 'Kilometrage': '90', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
{'Titre': 'Dacia Lodgy', 'Annee': '2012', 'Kilometrage': '290,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
Nombre total : 30

In [28]:
import pandas as pd

df = pd.DataFrame(dataset)

df

                Titre Annee Kilometrage Carburant Transmission
0     Renault Express  2022      84,000    Diesel     Manuelle
1       Jeep Renegade  2018     141,000    Diesel  Automatique
2         Ford Fiesta  2017     140,000    Diesel     Manuelle
3    Volkswagen T-Roc  2021     159,000    Diesel  Automatique
4          Ford Focus  2008     260,000    Diesel     Manuelle
5           Ford Kuga  2019         161    Diesel     Manuelle
6         Ford Fiesta  2019     117,000    Diesel     Manuelle
7      Hyundai Tucson  2022     146,000    Diesel     Manuelle
8             Audi Q5  2020     135,000    Diesel  Automatique
9       Skoda Octavia  2019     200,000    Diesel     Manuelle
10          Ford Kuga  2015     218,000    Diesel     Manuelle
11     Hyundai Tucson  2022     146,000    Diesel     Manuelle
12        Peugeot 208  2022     130,000    Diesel     Manuelle
13   Volkswagen Caddy  2011     200,000    Diesel     Manuelle
14        Dacia Logan  2018     120,000   Essence     Manuelle
15  Mercedes-Benz 180  2010     293,000    Diesel     Manuelle
16  Volkswagen Golf 7  2014     174,000    Diesel  Automatique
17       Dacia Duster  2014     240,000    Diesel     Manuelle
18       Peugeot 2008  2020         184    Diesel  Automatique
19         Fiat Punto  2016     200,000    Diesel     Manuelle
20           Fiat 500  2020          90    Diesel     Manuelle
21       Renault Clio  2019     150,000    Diesel     Manuelle
22   Hyundai Santa Fe  2014     256,000    Diesel     Manuelle
23       Dacia Dokker  2019     160,000    Diesel     Manuelle
24     Renault Kangoo  2009     300,000    Diesel     Manuelle
25      Skoda Octavia  2022     130,000    Diesel  Automatique
26       Renault Clio  2015         148    Diesel     Manuelle
27           Fiat 500  2016     115,000   Essence  Automatique
28          Ford Kuga  2022          90    Diesel     Manuelle
29        Dacia Lodgy  2012     290,000    Diesel     Manuelle

In [29]:
marques = [
    "Renault",
    "Jeep",
    "Ford",
    "Volkswagen",
    "Hyundai",
    "Audi",
    "Skoda",
    "Peugeot",
    "Dacia",
    "Mercedes-Benz",
    "Fiat"
]

def separer_marque(titre):
    for marque in marques:
        if titre.startswith(marque):
            return marque, titre.replace(marque,"").strip()
    return "N/A", titre


df[['Marque','Modele']] = df['Titre'].apply(
    lambda x: pd.Series(separer_marque(x))
)

df.head()

,Titre,Annee,Kilometrage,Carburant,Transmission,Marque,Modele
0,Renault Express,2022,"84,000",Diesel,Manuelle,Renault,Express
1,Jeep Renegade,2018,"141,000",Diesel,Automatique,Jeep,Renegade
2,Ford Fiesta,2017,"140,000",Diesel,Manuelle,Ford,Fiesta
3,Volkswagen T-Roc,2021,"159,000",Diesel,Automatique,Volkswagen,T-Roc
4,Ford Focus,2008,"260,000",Diesel,Manuelle,Ford,Focus

In [30]:
df["Kilometrage"] = (
    df["Kilometrage"]
    .str.replace(",","")
    .astype(int)
)

df["Kilometrage"] = df["Kilometrage"].apply(
    lambda x: x*1000 if x < 1000 else x
)

In [31]:
df.to_csv(
    "voitures_moteur_ma.csv",
    index=False,
    encoding="utf-8"
)

In [32]:
def recuperer_liens_page(numero_page):
    
    url = f"https://www.moteur.ma/fr/voiture/achat-voiture-occasion?page={numero_page}"
    
    driver.get(url)
    time.sleep(3)

    liens = driver.find_elements(By.TAG_NAME, "a")

    annonces = []

    for lien in liens:
        href = lien.get_attribute("href")

        if href and "detail-annonce" in href:
            annonces.append(href)

    return list(set(annonces))

In [33]:
liens_page2 = recuperer_liens_page(2)

print(len(liens_page2))

30

In [34]:
tous_les_liens = []

for page in range(1, 11):   # pages 1 à 10
    
    print("Récupération page :", page)
    
    liens = recuperer_liens_page(page)
    
    tous_les_liens.extend(liens)
    
    print("Nombre trouvé :", len(liens))
    print("Total actuel :", len(tous_les_liens))

Récupération page : 1
Nombre trouvé : 30
Total actuel : 30
Récupération page : 2
Nombre trouvé : 30
Total actuel : 60
Récupération page : 3
Nombre trouvé : 30
Total actuel : 90
Récupération page : 4
Nombre trouvé : 30
Total actuel : 120
Récupération page : 5
Nombre trouvé : 30
Total actuel : 150
Récupération page : 6
Nombre trouvé : 30
Total actuel : 180
Récupération page : 7
Nombre trouvé : 30
Total actuel : 210
Récupération page : 8
Nombre trouvé : 30
Total actuel : 240
Récupération page : 9
Nombre trouvé : 30
Total actuel : 270
Récupération page : 10
Nombre trouvé : 30
Total actuel : 300

In [35]:
tous_les_liens = list(set(tous_les_liens))

print("Nombre total d'annonces :", len(tous_les_liens))

Nombre total d'annonces : 300

In [36]:
dataset = []

for i, url in enumerate(tous_les_liens):
    
    try:
        annonce = extraire_annonce(url)
        dataset.append(annonce)
        
        print(i+1, "/", len(tous_les_liens), annonce)
        
    except Exception as e:
        print("Erreur annonce", i, e)

1 / 300 {'Titre': 'Peugeot 3008', 'Annee': '2020', 'Kilometrage': '65,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
2 / 300 {'Titre': 'Dacia Logan', 'Annee': '2022', 'Kilometrage': '31,500', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
3 / 300 {'Titre': 'Citroën C3', 'Annee': '2018', 'Kilometrage': '126,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
4 / 300 {'Titre': 'Volvo XC40', 'Annee': '2024', 'Kilometrage': '24,000', 'Carburant': 'Essence', 'Transmission': 'Automatique'}
5 / 300 {'Titre': 'Dacia Sandero', 'Annee': '2021', 'Kilometrage': '26,000', 'Carburant': 'Essence', 'Transmission': 'Manuelle'}
6 / 300 {'Titre': 'Fiat Freemont', 'Annee': '2016', 'Kilometrage': '236,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
7 / 300 {'Titre': 'Hyundai Tucson', 'Annee': '2023', 'Kilometrage': '115,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
8 / 300 {'Titre': 'Citroën C3', 'Annee': '2018', 'Kilometrage': '180,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
9 / 300 {'Titre': 'Skoda Scala', 'Annee': '2023', 'Kilometrage': '26,000', 'Carburant': 'Essence', 'Transmission': 'Automatique'}
10 / 300 {'Titre': 'Skoda Rapid', 'Annee': '2013', 'Kilometrage': '210,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
11 / 300 {'Titre': 'Volkswagen Golf 5', 'Annee': '2008', 'Kilometrage': '0', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
12 / 300 {'Titre': 'Mercedes-Benz Classe GLE', 'Annee': '2021', 'Kilometrage': '85,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
13 / 300 {'Titre': 'Toyota Yaris', 'Annee': '2023', 'Kilometrage': '58,630', 'Carburant': 'Hybride', 'Transmission': 'Automatique'}
14 / 300 {'Titre': 'BMW Z4', 'Annee': '2012', 'Kilometrage': '140,000', 'Carburant': 'Essence', 'Transmission': 'Automatique'}
15 / 300 {'Titre': 'Toyota Corolla', 'Annee': '2007', 'Kilometrage': '280,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
16 / 300 {'Titre': 'Renault R19', 'Annee': '1994', 'Kilometrage': '0', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
17 / 300 {'Titre': 'Volvo V40', 'Annee': '2013', 'Kilometrage': '190,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
18 / 300 {'Titre': 'Renault Clio', 'Annee': '2004', 'Kilometrage': '300,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
19 / 300 {'Titre': 'Citroën Berlingo', 'Annee': '2021', 'Kilometrage': '81,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
20 / 300 {'Titre': 'Peugeot 208', 'Annee': '2022', 'Kilometrage': '74,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
21 / 300 {'Titre': 'Peugeot 206', 'Annee': '2013', 'Kilometrage': '880', 'Carburant': 'Essence', 'Transmission': 'Manuelle'}
22 / 300 {'Titre': 'Renault Megane', 'Annee': '2002', 'Kilometrage': '160,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
23 / 300 {'Titre': 'Renault Kangoo', 'Annee': '2013', 'Kilometrage': '200', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
24 / 300 {'Titre': 'Ford Fiesta', 'Annee': '2019', 'Kilometrage': '117,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
25 / 300 {'Titre': 'Opel Grandland', 'Annee': '2021', 'Kilometrage': '124,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
26 / 300 {'Titre': 'Ford B Max', 'Annee': '2014', 'Kilometrage': '225,000', 'Carburant': 'Essence', 'Transmission': 'Manuelle'}
27 / 300 {'Titre': 'Suzuki Celerio', 'Annee': '2011', 'Kilometrage': '138,000', 'Carburant': 'Essence', 'Transmission': 'Manuelle'}
28 / 300 {'Titre': 'Renault Clio', 'Annee': '2021', 'Kilometrage': '91', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
29 / 300 {'Titre': 'Mercedes-Benz 190', 'Annee': '1990', 'Kilometrage': '600', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
30 / 300 {'Titre': 'Renault Scenic', 'Annee': '2008', 'Kilometrage': '270,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
31 / 300 {'Titre': 'Dacia Duster', 'Annee': '2018', 'Kilometrage': '120,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
32 / 300 {'Titre': 'Volkswagen Golf 6', 'Annee': '2011', 'Kilometrage': '240,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
33 / 300 {'Titre': 'Mazda 3', 'Annee': '2011', 'Kilometrage': '200,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
34 / 300 {'Titre': 'Dacia Sandero', 'Annee': '2018', 'Kilometrage': '150,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
35 / 300 {'Titre': 'Renault Kangoo', 'Annee': '2007', 'Kilometrage': '153,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
36 / 300 {'Titre': 'Ford Kuga', 'Annee': '2015', 'Kilometrage': '218,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
37 / 300 {'Titre': 'Peugeot 3008', 'Annee': '2020', 'Kilometrage': '65,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
38 / 300 {'Titre': 'Ford Focus', 'Annee': '2017', 'Kilometrage': '218,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
39 / 300 {'Titre': 'Renault Express', 'Annee': '2024', 'Kilometrage': '24,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
40 / 300 {'Titre': 'Skoda Karoq', 'Annee': '2023', 'Kilometrage': '65,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
41 / 300 {'Titre': 'Hyundai Tucson', 'Annee': '2022', 'Kilometrage': '146,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
42 / 300 {'Titre': 'Mercedes-Benz Classe CLA', 'Annee': '2021', 'Kilometrage': '100,000', 'Carburant': 'Diesel', 'Transmission': 'Automatique'}
43 / 300 {'Titre': 'Toyota Corolla', 'Annee': '2011', 'Kilometrage': '200,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
44 / 300 {'Titre': 'Peugeot 307', 'Annee': '2005', 'Kilometrage': '285,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
45 / 300 {'Titre': 'Volkswagen Caddy', 'Annee': '2011', 'Kilometrage': '200,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
46 / 300 {'Titre': 'Ford Fiesta', 'Annee': '2017', 'Kilometrage': '110', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}
Erreur annonce 46 Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: unable to send message to renderer
  (Session info: chrome=150.0.7871.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f319594d]
	chromedriver!(No symbol) [0x7ff6f3181750]
	chromedriver!(No symbol) [0x7ff6f31816ac]
	chromedriver!(No symbol) [0x7ff6f317feef]
	chromedriver!(No symbol) [0x7ff6f3180abf]
	chromedriver!(No symbol) [0x7ff6f3190a09]
	chromedriver!(No symbol) [0x7ff6f31a6ab7]
	chromedriver!(No symbol) [0x7ff6f31ae98a]
	chromedriver!(No symbol) [0x7ff6f3181281]
	chromedriver!(No symbol) [0x7ff6f31a619d]
	chromedriver!(No symbol) [0x7ff6f323e343]
	chromedriver!(No symbol) [0x7ff6f31e2e6c]
	chromedriver!(No symbol) [0x7ff6f31e3d93]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!GetHandleVerifier [0x7ff6f364ab74+1f3f4]
	chromedriver!GetHandleVerifier [0x7ff6f364ad04+1f584]
	chromedriver!GetHandleVerifier [0x7ff6f362d9d7+2257]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Erreur annonce 47 Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Erreur annonce 48 Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Erreur annonce 49 Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Erreur annonce 50 Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Erreur annonce 51 Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Erreur annonce 52 Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Erreur annonce 53 Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Erreur annonce 54 Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Erreur annonce 55 Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Erreur annonce 56 Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Erreur annonce 57 Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]


In [37]:
df = pd.DataFrame(dataset)

df.head()

           Titre Annee Kilometrage Carburant Transmission
0   Peugeot 3008  2020      65,000    Diesel  Automatique
1    Dacia Logan  2022      31,500    Diesel     Manuelle
2     Citroën C3  2018     126,000    Diesel     Manuelle
3     Volvo XC40  2024      24,000   Essence  Automatique
4  Dacia Sandero  2021      26,000   Essence     Manuelle

In [38]:
prix_elements = driver.find_elements(By.CLASS_NAME, "price-value")

for p in prix_elements:
    print("PRIX :", p.text)

InvalidSessionIdException: Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

In [39]:
from selenium import webdriver

driver = webdriver.Chrome()

print("Driver OK")

Driver OK

In [40]:
url = tous_les_liens[0]

driver.get(url)

In [41]:
import time
time.sleep(3)

In [42]:
prix_elements = driver.find_elements(By.CLASS_NAME, "price-value")

for p in prix_elements:
    print("PRIX :", p.text)

PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX : 173 900 Dhs
PRIX : Prix sur demande
PRIX : Prix sur demande
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :
PRIX :

In [43]:
print(len(tous_les_liens))

300

In [44]:
print(driver.title)

Peugeot 3008 peugeot 3008 2020 Diesel occasion 508866Tanger_phrase Maroc| Moteur.ma

In [45]:
prix_elements = driver.find_elements(By.CLASS_NAME, "price-value")

prix = []

for p in prix_elements:
    texte = p.text.strip()
    
    if "Dhs" in texte:
        prix.append(texte)

print(prix)

['173 900 Dhs']

In [46]:
annonce = {
    "Titre": "Jeep Renegade",
    "Annee": "2018",
    "Kilometrage": "141000",
    "Carburant": "Diesel",
    "Transmission": "Automatique",
    "Prix": prix[0]
}

print(annonce)

{'Titre': 'Jeep Renegade', 'Annee': '2018', 'Kilometrage': '141000', 'Carburant': 'Diesel', 'Transmission': 'Automatique', 'Prix': '173 900 Dhs'}

In [47]:
annonces = []

for lien in liens:
    driver.get(lien)
    
    # extraction des informations

In [48]:
# Récupération du prix
prix_elements = driver.find_elements(By.CLASS_NAME, "price-value")

prix = ""

for p in prix_elements:
    texte = p.text.strip()
    if "Dhs" in texte:
        prix = texte
        break

In [49]:
annonce = {
    "Titre": titre,
    "Annee": annee,
    "Kilometrage": kilometrage,
    "Carburant": carburant,
    "Transmission": transmission
}

NameError: name 'annee' is not defined

In [ ]:
annonce = {
    "Titre": titre,
    "Prix": prix,
    "Annee": annee,
    "Kilometrage": kilometrage,
    "Carburant": carburant,
    "Transmission": transmission
}

In [50]:
from selenium.webdriver.common.by import By
import time

tous_les_liens = []

for page in range(1, 11):
    url = f"https://www.moteur.ma/fr/voiture/achat-voiture-occasion?page={page}"
    
    driver.get(url)
    time.sleep(3)

    liens = driver.find_elements(By.TAG_NAME, "a")

    for lien in liens:
        href = lien.get_attribute("href")
        
        if href and "/detail-annonce/" in href:
            if href not in tous_les_liens:
                tous_les_liens.append(href)

    print("Page", page, "=>", len(tous_les_liens), "liens")

Page 1 => 30 liens
Page 2 => 60 liens
Page 3 => 90 liens
Page 4 => 120 liens
Page 5 => 150 liens
Page 6 => 180 liens
Page 7 => 210 liens
Page 8 => 240 liens
Page 9 => 259 liens
Page 10 => 289 liens

In [51]:
import pandas as pd
import time
from selenium.webdriver.common.by import By

donnees = []

for i, lien in enumerate(tous_les_liens):

    print("Annonce", i+1, "/", len(tous_les_liens))

    try:
        driver.get(lien)
        time.sleep(2)

        # Titre
        try:
            titre = driver.find_element(By.CLASS_NAME, "breadcrumb-item1").text
        except:
            titre = ""

        # Prix
        prix = ""
        prix_elements = driver.find_elements(By.CLASS_NAME, "price-value")

        for p in prix_elements:
            texte = p.text.strip()
            if "Dhs" in texte:
                prix = texte
                break

        # Informations générales
        texte_page = driver.find_element(By.TAG_NAME, "body").text

        # Année
        annee = ""
        if "Année:" in texte_page:
            annee = texte_page.split("Année:")[1].split("\n")[0].strip()

        # Kilométrage
        kilometrage = ""
        if "Kilométrage:" in texte_page:
            kilometrage = texte_page.split("Kilométrage:")[1].split("\n")[0].strip()

        # Carburant
        carburant = ""
        if "Diesel" in texte_page:
            carburant = "Diesel"
        elif "Essence" in texte_page:
            carburant = "Essence"

        # Transmission
        transmission = ""
        if "Automatique" in texte_page:
            transmission = "Automatique"
        elif "Manuelle" in texte_page:
            transmission = "Manuelle"


        annonce = {
            "Titre": titre,
            "Prix": prix,
            "Annee": annee,
            "Kilometrage": kilometrage,
            "Carburant": carburant,
            "Transmission": transmission
        }

        donnees.append(annonce)

    except Exception as e:
        print("Erreur :", e)


print("Terminé :", len(donnees))

Annonce 1 / 289
Annonce 2 / 289
Annonce 3 / 289
Annonce 4 / 289
Annonce 5 / 289
Annonce 6 / 289
Annonce 7 / 289
Annonce 8 / 289
Annonce 9 / 289
Annonce 10 / 289
Annonce 11 / 289
Annonce 12 / 289
Annonce 13 / 289
Annonce 14 / 289
Annonce 15 / 289
Annonce 16 / 289
Annonce 17 / 289
Annonce 18 / 289
Annonce 19 / 289
Annonce 20 / 289
Annonce 21 / 289
Annonce 22 / 289
Annonce 23 / 289
Annonce 24 / 289
Annonce 25 / 289
Annonce 26 / 289
Annonce 27 / 289
Annonce 28 / 289
Annonce 29 / 289
Annonce 30 / 289
Annonce 31 / 289
Annonce 32 / 289
Annonce 33 / 289
Annonce 34 / 289
Annonce 35 / 289
Annonce 36 / 289
Annonce 37 / 289
Annonce 38 / 289
Annonce 39 / 289
Annonce 40 / 289
Annonce 41 / 289
Annonce 42 / 289
Annonce 43 / 289
Erreur : Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: Unable to receive message from renderer
  (Session info: chrome=150.0.7871.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b9594d]
	chromedriver!(No symbol) [0x7ff787b827c9]
	chromedriver!(No symbol) [0x7ff787b824b1]
	chromedriver!(No symbol) [0x7ff787b80167]
	chromedriver!(No symbol) [0x7ff787b80abf]
	chromedriver!(No symbol) [0x7ff787b906e4]
	chromedriver!(No symbol) [0x7ff787ba6ab7]
	chromedriver!(No symbol) [0x7ff787bae98a]
	chromedriver!(No symbol) [0x7ff787b81281]
	chromedriver!(No symbol) [0x7ff787ba619d]
	chromedriver!(No symbol) [0x7ff787c3e343]
	chromedriver!(No symbol) [0x7ff787be2e6c]
	chromedriver!(No symbol) [0x7ff787be3d93]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!GetHandleVerifier [0x7ff78804ab74+1f3f4]
	chromedriver!GetHandleVerifier [0x7ff78804ad04+1f584]
	chromedriver!GetHandleVerifier [0x7ff78802d9d7+2257]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 44 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 45 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 46 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 47 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 48 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 49 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 50 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 51 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 52 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 53 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 54 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 55 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 56 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 57 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 58 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

Annonce 59 / 289
Erreur : Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]

In [52]:
print(driver.title)

InvalidSessionIdException: Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

In [53]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

In [54]:
donnees = []

In [55]:
time.sleep(5)

In [56]:
print(driver.title)

In [58]:
driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/")

In [59]:
donnees = []
erreurs = []

In [60]:
import time
from selenium.webdriver.common.by import By

for i, lien in enumerate(tous_les_liens):

    print("Annonce", i+1, "/", len(tous_les_liens))

    try:
        driver.get(lien)
        time.sleep(5)

        # Titre
        try:
            titre = driver.find_element(By.CLASS_NAME, "breadcrumb-item1").text
        except:
            titre = ""

        # Prix
        prix = ""
        prix_elements = driver.find_elements(By.CLASS_NAME, "price-value")

        for p in prix_elements:
            texte = p.text.strip()
            if "Dhs" in texte:
                prix = texte
                break

        # Texte complet de la page
        texte_page = driver.find_element(By.TAG_NAME, "body").text

        # Année
        annee = ""
        if "Année:" in texte_page:
            annee = texte_page.split("Année:")[1].split("\n")[0].strip()

        # Kilométrage
        kilometrage = ""
        if "Kilométrage:" in texte_page:
            kilometrage = texte_page.split("Kilométrage:")[1].split("\n")[0].strip()

        # Carburant
        carburant = ""
        if "Diesel" in texte_page:
            carburant = "Diesel"
        elif "Essence" in texte_page:
            carburant = "Essence"

        # Transmission
        transmission = ""
        if "Automatique" in texte_page:
            transmission = "Automatique"
        elif "Manuelle" in texte_page:
            transmission = "Manuelle"

        donnees.append({
            "Titre": titre,
            "Prix": prix,
            "Annee": annee,
            "Kilometrage": kilometrage,
            "Carburant": carburant,
            "Transmission": transmission
        })

    except Exception as e:
        erreurs.append(lien)
        print("Erreur annonce", i+1)

print("Terminé :", len(donnees))
print("Erreurs :", len(erreurs))

Annonce 1 / 289
Annonce 2 / 289
Annonce 3 / 289
Annonce 4 / 289
Annonce 5 / 289
Annonce 6 / 289
Annonce 7 / 289
Annonce 8 / 289
Annonce 9 / 289
Annonce 10 / 289
Annonce 11 / 289
Annonce 12 / 289
Annonce 13 / 289
Annonce 14 / 289
Annonce 15 / 289
Annonce 16 / 289
Annonce 17 / 289
Annonce 18 / 289
Annonce 19 / 289
Annonce 20 / 289
Annonce 21 / 289
Annonce 22 / 289
Annonce 23 / 289
Annonce 24 / 289
Annonce 25 / 289
Annonce 26 / 289
Annonce 27 / 289
Annonce 28 / 289
Annonce 29 / 289
Annonce 30 / 289
Annonce 31 / 289
Annonce 32 / 289
Annonce 33 / 289
Annonce 34 / 289
Annonce 35 / 289
Annonce 36 / 289
Annonce 37 / 289
Annonce 38 / 289
Annonce 39 / 289
Annonce 40 / 289
Annonce 41 / 289
Annonce 42 / 289
Annonce 43 / 289
Annonce 44 / 289
Annonce 45 / 289
Annonce 46 / 289
Annonce 47 / 289
Annonce 48 / 289
Annonce 49 / 289
Annonce 50 / 289
Annonce 51 / 289
Annonce 52 / 289
Annonce 53 / 289
Annonce 54 / 289
Annonce 55 / 289
Annonce 56 / 289
Annonce 57 / 289
Annonce 58 / 289
Annonce 59 / 289
Annonce 60 / 289
Annonce 61 / 289
Annonce 62 / 289
Annonce 63 / 289
Annonce 64 / 289
Annonce 65 / 289
Annonce 66 / 289
Annonce 67 / 289
Annonce 68 / 289
Annonce 69 / 289
Annonce 70 / 289
Annonce 71 / 289
Annonce 72 / 289
Annonce 73 / 289
Annonce 74 / 289
Annonce 75 / 289
Annonce 76 / 289
Annonce 77 / 289
Annonce 78 / 289
Annonce 79 / 289
Annonce 80 / 289
Annonce 81 / 289
Annonce 82 / 289
Annonce 83 / 289
Annonce 84 / 289
Annonce 85 / 289
Annonce 86 / 289
Annonce 87 / 289
Annonce 88 / 289
Annonce 89 / 289
Annonce 90 / 289
Annonce 91 / 289
Annonce 92 / 289
Annonce 93 / 289
Annonce 94 / 289
Annonce 95 / 289
Annonce 96 / 289
Annonce 97 / 289
Annonce 98 / 289
Annonce 99 / 289
Annonce 100 / 289
Annonce 101 / 289
Annonce 102 / 289
Annonce 103 / 289
Annonce 104 / 289
Annonce 105 / 289
Annonce 106 / 289
Annonce 107 / 289
Annonce 108 / 289
Annonce 109 / 289
Annonce 110 / 289
Annonce 111 / 289
Annonce 112 / 289
Annonce 113 / 289
Annonce 114 / 289
Annonce 115 / 289
Annonce 116 / 289
Annonce 117 / 289
Annonce 118 / 289
Annonce 119 / 289
Annonce 120 / 289
Annonce 121 / 289
Annonce 122 / 289
Annonce 123 / 289
Annonce 124 / 289
Annonce 125 / 289
Annonce 126 / 289
Annonce 127 / 289
Annonce 128 / 289
Annonce 129 / 289
Annonce 130 / 289
Annonce 131 / 289
Annonce 132 / 289
Annonce 133 / 289
Annonce 134 / 289
Annonce 135 / 289
Annonce 136 / 289
Annonce 137 / 289
Annonce 138 / 289
Annonce 139 / 289
Annonce 140 / 289
Annonce 141 / 289
Annonce 142 / 289
Annonce 143 / 289
Annonce 144 / 289
Annonce 145 / 289
Annonce 146 / 289
Annonce 147 / 289
Annonce 148 / 289
Annonce 149 / 289
Annonce 150 / 289
Annonce 151 / 289
Annonce 152 / 289
Annonce 153 / 289
Annonce 154 / 289
Annonce 155 / 289
Annonce 156 / 289
Annonce 157 / 289
Annonce 158 / 289
Annonce 159 / 289
Annonce 160 / 289
Annonce 161 / 289
Annonce 162 / 289
Annonce 163 / 289
Annonce 164 / 289
Annonce 165 / 289
Annonce 166 / 289
Annonce 167 / 289
Annonce 168 / 289
Annonce 169 / 289
Annonce 170 / 289
Annonce 171 / 289
Annonce 172 / 289
Annonce 173 / 289
Annonce 174 / 289
Annonce 175 / 289
Annonce 176 / 289
Annonce 177 / 289
Annonce 178 / 289
Annonce 179 / 289
Annonce 180 / 289
Annonce 181 / 289
Annonce 182 / 289
Annonce 183 / 289
Annonce 184 / 289
Annonce 185 / 289
Annonce 186 / 289
Annonce 187 / 289
Annonce 188 / 289
Annonce 189 / 289
Annonce 190 / 289
Annonce 191 / 289
Annonce 192 / 289
Annonce 193 / 289
Annonce 194 / 289
Annonce 195 / 289
Annonce 196 / 289
Annonce 197 / 289
Annonce 198 / 289
Annonce 199 / 289
Annonce 200 / 289
Annonce 201 / 289
Annonce 202 / 289
Annonce 203 / 289
Annonce 204 / 289
Annonce 205 / 289
Annonce 206 / 289
Annonce 207 / 289
Annonce 208 / 289
Annonce 209 / 289
Annonce 210 / 289
Annonce 211 / 289
Annonce 212 / 289
Annonce 213 / 289
Annonce 214 / 289
Annonce 215 / 289
Annonce 216 / 289
Annonce 217 / 289
Annonce 218 / 289
Annonce 219 / 289
Annonce 220 / 289
Annonce 221 / 289
Annonce 222 / 289
Annonce 223 / 289
Annonce 224 / 289
Annonce 225 / 289
Annonce 226 / 289
Annonce 227 / 289
Annonce 228 / 289
Annonce 229 / 289
Annonce 230 / 289
Annonce 231 / 289
Annonce 232 / 289
Annonce 233 / 289
Erreur annonce 233
Annonce 234 / 289
Erreur annonce 234
Annonce 235 / 289
Erreur annonce 235
Annonce 236 / 289
Erreur annonce 236
Annonce 237 / 289
Erreur annonce 237
Annonce 238 / 289
Erreur annonce 238
Annonce 239 / 289
Erreur annonce 239
Annonce 240 / 289
Erreur annonce 240
Annonce 241 / 289
Erreur annonce 241
Annonce 242 / 289
Erreur annonce 242
Annonce 243 / 289
Erreur annonce 243
Annonce 244 / 289
Erreur annonce 244
Annonce 245 / 289
Erreur annonce 245
Annonce 246 / 289
Erreur annonce 246
Annonce 247 / 289
Erreur annonce 247
Annonce 248 / 289
Erreur annonce 248
Annonce 249 / 289
Erreur annonce 249
Annonce 250 / 289
Erreur annonce 250
Annonce 251 / 289
Erreur annonce 251
Annonce 252 / 289
Erreur annonce 252
Annonce 253 / 289
Erreur annonce 253
Annonce 254 / 289
Erreur annonce 254
Annonce 255 / 289
Erreur annonce 255
Annonce 256 / 289
Erreur annonce 256
Annonce 257 / 289
Erreur annonce 257
Annonce 258 / 289
Erreur annonce 258
Annonce 259 / 289
Erreur annonce 259
Annonce 260 / 289
Erreur annonce 260
Annonce 261 / 289
Erreur annonce 261
Annonce 262 / 289
Erreur annonce 262
Annonce 263 / 289
Erreur annonce 263
Annonce 264 / 289
Erreur annonce 264
Annonce 265 / 289
Erreur annonce 265
Annonce 266 / 289
Erreur annonce 266
Annonce 267 / 289
Erreur annonce 267
Annonce 268 / 289
Erreur annonce 268
Annonce 269 / 289
Erreur annonce 269
Annonce 270 / 289
Erreur annonce 270
Annonce 271 / 289
Erreur annonce 271
Annonce 272 / 289
Erreur annonce 272
Annonce 273 / 289
Erreur annonce 273
Annonce 274 / 289
Erreur annonce 274
Annonce 275 / 289
Erreur annonce 275
Annonce 276 / 289
Erreur annonce 276
Annonce 277 / 289
Erreur annonce 277
Annonce 278 / 289
Erreur annonce 278
Annonce 279 / 289
Erreur annonce 279
Annonce 280 / 289
Erreur annonce 280
Annonce 281 / 289
Erreur annonce 281
Annonce 282 / 289
Erreur annonce 282
Annonce 283 / 289
Erreur annonce 283
Annonce 284 / 289
Erreur annonce 284
Annonce 285 / 289
Erreur annonce 285
Annonce 286 / 289
Erreur annonce 286
Annonce 287 / 289
Erreur annonce 287
Annonce 288 / 289
Erreur annonce 288
Annonce 289 / 289
Erreur annonce 289
Terminé : 232
Erreurs : 57

In [61]:
print(len(erreurs))
print(erreurs[:10])

57
['https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508722/volkswagen-golf-7.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508721/peugeot-208.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508720/bmw-serie-1.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508719/volkswagen-tiguan.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508718/audi-q7.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508717/land-rover-discovery.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508716/hyundai-i10.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508715/volkswagen-touareg.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508714/volkswagen-touareg.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508713/nissan-qashqai.html']

In [62]:
erreurs_restantes = []

In [63]:
import time
from selenium.webdriver.common.by import By

for i, lien in enumerate(erreurs):

    print("Correction", i+1, "/", len(erreurs))

    try:
        driver.get(lien)
        time.sleep(8)   # attendre plus longtemps

        titre = ""
        try:
            titre = driver.find_element(By.CLASS_NAME, "breadcrumb-item1").text
        except:
            pass

        prix = ""
        prix_elements = driver.find_elements(By.CLASS_NAME, "price-value")

        for p in prix_elements:
            texte = p.text.strip()
            if "Dhs" in texte:
                prix = texte
                break

        texte_page = driver.find_element(By.TAG_NAME, "body").text

        annee = ""
        if "Année:" in texte_page:
            annee = texte_page.split("Année:")[1].split("\n")[0].strip()

        kilometrage = ""
        if "Kilométrage:" in texte_page:
            kilometrage = texte_page.split("Kilométrage:")[1].split("\n")[0].strip()

        carburant = ""
        if "Diesel" in texte_page:
            carburant = "Diesel"
        elif "Essence" in texte_page:
            carburant = "Essence"

        transmission = ""
        if "Automatique" in texte_page:
            transmission = "Automatique"
        elif "Manuelle" in texte_page:
            transmission = "Manuelle"

        donnees.append({
            "Titre": titre,
            "Prix": prix,
            "Annee": annee,
            "Kilometrage": kilometrage,
            "Carburant": carburant,
            "Transmission": transmission
        })

    except Exception as e:
        erreurs_restantes.append(lien)

print("Ajoutées :", len(donnees))
print("Encore en erreur :", len(erreurs_restantes))

Correction 1 / 57
Correction 2 / 57
Correction 3 / 57
Correction 4 / 57
Correction 5 / 57
Correction 6 / 57
Correction 7 / 57
Correction 8 / 57
Correction 9 / 57
Correction 10 / 57
Correction 11 / 57
Correction 12 / 57
Correction 13 / 57
Correction 14 / 57
Correction 15 / 57
Correction 16 / 57
Correction 17 / 57
Correction 18 / 57
Correction 19 / 57
Correction 20 / 57
Correction 21 / 57
Correction 22 / 57
Correction 23 / 57
Correction 24 / 57
Correction 25 / 57
Correction 26 / 57
Correction 27 / 57
Correction 28 / 57
Correction 29 / 57
Correction 30 / 57
Correction 31 / 57
Correction 32 / 57
Correction 33 / 57
Correction 34 / 57
Correction 35 / 57
Correction 36 / 57
Correction 37 / 57
Correction 38 / 57
Correction 39 / 57
Correction 40 / 57
Correction 41 / 57
Correction 42 / 57
Correction 43 / 57
Correction 44 / 57
Correction 45 / 57
Correction 46 / 57
Correction 47 / 57
Correction 48 / 57
Correction 49 / 57
Correction 50 / 57
Correction 51 / 57
Correction 52 / 57
Correction 53 / 57
Correction 54 / 57
Correction 55 / 57
Correction 56 / 57
Correction 57 / 57
Ajoutées : 232
Encore en erreur : 57

In [64]:
print(erreurs_restantes[0])

https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508722/volkswagen-golf-7.html

In [65]:
driver.get(erreurs_restantes[0])

InvalidSessionIdException: Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

In [66]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

options = Options()
options.add_argument("--start-maximized")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

print("Selenium redémarré")

Selenium redémarré

In [67]:
driver.get(erreurs_restantes[0])
print(driver.title)

Volkswagen Golf 7 للبيع سيارة غولف 7 2018 Diesel occasion 508722Agadir_phrase Maroc| Moteur.ma

In [68]:
for url in erreurs_restantes:
    try:
        driver.get(url)
        print("OK :", url)

    except Exception as e:
        print("ERREUR :", url)

OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508722/volkswagen-golf-7.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508721/peugeot-208.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508720/bmw-serie-1.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508719/volkswagen-tiguan.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508718/audi-q7.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508717/land-rover-discovery.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508716/hyundai-i10.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508715/volkswagen-touareg.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508714/volkswagen-touareg.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508713/nissan-qashqai.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508712/honda-civic.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508711/peugeot-307.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508709/mercedes-benz-200.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508708/suzuki-carry.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508707/volkswagen-passat.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508706/hyundai-creta.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508705/volkswagen-golf-5.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508704/peugeot-208.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508703/volkswagen-tiguan.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508702/renault-clio.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508701/volkswagen-golf-8.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508700/hyundai-i10.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508699/volkswagen-tiguan.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508698/mercedes-benz-220.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508697/hyundai-i10.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508696/hyundai-i10.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508695/skoda-rapid.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508694/porsche-cayenne.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508693/citroen-cx.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508692/renault-clio.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508691/volkswagen-passat.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508690/mercedes-benz-250.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508689/opel-astra.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508688/dacia-logan.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508687/hyundai-atos.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508686/skoda-karoq.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508684/renault-r4.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508683/renault-clio.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508682/skoda-karoq.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508681/dacia-dokker.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508680/toyota-corolla.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508679/hyundai-i10.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508678/volkswagen-coccinelle.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508677/volkswagen-jetta.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508676/citroen-c4.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508675/mercedes-benz-classe-c.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508674/autre-autre.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508673/autre-autre.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508672/dacia-dokker.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508671/land-rover-range-rover-sport.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508670/volkswagen-golf-6.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508669/peugeot-308.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508668/toyota-corolla.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508667/mercedes-benz-220.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508666/mercedes-benz-220.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508665/renault-megane.html
OK : https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508664/renault-clio.html

In [69]:
from selenium.webdriver.common.by import By
import time

url_test = annonces_erreurs_recup[0]["URL"]

driver.get(url_test)

time.sleep(3)

print(driver.title)

NameError: name 'annonces_erreurs_recup' is not defined

In [70]:
from selenium.webdriver.common.by import By
import time

url_test = erreurs_restantes[0]

driver.get(url_test)

time.sleep(3)

print(driver.title)

ReadTimeoutError: HTTPConnectionPool(host='localhost', port=60186): Read timed out. (read timeout=120)

In [71]:
driver.quit()

In [72]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument("--start-maximized")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

driver.set_page_load_timeout(30)

print("Nouveau driver OK")

Nouveau driver OK

In [73]:
url_test = "https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508722/volkswagen-golf-7.html"

try:
    driver.get(url_test)
    print("Page chargée")
    print(driver.title)

except:
    print("Page trop lente")

Page chargée
Volkswagen Golf 7 للبيع سيارة غولف 7 2018 Diesel occasion 508722Agadir_phrase Maroc| Moteur.ma

In [74]:
driver.set_page_load_timeout(20)

In [75]:
from selenium.common.exceptions import TimeoutException

try:
    driver.get(url_test)
except TimeoutException:
    print("La page est suffisamment chargée.")

In [76]:
print(driver.title)

Volkswagen Golf 7 للبيع سيارة غولف 7 2018 Diesel occasion 508722Agadir_phrase Maroc| Moteur.ma

In [77]:
print(driver.current_url)

https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508722/volkswagen-golf-7.html

In [78]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

options = webdriver.ChromeOptions()

options.page_load_strategy = "eager"

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

In [79]:
print(driver.title)
print(driver.current_url)

data:,

In [80]:
from selenium.webdriver.common.by import By

prix = driver.find_elements(By.CLASS_NAME, "price-value")

print("Nombre :", len(prix))

for p in prix:
    print(p.text)

Nombre : 0

In [81]:
print(driver.page_source[:3000])

<html><head></head><body></body></html>

In [82]:
try:
    driver.quit()
except:
    pass

In [83]:
driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508722/volkswagen-golf-7.html")

MaxRetryError: HTTPConnectionPool(host='localhost', port=65023): Max retries exceeded with url: /session/3a451f4ae4db1b830b26cd7dc2b59a78/url (Caused by NewConnectionError("HTTPConnection(host='localhost', port=65023): Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée"))

In [ ]:
import time
time.sleep(5)

In [84]:
try:
    driver.quit()
except:
    pass

In [85]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

options = webdriver.ChromeOptions()
options.page_load_strategy = "eager"

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

In [86]:
driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508722/volkswagen-golf-7.html")

print(driver.title)

Volkswagen Golf 7 للبيع سيارة غولف 7 2018 Diesel occasion 508722Agadir_phrase Maroc| Moteur.ma

In [87]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

options = webdriver.ChromeOptions()
options.page_load_strategy = "eager"

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

In [88]:
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import pandas as pd
import time

annonces_recup = []
erreurs_finales = []

for url in erreurs_restantes:

    try:
        driver.get(url)
        time.sleep(3)

        titre = ""
        annee = ""
        kilometrage = ""
        carburant = ""
        transmission = ""
        prix = ""

        try:
            titre = driver.find_element(By.TAG_NAME, "h1").text
        except:
            pass

        try:
            prix = driver.find_element(By.CLASS_NAME, "price-value").text
        except:
            pass

        specs = driver.find_elements(By.CLASS_NAME, "caracteristic")

        for s in specs:
            txt = s.text

            if "Année" in txt:
                annee = txt.split("\n")[-1]

            elif "Kilométrage" in txt:
                kilometrage = txt.split("\n")[-1]

            elif "Carburant" in txt:
                carburant = txt.split("\n")[-1]

            elif "Transmission" in txt:
                transmission = txt.split("\n")[-1]

        annonces_recup.append({
            "Titre": titre,
            "Prix": prix,
            "Annee": annee,
            "Kilometrage": kilometrage,
            "Carburant": carburant,
            "Transmission": transmission,
            "URL": url
        })

        print("✓", titre)

    except Exception:
        erreurs_finales.append(url)
        print("✗ Erreur :", url)

df_erreurs = pd.DataFrame(annonces_recup)

✓ Volkswagen Golf 7
✓ Peugeot 208
✓ BMW Série 1
✓ Volkswagen Tiguan
✓ Audi Q7
✓ Land Rover Discovery
✓ Hyundai i10
✓ Volkswagen Touareg
✓ Volkswagen Touareg
✓ Nissan Qashqai
✓ Honda Civic
✓ Peugeot 307
✓ Mercedes-Benz 200
✓ Suzuki Carry
✓ Volkswagen Passat
✓ Hyundai Creta
✓ Volkswagen Golf 5
✓ Peugeot 208
✓ Volkswagen Tiguan
✓ Renault Clio
✓ Volkswagen Golf 8
✓ Hyundai i10
✓ Volkswagen Tiguan
✓ Mercedes-Benz 220
✓ Hyundai i10
✓ Hyundai i10
✓ Skoda Rapid
✓ Porsche Cayenne
✓ Citroën CX
✓ Renault Clio
✓ Volkswagen Passat
✓ Mercedes-Benz 250
✓ Opel Astra
✓ Dacia Logan
✓ Hyundai Atos
✓ Skoda Karoq
✓ Renault R4
✓ Renault Clio
✓ Skoda Karoq
✓ Dacia Dokker
✓ Toyota Corolla
✓ Hyundai i10
✓ Volkswagen Coccinelle
✓ Volkswagen Jetta
✓ Citroën C4
✓ Mercedes-Benz Classe C
✓ Autre Autre
✓ Autre Autre
✓ Dacia Dokker
✓ Land Rover Range Rover Sport
✓ Volkswagen Golf 6
✓ Peugeot 308
✓ Toyota Corolla
✓ Mercedes-Benz 220
✓ Mercedes-Benz 220
✓ Renault Megane
✓ Renault Clio

In [89]:
print(df_erreurs.head())

print("Récupérées :", len(df_erreurs))
print("Encore en erreur :", len(erreurs_finales))

               Titre Prix Annee Kilometrage Carburant Transmission  \
0  Volkswagen Golf 7
1        Peugeot 208
2        BMW Série 1
3  Volkswagen Tiguan
4            Audi Q7

                                                 URL
0  https://www.moteur.ma/fr/voiture/achat-voiture...
1  https://www.moteur.ma/fr/voiture/achat-voiture...
2  https://www.moteur.ma/fr/voiture/achat-voiture...
3  https://www.moteur.ma/fr/voiture/achat-voiture...
4  https://www.moteur.ma/fr/voiture/achat-voiture...
Récupérées : 57
Encore en erreur : 0

In [90]:
driver.get(df["URL"][0])

import time
time.sleep(5)

print(driver.page_source[:5000])

KeyError: 'URL'

In [91]:
print(df.columns)

Index(['Titre', 'Annee', 'Kilometrage', 'Carburant', 'Transmission'], dtype='str')

In [92]:
driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508722/volkswagen-golf-7.html")

import time
time.sleep(5)

print(driver.page_source[:5000])

<html class="no-js" lang="fr" dir="ltr"><head>
    <script type="text/javascript" async="" src="https://analytics.tiktok.com/i18n/pixel/static/identify_b8133453.js"></script><script async="" src="https://scripts.clarity.ms/0.8.67/clarity.js"></script><script type="text/javascript" async="" src="https://analytics.tiktok.com/i18n/pixel/static/main.MTA2MWE1OWMwOQ.js" data-id="CTC6DRBC77U38DUS8CO0"></script><script type="text/javascript" async="" src="https://analytics.tiktok.com/i18n/pixel/events.js?sdkid=CTC6DRBC77U38DUS8CO0&amp;lib=ttq"></script><script async="" src="https://www.clarity.ms/tag/jjlg7xl4le?ref=gtm2"></script><script src="https://connect.facebook.net/signals/config/627061288872447?v=2.9.357&amp;r=stable&amp;domain=www.moteur.ma&amp;hme=1179b74563cacb97c6ebae600e40937237ab12824fb84996eee07eca65cabbd4&amp;ex_m=107%2C208%2C158%2C22%2C73%2C74%2C149%2C69%2C68%2C11%2C167%2C93%2C16%2C141%2C130%2C39%2C76%2C81%2C137%2C163%2C169%2C26%2C27%2C28%2C30%2C48%2C150%2C78%2C115%2C18%2C20%2C44%2C40%2C42%2C41%2C86%2C95%2C99%2C113%2C148%2C151%2C46%2C114%2C24%2C21%2C122%2C70%2C36%2C153%2C152%2C154%2C145%2C143%2C25%2C35%2C59%2C112%2C165%2C71%2C17%2C156%2C117%2C84%2C67%2C19%2C88%2C89%2C119%2C87%2C139%2C138%2C142%2C164%2C34%2C49%2C116%2C47%2C8%2C4%2C5%2C7%2C6%2C3%2C94%2C104%2C170%2C175%2C222%2C75%2C235%2C234%2C233%2C23%2C33%2C55%2C106%2C61%2C10%2C64%2C100%2C101%2C102%2C108%2C133%2C31%2C29%2C135%2C136%2C132%2C131%2C159%2C77%2C162%2C160%2C161%2C50%2C60%2C126%2C15%2C166%2C45%2C280%2C281%2C279%2C294%2C310%2C215%2C204%2C62%2C205%2C203%2C313%2C304%2C52%2C216%2C110%2C134%2C83%2C124%2C54%2C123%2C129%2C128%2C58%2C65%2C63%2C155%2C79%2C80%2C118%2C37%2C32%2C53%2C56%2C103%2C168%2C1%2C127%2C14%2C125%2C12%2C2%2C57%2C96%2C66%2C121%2C92%2C91%2C171%2C172%2C97%2C98%2C9%2C105%2C51%2C146%2C90%2C82%2C72%2C120%2C109%2C43%2C147%2C0%2C85%2C140%2C144%2C157%2C38%2C111%2C13%2C173%2C232%2C230%2C225%2C227%2C228%2C229%2C226%2C214%2C231%2C224%2C237%2C196%2C190%2C194%2C195%2C193%2C188%2C334%2C263%2C270%2C271%2C272%2C269%2C273%2C264%2C267%2C261%2C274%2C275%2C266%2C276%2C268%2C277%2C262%2C207%2C265%2C260%2C199%2C191%2C192%2C218%2C189%2C187%2C213%2C331%2C239%2C209%2C181%2C182%2C177%2C183%2C180%2C178%2C179%2C176%2C174%2C185%2C186%2C184%2C282%2C333%2C303%2C301%2C302%2C300%2C197%2C242%2C249%2C243%2C245%2C248%2C246%2C247%2C244%2C241%2C258%2C253%2C255%2C252%2C259%2C256%2C251%2C257%2C254%2C250%2C296%2C307" async=""></script><script src="https://connect.facebook.net/signals/config/204407031549583?v=2.9.357&amp;r=stable&amp;domain=www.moteur.ma&amp;hme=1179b74563cacb97c6ebae600e40937237ab12824fb84996eee07eca65cabbd4&amp;ex_m=107%2C208%2C158%2C22%2C73%2C74%2C149%2C69%2C68%2C11%2C167%2C93%2C16%2C141%2C130%2C39%2C76%2C81%2C137%2C163%2C169%2C26%2C27%2C28%2C30%2C48%2C150%2C78%2C115%2C18%2C20%2C44%2C40%2C42%2C41%2C86%2C95%2C99%2C113%2C148%2C151%2C46%2C114%2C24%2C21%2C122%2C70%2C36%2C153%2C152%2C154%2C145%2C143%2C25%2C35%2C59%2C112%2C165%2C71%2C17%2C156%2C117%2C84%2C67%2C19%2C88%2C89%2C119%2C87%2C139%2C138%2C142%2C164%2C34%2C49%2C116%2C47%2C8%2C4%2C5%2C7%2C6%2C3%2C94%2C104%2C170%2C175%2C222%2C75%2C235%2C234%2C233%2C23%2C33%2C55%2C106%2C61%2C10%2C64%2C100%2C101%2C102%2C108%2C133%2C31%2C29%2C135%2C136%2C132%2C131%2C159%2C77%2C162%2C160%2C161%2C50%2C60%2C126%2C15%2C166%2C45%2C280%2C281%2C279%2C294%2C310%2C215%2C204%2C62%2C205%2C203%2C313%2C304%2C52%2C216%2C110%2C134%2C83%2C124%2C54%2C123%2C129%2C128%2C58%2C65%2C63%2C155%2C79%2C80%2C118%2C37%2C32%2C53%2C56%2C103%2C168%2C1%2C127%2C14%2C125%2C12%2C2%2C57%2C96%2C66%2C121%2C92%2C91%2C171%2C172%2C97%2C98%2C9%2C105%2C51%2C146%2C90%2C82%2C72%2C120%2C109%2C43%2C147%2C0%2C85%2C140%2C144%2C157%2C38%2C111%2C13%2C173" async=""></script><script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-Q1NXR1BVFD&amp;cx=c&amp;gtm=4e67f0"></script><script async="" type="text/javascript" src="https://www.googletagservices.com/tag/js/gpt.js"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-TLMJHZ6"></script><script>
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-TLMJHZ6');
</script>
    <script>
        window.dataLayer = window.dataLayer || [];
                    window.dataLayer.push({"lang":"fr","section_type":"occasion","content_type":"detail","category":"car","event":"page_view"});
            </script>
    <meta name="robots" content="index, follow">
<meta charset="utf-8">
<script>
    window.googletag = window.googletag || { cmd: [] };
</script>
<meta http-equiv="x-ua-compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="msapplication-TileColor"

In [93]:
html = driver.page_source

print("Prix trouvé :", "Dhs" in html)
print("Année 2018 :", "2018" in html)
print("Diesel :", "Diesel" in html)
print("Golf 7 :", "Golf" in html)

Prix trouvé : True
Année 2018 : True
Diesel : True
Golf 7 : True

In [94]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(driver.page_source, "html.parser")

text = soup.get_text(" ", strip=True)

print(text[:8000])

Volkswagen Golf 7 للبيع سيارة غولف 7 2018 Diesel occasion 508722Agadir_phrase Maroc| Moteur.ma 0 Accueil Neuf Accueil Voitures Tarifs et prix des voitures neuves Dernières promotions 2026 Offres du moment Comparatif voitures neuves Motos Tarifs et prix des motos neuves Dernières promotions 2026 Camions Tarifs et prix des camions neufs Promotion Dernières Promotions 2026 Offres du moment Émissions Actualités Marché Auto Forum Occasion Voitures Vendre une voiture Acheter une voiture d'occasion La Cote d'occasion Motos Vendre une moto Acheter une moto d'occasion Camions Vendre un camion Acheter un camion d'occasion Showrooms Pro Véhicules d'occasion Voiture de location Agences de location ﻿Se connecter S'inscrire Vendez Votre Voiture Se connecter Vendez Votre Voiture 0 العربية opel astra opel corsa opel grandland opel frontera opel mokka Seat Leon FR Seat ibiza SANTA FE Full Hybrid taigo golf 8 T-roc tiguan Offres du moment DFSK E5 magnite chery tiggo 7 pro dacia sandero stepway opel astra opel corsa opel grandland opel frontera opel mokka Seat Leon FR Seat ibiza SANTA FE Full Hybrid taigo golf 8 T-roc tiguan Offres du moment DFSK E5 magnite chery tiggo 7 pro dacia sandero stepway opel astra opel corsa opel grandland opel frontera opel mokka Seat Leon FR Seat ibiza ‹ › Accueil Occasion Acheter une voiture d'occasion Volkswagen Golf 7 Comparatif voitures neuves 0 Marque Abarth Alfa Romeo Alpine Aston Martin Audi BAIC Bentley BMW BYD Changan Chery Chevrolet Citroën Cupra Dacia DEEPAL DENZA DFSK Dongfeng DS EXEED Ferrari Fiat Ford Foton GAC GAZ Geely GWM Honda Hyundai Isuzu jac Jaecoo Jaguar Jeep Jetour KGM Kia Land Rover Leapmotor Lexus Lynk & Co Mahindra Maserati Mazda Mercedes-Benz MG Mini Mitsubishi Neo Motors Nissan Omoda Opel Peugeot Porsche Renault ROX Seat Seres Skoda Smart soueast Ssangyong Suzuki Tata Tesla Toyota Volkswagen Volvo XPENG Zeekr Modèle Version Marque Abarth Alfa Romeo Alpine Aston Martin Audi BAIC Bentley BMW BYD Changan Chery Chevrolet Citroën Cupra Dacia DEEPAL DENZA DFSK Dongfeng DS EXEED Ferrari Fiat Ford Foton GAC GAZ Geely GWM Honda Hyundai Isuzu jac Jaecoo Jaguar Jeep Jetour KGM Kia Land Rover Leapmotor Lexus Lynk & Co Mahindra Maserati Mazda Mercedes-Benz MG Mini Mitsubishi Neo Motors Nissan Omoda Opel Peugeot Porsche Renault ROX Seat Seres Skoda Smart soueast Ssangyong Suzuki Tata Tesla Toyota Volkswagen Volvo XPENG Zeekr Modèle Version Marque Abarth Alfa Romeo Alpine Aston Martin Audi BAIC Bentley BMW BYD Changan Chery Chevrolet Citroën Cupra Dacia DEEPAL DENZA DFSK Dongfeng DS EXEED Ferrari Fiat Ford Foton GAC GAZ Geely GWM Honda Hyundai Isuzu jac Jaecoo Jaguar Jeep Jetour KGM Kia Land Rover Leapmotor Lexus Lynk & Co Mahindra Maserati Mazda Mercedes-Benz MG Mini Mitsubishi Neo Motors Nissan Omoda Opel Peugeot Porsche Renault ROX Seat Seres Skoda Smart soueast Ssangyong Suzuki Tata Tesla Toyota Volkswagen Volvo XPENG Zeekr Modèle Version Comparer × Volkswagen
                                    Golf 7 183,000 MAD Voiture Agadir Jul 18, 2026 21 vues Informations Véhicule Marque: Volkswagen Modèle: Golf 7 Année: 2018 Kilométrage: 220,000 km Carburant: Diesel Transmission: Automatique Carrosserie: N/A Couleur: N/A Nombre de portes 5 Puissance fiscale 8 Spécifications rapides سيارة غولف 7 السيارة ممتازة جدا. للحادين فقط البيع المباشر ...الوكالة لا. Caractéristiques & Options Premier propriétaire Véhicule préparé Historique d'accidents Importation neuve Statut de douane N/A options État du véhicule ABS Climatisation Airbags Fermeture centralisée Régulateur de vitesse Vitres électriques ESP Intérieur cuir Navigation GPS Ordinateur de bord Radar de recul Jantes Limiteur de vitesse CD / MP3 / Bluetooth Avis & Évaluations 4 /5 Basé sur 0 avis 5 315 4 142 3 355 2 331 1 121 Annonces Similaires Volkswagen Tiguan 280,000 MAD il y a 14 minutes Volkswagen Tiguan 490,000 MAD il y a 25 minutes Volkswagen Touareg 165,000 MAD il y a 36 minutes Volkswagen Tiguan 290,000 MAD il y a 36 minutes Volkswagen Golf 7 210,000 MAD il y a 58 minutes Dernières annonces premium Premium Mercedes-Benz Classe C Casablanca 2022 Appeler pour le prix Premium Audi A4 Casablanca 2014 180,000 MAD Premium Fiat Tipo Kénitra 2018 165,000 MAD Premium Mercedes-Benz Classe C Meknès 1999 88,000 MAD Premium Renault Kangoo Agadir 2013 98,000 MAD Premium Hyundai Santa Fe Casablanca 2009 80,000 MAD Premium Mercedes-Benz Classe CLA Marrakech 2013 225,000 MAD Premium Chevrolet Camaro Rabat 2022 Appeler pour le prix Premium Porsche Cayenne Casablanca 2022 Appeler pour le prix Premium Seat Ibiza 2012 82,000 MAD Premium Mercedes-Benz Classe C Casablanca 2022 Appeler pour le prix Premium Audi A4 Casablanca 2014 180,000 MAD Premium Fiat Tipo Kénitra 2018 165,000 MAD Premium Mercedes-Benz Classe C Meknès 1999 88,000 MAD Premium Renault Kangoo Agadir 2013 98,000 MAD Premium Hyundai Santa Fe Casablanca 2009 80,000 MAD Premium Mercedes-Benz Classe CLA Marrakech 2013 225,000 MAD Premium Chevrolet Camaro Rabat 2022 Appeler pour le prix Premium Porsche Cayenne Casablanca 2022 Appeler pour le prix Premium Seat Ibiza 2012 82,000 MAD ‹ › Publié par rachid orka Vendeur depuis Jul 2026 Informations Contact Agadir Appeler maintenant Contacter le vendeur Appeler maintenant Modèles neufs Volkswagen Caddy Crafter Golf 8 T-Cross T-Roc Taigo Tiguan Touareg Caddy Crafter Golf 8 T-Cross T-Roc Taigo Tiguan Touareg ‹ › Prix promotionnels du moment Citroën C4 À partir de 217 900 Dhs BAIC X7 À partir de 269 000 Dhs Audi Q2 À partir de 348 000 Dhs BAIC X55 À partir de 234 000 Dhs Kia pv5 Passenger À partir de 456 000 Dhs GWM haval jolion À partir de 189 900 Dhs BAIC X35 À partir de 169 000 Dhs Dernières voitures neuves Nouveau DENZA D9 100 % électrique (BEV) Prix sur demande 2026 · SUV et 4x4 Nouveau DENZA D9 DM-i Hybride rechargeable (PHEV) 889 900 Dhs 2026 · SUV et 4x4 Nouveau DENZA B8 2.0 Turbo essence  PHEV 869 900 Dhs 2026 · SUV et 4x4 Nouveau DENZA B5 1.5 Turbo essence  PHEV 629 900 Dhs 2026 · SUV et 4x4 Nouveau Leapmotor B10 REEV 1.5 AT 218 269 000 Dhs 2026 · SUV et 4x4 Nouveau Citroën C3 PLUS PACK ESSENCE BVM 173 900 Dhs 2026 · Citadine Nouveau Fiat Grizzly Fastback BEV Prix sur demande 2026 · SUV et 4x4 Nouveau Fiat Grizzly Fastback 1.2 Turbo Hybrid 48V Prix sur demande 2026 · SUV et 4x4 Nouveau Fiat Grizzly BEV Prix sur demande 2026 · SUV et 4x4 Nouveau Fiat Grizzly 1.2 MHEV  Hybride léger Prix sur demande 2026 · SUV et 4x4 Nouveau DENZA D9 100 % électrique (BEV) Prix sur demande 2026 · SUV et 4x4 Nouveau DENZA D9 DM-i Hybride rechargeable (PHEV) 889 900 Dhs 2026 · SUV et 4x4 Nouveau DENZA B8 2.0 Turbo essence  PHEV 869 900 Dhs 2026 · SUV et 4x4 Nouveau DENZA B5 1.5 Turbo essence  PHEV 629 900 Dhs 2026 · SUV et 4x4 Nouveau Leapmotor B10 REEV 1.5 AT 218 269 000 Dhs 2026 · SUV et 4x4 Nouveau Citroën C3 PLUS PACK ESSENCE BVM 173 900 Dhs 2026 · Citadine Nouveau Fiat Grizzly Fastback BEV Prix sur demande 2026 · SUV et 4x4 Nouveau Fiat Grizzly Fastback 1.2 Turbo Hybrid 48V Prix sur demande 2026 · SUV et 4x4 Nouveau Fiat Grizzly BEV Prix sur demande 2026 · SUV et 4x4 Nouveau Fiat Grizzly 1.2 MHEV  Hybride léger Prix sur demande 2026 · SUV et 4x4 ‹ › Comparez les voitures neuves au Maroc Analysez les prix, motorisations et équipements pour faire le meilleur choix. ديبال جي 318 1.5T REEV propulsion (RWD) Nom... دينزا بي 5 1.5 Turbo essence  PHEV ديبال VS دينزا ميني هاتش 3p ONE OXFORD بيجو 208 1.5 BlueHDi 100 GT ميني VS بيجو دفسك إي 5 1.5 l 277 PHEV AT M1 دفسك إي 5 1.5 l 277 PHEV AT L2 دفسك VS دفسك تويوتا لاند كروزر Prado 2.8 l D4D Adventure داسيا سانديرو Stepway 1.5 dCi 95 Essentiel تويوتا VS داسيا جي دبليو أم هافال جوليون HEV FINITION TOP سوإيست إس 06 ICE 1.6 l 197 AT Summit جي دبليو أم VS سوإيست لاند روفر ديفندر 3.0 L Diesel 200 ch AWD Auto S... بي ام دبليو اكس 3 xDrive 20d Pack M لاند روفر VS بي ام دبليو بي ام دبليو اكس 1 sDrive 18d Pack M أودي كيو3 30 TDI 150 S-Tronic Dynamic بي ام دبليو VS أودي كيا سورينتو HEV 1.6 T-GDi 230 4WD Executiv... كيا سورينتو 2.2 CRDi 202 DCT Active+ TO كيا VS كيا ديبال ج

In [95]:
import re
from bs4 import BeautifulSoup

driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508722/volkswagen-golf-7.html")

import time
time.sleep(3)

soup = BeautifulSoup(driver.page_source, "html.parser")
texte = soup.get_text(" ", strip=True)

# Prix
prix = re.search(r'(\d[\d\s,]*)\s*MAD', texte)

# Année
annee = re.search(r'Année:\s*(\d{4})', texte)

# Kilométrage
km = re.search(r'Kilométrage:\s*([\d,\s]+)\s*km', texte)

# Carburant
carburant = re.search(r'Carburant:\s*([A-Za-zÀ-ÿ]+)', texte)

# Transmission
transmission = re.search(r'Transmission:\s*([A-Za-zÀ-ÿ]+)', texte)

print("Prix :", prix.group(1) if prix else "Non trouvé")
print("Année :", annee.group(1) if annee else "Non trouvé")
print("Kilométrage :", km.group(1) if km else "Non trouvé")
print("Carburant :", carburant.group(1) if carburant else "Non trouvé")
print("Transmission :", transmission.group(1) if transmission else "Non trouvé")

Prix : 7 183,000
Année : 2018
Kilométrage : 220,000
Carburant : Diesel
Transmission : Automatique

In [96]:
prix = re.search(r'Voiture\s+([\d,\s]+)\s*MAD', texte)

In [97]:
prixs = re.findall(r'([\d,\s]+)\s*MAD', texte)
print(prixs)

[' 7 183,000 ', ' 280,000 ', ' 490,000 ', ' 165,000 ', ' 290,000 ', ' 7 210,000 ', ' 2014 180,000 ', ' 2013 195,000 ', ' 2014 160,000 ', ' 2018 290,000 ', ' 2019 520,000 ', ' 2016 139,000 ', ' 1993 65,000 ', ' 2013 99,000 ', ' 2005 95,000 ', ' 2018 188,000 ', ' 2014 180,000 ', ' 2013 195,000 ', ' 2014 160,000 ', ' 2018 290,000 ', ' 2019 520,000 ', ' 2016 139,000 ', ' 1993 65,000 ', ' 2013 99,000 ', ' 2005 95,000 ', ' 2018 188,000 ']

In [98]:
import re

prix = prix_elements[0].text

# garder uniquement les nombres
nombres = re.findall(r"\d+", prix)

# supprimer le premier nombre si c'est le numéro du modèle (Golf 7)
if len(nombres) >= 3:
    prix = nombres[1] + "," + nombres[2]
else:
    prix = ",".join(nombres)

print(prix)

InvalidSessionIdException: Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f3195736]
	chromedriver!(No symbol) [0x7ff6f31e1ed6]
	chromedriver!(No symbol) [0x7ff6f32190d2]
	chromedriver!(No symbol) [0x7ff6f3212ef2]
	chromedriver!(No symbol) [0x7ff6f32126b2]
	chromedriver!(No symbol) [0x7ff6f315de1b]
	chromedriver!(No symbol) [0x7ff6f315e472]
	chromedriver!(No symbol) [0x7ff6f315ea35]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!(No symbol) [0x7ff6f315d39c]
	chromedriver!GetHandleVerifier [0x7ff6f3e03d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

In [99]:
driver

In [100]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

In [101]:
url = "https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508722/volkswagen-golf-7.html"

driver.get(url)

In [102]:
import time
time.sleep(5)

In [103]:
from selenium.webdriver.common.by import By

prix_elements = driver.find_elements(By.CLASS_NAME, "price-value")

for p in prix_elements:
    print(p.text)

Prix sur demande
Prix sur demande
Prix sur demande

In [104]:
print(driver.current_url)

https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/508722/volkswagen-golf-7.html

In [105]:
print(driver.title)

Volkswagen Golf 7 للبيع سيارة غولف 7 2018 Diesel occasion 508722Agadir_phrase Maroc| Moteur.ma

In [106]:
from selenium.webdriver.common.by import By
import pandas as pd
import time
import re

donnees = []

for i, url in enumerate(liens):
    try:
        driver.get(url)
        time.sleep(2)

        texte = driver.find_element(By.TAG_NAME, "body").text

        prix = ""
        m = re.search(r"(\d[\d,\s]*)\s*MAD", texte)
        if m:
            prix = m.group(1).replace("\n"," ").strip()

        def extraire(champ):
            m = re.search(champ + r"\s*:\s*(.+)", texte)
            return m.group(1).split("\n")[0].strip() if m else ""

        donnees.append({
            "Titre": driver.title.split("|")[0].split("occasion")[0].strip(),
            "Prix": prix,
            "Annee": extraire("Année"),
            "Kilometrage": extraire("Kilométrage"),
            "Carburant": extraire("Carburant"),
            "Transmission": extraire("Transmission"),
            "URL": url
        })

        print(i + 1, "OK")

    except Exception:
        print(i + 1, "Erreur")

df = pd.DataFrame(donnees)

1 Erreur
2 Erreur
3 Erreur
4 Erreur
5 Erreur
6 Erreur
7 Erreur
8 Erreur
9 Erreur
10 Erreur
11 Erreur
12 Erreur
13 Erreur
14 Erreur
15 Erreur
16 Erreur
17 Erreur
18 Erreur
19 Erreur
20 Erreur
21 Erreur
22 Erreur
23 Erreur
24 Erreur
25 Erreur
26 Erreur
27 Erreur
28 Erreur
29 Erreur
30 Erreur
31 Erreur
32 Erreur
33 Erreur
34 Erreur
35 Erreur
36 Erreur
37 Erreur
38 Erreur
39 Erreur
40 Erreur
41 Erreur
42 Erreur
43 Erreur
44 Erreur
45 Erreur
46 Erreur
47 Erreur
48 Erreur
49 Erreur
50 Erreur
51 Erreur
52 Erreur
53 Erreur
54 Erreur
55 Erreur
56 Erreur
57 Erreur
58 Erreur
59 Erreur
60 Erreur
61 Erreur
62 Erreur
63 Erreur
64 Erreur
65 Erreur
66 Erreur
67 Erreur
68 Erreur
69 Erreur
70 Erreur
71 Erreur
72 Erreur
73 Erreur
74 Erreur
75 Erreur
76 Erreur
77 Erreur
78 Erreur
79 Erreur
80 Erreur
81 Erreur
82 Erreur
83 Erreur
84 Erreur
85 Erreur
86 Erreur
87 Erreur
88 Erreur
89 Erreur
90 Erreur
91 Erreur
92 Erreur
93 Erreur
94 Erreur
95 Erreur
96 Erreur
97 Erreur
98 Erreur
99 Erreur
100 Erreur
101 Erreur
102 Erreur
103 Erreur
104 Erreur
105 Erreur
106 Erreur
107 Erreur
108 Erreur
109 Erreur
110 Erreur
111 Erreur
112 Erreur
113 Erreur
114 Erreur
115 Erreur
116 Erreur
117 Erreur
118 Erreur
119 Erreur
120 Erreur
121 Erreur
122 Erreur
123 Erreur
124 Erreur
125 Erreur
126 Erreur
127 Erreur
128 Erreur
129 Erreur
130 Erreur
131 Erreur
132 Erreur
133 Erreur
134 Erreur
135 Erreur
136 Erreur
137 Erreur
138 Erreur
139 Erreur
140 Erreur
141 Erreur
142 Erreur
143 Erreur
144 Erreur
145 Erreur
146 Erreur
147 Erreur
148 Erreur
149 Erreur
150 Erreur
151 Erreur
152 Erreur
153 Erreur
154 Erreur
155 Erreur
156 Erreur
157 Erreur
158 Erreur
159 Erreur
160 Erreur
161 Erreur
162 Erreur
163 Erreur
164 Erreur
165 Erreur
166 Erreur
167 Erreur
168 Erreur
169 Erreur
170 Erreur
171 Erreur
172 Erreur
173 Erreur
174 Erreur
175 Erreur
176 Erreur
177 Erreur
178 Erreur
179 Erreur
180 Erreur
181 Erreur
182 Erreur
183 Erreur
184 Erreur
185 Erreur
186 Erreur
187 Erreur
188 Erreur
189 Erreur
190 Erreur
191 Erreur
192 Erreur
193 Erreur
194 Erreur
195 Erreur
196 Erreur
197 Erreur
198 Erreur
199 Erreur
200 Erreur
201 Erreur
202 Erreur
203 Erreur
204 Erreur
205 Erreur
206 Erreur
207 Erreur
208 Erreur
209 Erreur
210 Erreur
211 Erreur
212 Erreur
213 Erreur
214 Erreur
215 Erreur
216 Erreur
217 Erreur
218 Erreur
219 Erreur
220 Erreur
221 Erreur
222 Erreur
223 Erreur
224 Erreur
225 Erreur
226 Erreur
227 Erreur
228 Erreur
229 Erreur
230 Erreur
231 Erreur
232 Erreur
233 Erreur
234 Erreur
235 Erreur
236 Erreur
237 Erreur
238 Erreur
239 Erreur
240 Erreur
241 Erreur
242 Erreur
243 Erreur
244 Erreur
245 Erreur
246 Erreur
247 Erreur
248 Erreur
249 Erreur
250 Erreur
251 Erreur
252 Erreur
253 Erreur
254 Erreur
255 Erreur
256 Erreur
257 Erreur
258 Erreur
259 Erreur
260 Erreur
261 Erreur
262 Erreur
263 Erreur
264 Erreur
265 Erreur
266 Erreur
267 Erreur
268 Erreur
269 Erreur
270 Erreur
271 Erreur
272 Erreur
273 Erreur
274 Erreur
275 Erreur
276 Erreur
277 Erreur
278 Erreur
279 Erreur
280 Erreur
281 Erreur
282 Erreur
283 Erreur
284 Erreur
285 Erreur
286 Erreur
287 Erreur
288 Erreur
289 Erreur
290 Erreur
291 Erreur
292 Erreur
293 Erreur
294 Erreur
295 Erreur
296 Erreur
297 Erreur
298 Erreur
299 Erreur
300 Erreur
301 Erreur
302 Erreur
303 Erreur
304 Erreur
305 Erreur
306 Erreur
307 Erreur
308 Erreur
309 Erreur
310 Erreur
311 Erreur
312 Erreur
313 Erreur
314 Erreur
315 Erreur
316 Erreur
317 Erreur
318 Erreur
319 Erreur
320 Erreur
321 Erreur
322 Erreur
323 Erreur
324 Erreur
325 Erreur
326 Erreur
327 Erreur
328 Erreur
329 Erreur
330 Erreur
331 Erreur
332 Erreur
333 Erreur
334 Erreur
335 Erreur
336 Erreur
337 Erreur
338 Erreur
339 Erreur
340 Erreur
341 Erreur
342 Erreur
343 Erreur
344 Erreur
345 Erreur
346 Erreur
347 Erreur
348 Erreur
349 Erreur
350 Erreur
351 Erreur
352 Erreur
353 Erreur
354 Erreur
355 Erreur
356 Erreur
357 Erreur
358 Erreur
359 Erreur
360 Erreur
361 Erreur
362 Erreur
363 Erreur
364 Erreur
365 Erreur
366 Erreur
367 Erreur
368 Erreur
369 Erreur
370 Erreur
371 Erreur
372 Erreur
373 Erreur
374 Erreur
375 Erreur
376 Erreur
377 Erreur
378 Erreur
379 Erreur
380 Erreur
381 Erreur
382 Erreur
383 Erreur
384 Erreur
385 Erreur
386 Erreur
387 Erreur
388 Erreur
389 Erreur
390 Erreur
391 Erreur
392 Erreur
393 Erreur
394 Erreur
395 Erreur
396 Erreur
397 Erreur
398 Erreur
399 Erreur
400 Erreur
401 Erreur
402 Erreur
403 Erreur
404 Erreur
405 Erreur
406 Erreur
407 Erreur
408 Erreur
409 Erreur
410 Erreur
411 Erreur
412 Erreur
413 Erreur
414 Erreur
415 Erreur
416 Erreur
417 Erreur
418 Erreur
419 Erreur
420 Erreur
421 Erreur
422 Erreur
423 Erreur
424 Erreur
425 Erreur
426 Erreur
427 Erreur
428 Erreur
429 Erreur
430 Erreur
431 Erreur
432 Erreur
433 Erreur
434 Erreur
435 Erreur
436 Erreur
437 Erreur
438 Erreur
439 Erreur
440 Erreur
441 Erreur
442 Erreur
443 Erreur
444 Erreur
445 Erreur
446 Erreur
447 Erreur
448 Erreur
449 Erreur
450 Erreur
451 Erreur
452 Erreur
453 Erreur
454 Erreur
455 Erreur
456 Erreur
457 Erreur
458 Erreur
459 Erreur
460 Erreur
461 Erreur
462 Erreur
463 Erreur
464 Erreur
465 Erreur
466 Erreur
467 Erreur
468 Erreur
469 Erreur
470 Erreur
471 Erreur
472 Erreur

In [107]:
df.head()

Empty DataFrame
Columns: []
Index: []

In [108]:
try:
    driver.quit()
except:
    pass

In [109]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

driver.maximize_window()

print("Driver relancé")

Driver relancé

In [110]:
driver.get(liens[0])

InvalidArgumentException: Message: invalid argument: 'url' must be a string
  (Session info: chrome=150.0.7871.127)
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f319594d]
	chromedriver!(No symbol) [0x7ff6f323eeea]
	chromedriver!(No symbol) [0x7ff6f32191ca]
	chromedriver!(No symbol) [0x7ff6f323e01b]
	chromedriver!(No symbol) [0x7ff6f31e2e6c]
	chromedriver!(No symbol) [0x7ff6f31e3d93]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!GetHandleVerifier [0x7ff6f364ab74+1f3f4]
	chromedriver!GetHandleVerifier [0x7ff6f364ad04+1f584]
	chromedriver!GetHandleVerifier [0x7ff6f362d9d7+2257]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

In [111]:
print(type(liens))
print(type(liens[0]))
print(liens[0])

<class 'list'>
<class 'selenium.webdriver.remote.webelement.WebElement'>
<selenium.webdriver.remote.webelement.WebElement (session="4d0f22851b3ba26c821d9c372bcf9b57", element="f.3970095B3F1C1A0385B388B1103D8B43.d.F6CCC175CD85DB95A8362CFE8310E77D.e.7160")>

In [112]:
url = liens[0].get_attribute("href")
print(url)

driver.get(url)

InvalidSessionIdException: Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

In [113]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

In [114]:
driver.get("https://www.moteur.ma/fr/voiture/occasion/")

In [115]:
from selenium.webdriver.common.by import By
import time

time.sleep(5)

liens = []

elements = driver.find_elements(By.CSS_SELECTOR, "a[href*='detail-annonce']")

for e in elements:
    href = e.get_attribute("href")
    if href and href not in liens:
        liens.append(href)

print("Nombre de liens :", len(liens))
print(liens[:5])

Nombre de liens : 0
[]

In [116]:
driver.get(liens[0])

IndexError: list index out of range

In [117]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

driver = webdriver.Chrome()

In [118]:
driver.get("https://www.moteur.ma/fr/voiture/occasion/")
time.sleep(5)

In [119]:
liens = driver.find_elements(By.CSS_SELECTOR, "a[href*='detail-annonce']")

print(len(liens))

0

In [120]:
url = liens[0].get_attribute("href")
print(url)

IndexError: list index out of range

In [121]:
driver.current_url

'https://www.moteur.ma/fr/neuf/'

In [122]:
driver.get("https://www.moteur.ma/fr/voiture/occasion/")

In [123]:
import time
time.sleep(5)

In [124]:
from selenium.webdriver.common.by import By

liens = driver.find_elements(By.TAG_NAME, "a")
print(len(liens))

474

In [125]:
print(driver.current_url)

https://www.moteur.ma/fr/neuf/

In [126]:
driver.title

"Guide d'achat des véhicules neufs au Maroc| Moteur.ma"

In [127]:
driver.get("https://www.moteur.ma/fr/voiture/occasion/")

In [128]:
import time
time.sleep(5)

In [129]:
print(driver.title)

Guide d'achat des véhicules neufs au Maroc| Moteur.ma

In [130]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.maximize_window()

print("Chrome lancé")

Chrome lancé

In [131]:
driver.get("https://www.moteur.ma/fr/voiture/occasion/")

import time
time.sleep(5)

print(driver.title)

Guide d'achat des véhicules neufs au Maroc| Moteur.ma

In [132]:
driver.get("https://www.moteur.ma/fr/voiture/occasion/")

In [133]:
driver.get("https://www.moteur.ma/fr/voiture/occasion/")
print(driver.current_url)
print(driver.title)

https://www.moteur.ma/fr/neuf/
Guide d'achat des véhicules neufs au Maroc| Moteur.ma

In [134]:
driver.delete_all_cookies()

driver.get("https://www.moteur.ma/")
print(driver.current_url)

driver.get("https://www.moteur.ma/fr/voiture/occasion/")
print(driver.current_url)
print(driver.title)

https://www.moteur.ma/
https://www.moteur.ma/fr/neuf/
Guide d'achat des véhicules neufs au Maroc| Moteur.ma

In [135]:
driver.quit()

In [136]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

options = webdriver.ChromeOptions()

# ouvrir une nouvelle session totalement propre
options.add_argument("--incognito")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

In [137]:
driver.get("https://www.moteur.ma/fr/voiture/occasion/")

print(driver.current_url)
print(driver.title)

https://www.moteur.ma/fr/neuf/
Guide d'achat des véhicules neufs au Maroc| Moteur.ma

In [138]:
from selenium.webdriver.common.by import By

liens = driver.find_elements(By.TAG_NAME, "a")

print("Nombre de liens :", len(liens))

Nombre de liens : 474

In [139]:
for i in range(min(30, len(liens))):
    href = liens[i].get_attribute("href")
    texte = liens[i].text
    print(i, "=>", texte, "||", href)

0 =>  || None
1 =>  || https://www.moteur.ma/
2 =>  || https://www.moteur.ma/
3 =>  || https://www.moteur.ma/fr/neuf/voiture/
4 =>  || https://www.moteur.ma/
5 =>  || https://www.moteur.ma/
6 =>  || https://www.moteur.ma/
7 => Neuf || https://www.moteur.ma/fr/neuf/
8 =>  || https://www.moteur.ma/fr/neuf/
9 =>  || https://www.moteur.ma/fr/neuf/voiture/
10 =>  || https://www.moteur.ma/fr/neuf/voiture/
11 =>  || https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/
12 =>  || https://www.moteur.ma/fr/neuf/rubrique/
13 =>  || https://www.moteur.ma/fr/neuf/comparatif-voiture-neuf/
14 =>  || https://www.moteur.ma/fr/neuf/moto/
15 =>  || https://www.moteur.ma/fr/neuf/moto/
16 =>  || https://www.moteur.ma/fr/neuf/promotion-moto-neuve-maroc/
17 =>  || https://www.moteur.ma/fr/neuf/camion/
18 =>  || https://www.moteur.ma/fr/neuf/camion/
19 => Promotion || https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/
20 =>  || https://www.moteur.ma/fr/neuf/promotion-voiture-neuve-maroc/
21 =>  || https://www.moteur.ma/fr/neuf/rubrique/
22 => Émissions || https://www.moteur.ma/fr/guide-achat/
23 =>  || https://www.moteur.ma/fr/guide-achat/ajinjerbo/
24 =>  || https://www.moteur.ma/fr/guide-achat/parlons-auto/
25 =>  || https://www.moteur.ma/fr/guide-achat/zoom-auto/
26 =>  || https://www.moteur.ma/fr/guide-achat/live-events/
27 => Actualités || https://www.moteur.ma/fr/guide-achat/actualite/
28 =>  || https://www.moteur.ma/fr/guide-achat/actualite/
29 =>  || https://www.moteur.ma/fr/forum/

In [140]:
for lien in liens:
    href = lien.get_attribute("href")
    if href and ("occasion" in href.lower() or "achat-voiture-occasion" in href.lower()):
        print(href)

https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
https://www.moteur.ma/fr/voiture/vendez-voiture-occasion/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
https://www.moteur.ma/fr/voiture/prix-voiture-occasion-maroc/?src=menu
https://www.moteur.ma/fr/moto/achat-moto-occasion/
https://www.moteur.ma/fr/moto/vendez-moto-occasion/
https://www.moteur.ma/fr/moto/achat-moto-occasion/
https://www.moteur.ma/fr/camion/achat-camion-occasion/
https://www.moteur.ma/fr/camion/vendez-camion-occasion/
https://www.moteur.ma/fr/camion/achat-camion-occasion/
https://www.moteur.ma/fr/voiture/concessionnaire-voiture-occasion/
https://www.moteur.ma/fr/voiture/concessionnaire-voiture-occasion/
https://www.moteur.ma/fr/voiture/vendez-voiture-occasion/
https://www.moteur.ma/fr/voiture/vendez-voiture-occasion/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/volkswagen/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/mercedes-benz/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/renault/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/peugeot/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/dacia/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/hyundai/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/audi/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/ford/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/bmw/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/fiat/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/kia/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/land-rover/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/citroen/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/toyota/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/opel/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/nissan/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/jeep/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/skoda/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/seat/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/porsche/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/volvo/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/alfa-romeo/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/honda/
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/marque/jaguar/
https://www.moteur.ma/fr/voiture/concessionnaire-voiture-occasion/
https://www.moteur.ma/fr/voiture/prix-voiture-occasion-maroc/?src=homepage

In [141]:
for lien in liens:
    href = lien.get_attribute("href")
    if href == "https://www.moteur.ma/fr/voiture/achat-voiture-occasion/":
        lien.click()
        break

print(driver.current_url)
print(driver.title)

https://www.moteur.ma/fr/moto/achat-moto-occasion/
Moto occasion| Moteur.ma

In [142]:
from selenium.webdriver.common.by import By

liens = driver.find_elements(By.TAG_NAME, "a")

for lien in liens:
    href = lien.get_attribute("href")
    if href == "https://www.moteur.ma/fr/voiture/achat-voiture-occasion/":
        driver.execute_script("arguments[0].click();", lien)
        break

print(driver.current_url)
print(driver.title)

https://www.moteur.ma/fr/voiture/achat-voiture-occasion/
Voiture occasion| Moteur.ma

In [143]:
from selenium.webdriver.common.by import By

liens = driver.find_elements(
    By.CSS_SELECTOR,
    "a[href*='/detail-annonce/']"
)

print("Nombre d'annonces :", len(liens))

Nombre d'annonces : 90

In [144]:
urls = [a.get_attribute("href") for a in liens]

print("Nombre d'URLs :", len(urls))
print(urls[:5])

Nombre d'URLs : 90
['https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509289/citroen-berlingo.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509289/citroen-berlingo.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509289/citroen-berlingo.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509288/kia-picanto.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509288/kia-picanto.html']

In [145]:
urls = list(dict.fromkeys(urls))

print("Nombre d'URLs uniques :", len(urls))
print(urls[:5])

Nombre d'URLs uniques : 30
['https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509289/citroen-berlingo.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509288/kia-picanto.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509287/bmw-serie-3.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509286/kia-picanto.html', 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509285/cupra-formentor.html']

In [146]:
from selenium.webdriver.common.by import By
import pandas as pd
import re
import time

donnees = []

for i, url in enumerate(urls):

    print(f"{i+1}/{len(urls)}")

    try:
        driver.get(url)
        time.sleep(2)

        texte = driver.find_element(By.TAG_NAME, "body").text

        # Prix
        prix = ""
        m = re.search(r"Comparer\s*×.*?([\d\s,]+)\s*MAD", texte, re.S)
        if m:
            prix = m.group(1).strip().replace(" ", "")

        if prix == "":
            m = re.search(r"Prix sur demande", texte)
            if m:
                prix = "Prix sur demande"

        # Année
        annee = ""
        m = re.search(r"Année:\s*(\d{4})", texte)
        if m:
            annee = m.group(1)

        # Kilométrage
        km = ""
        m = re.search(r"Kilométrage:\s*([\d\s,]+)", texte)
        if m:
            km = m.group(1).strip().replace(" ", "")

        # Carburant
        carburant = ""
        m = re.search(r"Carburant:\s*([^\n]+)", texte)
        if m:
            carburant = m.group(1).strip()

        # Transmission
        transmission = ""
        m = re.search(r"Transmission:\s*([^\n]+)", texte)
        if m:
            transmission = m.group(1).strip()

        # Marque
        marque = ""
        m = re.search(r"Marque:\s*([^\n]+)", texte)
        if m:
            marque = m.group(1).strip()

        # Modèle
        modele = ""
        m = re.search(r"Modèle:\s*([^\n]+)", texte)
        if m:
            modele = m.group(1).strip()

        donnees.append({
            "Prix": prix,
            "Marque": marque,
            "Modele": modele,
            "Annee": annee,
            "Kilometrage": km,
            "Carburant": carburant,
            "Transmission": transmission,
            "URL": url
        })

    except Exception as e:
        print("Erreur :", e)

1/30
2/30
3/30
4/30
5/30
6/30
7/30
8/30
9/30
10/30
11/30
12/30
13/30
14/30
15/30
16/30
17/30
18/30
19/30
20/30
21/30
22/30
23/30
24/30
25/30
26/30
Erreur : HTTPConnectionPool(host='localhost', port=64309): Read timed out. (read timeout=120)
27/30
28/30
29/30
30/30

In [147]:
df = pd.DataFrame(donnees)

print(df.head())
print("Nombre de voitures :", len(df))

               Prix                    Marque     Modele Annee Kilometrage  \
0  Prix sur demande  Citroën Modèle: Berlingo   Berlingo  2021         250
1  Prix sur demande       Kia Modèle: Picanto    Picanto  2006           0
2  Prix sur demande       BMW Modèle: Série 3    Série 3  2012       1,000
3  Prix sur demande       Kia Modèle: Picanto    Picanto  2006         888
4  Prix sur demande   Cupra Modèle: Formentor  Formentor  2023         108

                          Carburant Transmission  \
0     Diesel Transmission: Manuelle     Manuelle
1    Essence Transmission: Manuelle     Manuelle
2     Diesel Transmission: Manuelle     Manuelle
3    Essence Transmission: Manuelle     Manuelle
4  Diesel Transmission: Automatique  Automatique

                                                 URL
0  https://www.moteur.ma/fr/voiture/achat-voiture...
1  https://www.moteur.ma/fr/voiture/achat-voiture...
2  https://www.moteur.ma/fr/voiture/achat-voiture...
3  https://www.moteur.ma/fr/voiture/achat-voiture...
4  https://www.moteur.ma/fr/voiture/achat-voiture...
Nombre de voitures : 29

In [148]:
import re

# Marque
df["Marque"] = df["Marque"].str.replace("Marque:", "", regex=False)
df["Marque"] = df["Marque"].str.split("Modèle:").str[0].str.strip()

# Modèle
df["Modele"] = df["Modele"].str.replace("Modèle:", "", regex=False).str.strip()

# Carburant
df["Carburant"] = df["Carburant"].str.split("Transmission").str[0].str.strip()

# Transmission
df["Transmission"] = df["Transmission"].str.replace("Transmission:", "", regex=False).str.strip()

# Prix
def nettoyer_prix(x):
    if pd.isna(x):
        return None
    if "Prix sur demande" in x:
        return None
    nums = re.findall(r"\d+", x)
    if len(nums) >= 2:
        return "".join(nums[-2:])
    elif len(nums) == 1:
        return nums[0]
    return None

df["Prix"] = df["Prix"].apply(nettoyer_prix)

In [149]:
df.head()

,Prix,Marque,Modele,Annee,Kilometrage,Carburant,Transmission,URL
0,None,Citroën,Berlingo,2021,250,Diesel,Manuelle,https://www.moteur.ma/fr/voiture/achat-voiture...
1,None,Kia,Picanto,2006,0,Essence,Manuelle,https://www.moteur.ma/fr/voiture/achat-voiture...
2,None,BMW,Série 3,2012,"1,000",Diesel,Manuelle,https://www.moteur.ma/fr/voiture/achat-voiture...
3,None,Kia,Picanto,2006,888,Essence,Manuelle,https://www.moteur.ma/fr/voiture/achat-voiture...
4,None,Cupra,Formentor,2023,108,Diesel,Automatique,https://www.moteur.ma/fr/voiture/achat-voiture...

In [150]:
driver.get(df["URL"][0])

import time
time.sleep(3)

print(driver.find_element("tag name", "body").text)

Neuf
Promotion
Émissions
Actualités
Occasion
Se connecter
Vendez Votre Voiture
0
العربية
Offres du moment
DFSK E5
magnite
chery tiggo 7 pro
dacia sandero stepway
opel astra
opel corsa
opel grandland
opel frontera
opel mokka
Seat Leon FR
Seat ibiza
Accueil
Occasion
Acheter une voiture d'occasion
Citroën Berlingo
Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Citroën Berlingo
Appeler pour le prix
Voiture
Jul 18, 2026
5 vues
Informations Véhicule
Marque: Citroën Modèle: Berlingo
Année: 2021 Kilométrage: 250 km
Carburant: Diesel Transmission: Manuelle
Carrosserie: N/A Couleur: N/A
Nombre de portes 5 Puissance fiscale 7
Spécifications rapides
سيارة للبيع ستروين بيرلنكو مليحة صباغة الأولى مديل 2021كلمتر 250 لبغها يتصل نيشان ممكن وربريز كاينة في سلا
Caractéristiques & Options
Premier propriétaire Véhicule préparé
Historique d'accidents Importation neuve
Statut de douane N/A
options
État du véhicule
ABS
Climatisation
Airbags
Fermeture centralisée
Vitres électriques
ESP
Navigation GPS
Limiteur de vitesse
CD / MP3 / Bluetooth
Annonces Similaires
Citroën Jumper
200,000 MAD
il y a 1 heure
Citroën C5
48,000 MAD
il y a 2 heures
Citroën Berlingo
73,000 MAD
il y a 3 heures
Citroën C4
50,000 MAD
il y a 3 heures
Citroën C-Elysée
112,000 MAD
il y a 3 heures
Dernières annonces premium
Premium
Volkswagen Arteon
Agadir 2019
269,000 MAD
Premium
Toyota Verso
Rabat 2012
95,000 MAD
Premium
Mercedes-Benz Classe A
Mohammédia 2016
270,000 MAD
Publié par
Simo Simo
Vendeur depuis Jul 2026
Informations Contact
Appeler maintenant
Prix Citroën Berlingo neuve maroc
Promo
CITROëN Berlingo
À partir de
195 900 Dhs
3 Versions
Prix promotionnels du moment
Kia
EV5
À partir de
493 900 Dhs
Audi
Q7
À partir de
720 000 Dhs
Peugeot
308
À partir de
284 900 Dhs
Kia
Tasman
À partir de
320 700 Dhs
Citroën
C4
À partir de
217 900 Dhs
Citroën
Berlingo
À partir de
195 900 Dhs
Audi
A3 Sportback
À partir de
351 000 Dhs
Dernières voitures neuves
NOUVEAU
Citroën
C3
PLUS PACK ESSENCE BVM
173 900 Dhs
2026 · Citadine
NOUVEAU
Fiat
Grizzly
Fastback BEV
Prix sur demande
2026 · SUV et 4x4
NOUVEAU
Fiat
Grizzly
Fastback 1.2 Turbo Hybrid 48V
Prix sur demande
2026 · SUV et 4x4
Comparez les voitures neuves au Maroc
Analysez les prix, motorisations et équipements pour faire le meilleur choix.
شيري
تيجو 7 برو
PHEV NEW TIGGO 7 PRO LUXURY
دفسك
إي 5
1.5 l 277 PHEV AT M1
شيري VS دفسك
كوبرا
تيرامار
1,5 e-hybrid 204 DSG OCEAN ED...
سوإيست
إس 07
soul ease summit 1.5 TD 7 DCT
كوبرا VS سوإيست
شكودا
أوكتافيا
2.0 TDI 150 DSG Luxury
فولكس فاجن
تايغو
1.0 TSI 116 DSG Style
شكودا VS فولكس فاجن
Toutes les comparaisons neuves
GUIDES PRIX VOITURES NEUVES AU MAROC
Voitures neuves Maroc
Voitures hybrides Maroc
Voitures électriques neuves Maroc
Voitures neuves moins de 200 000 DH
SUV neufs Maroc
Voitures Diesel neuves
Voitures essence maroc
Voitures automatiques Maroc
Voitures familiales neuves
Voitures neuves au Maroc
Zeekr neuve Maroc
BYD neuve Maroc
Tata neuve Maroc
Ford neuve Maroc
Hyundai neuve Maroc
Ferrari neuve Maroc
DFSK neuve Maroc
Omoda neuve Maroc
Seres neuve Maroc
Toyota neuve Maroc
Isuzu neuve Maroc
Volvo neuve Maroc
Seat neuve Maroc
Alfa Romeo neuve Maroc
Mahindra neuve Maroc
Jaguar neuve Maroc
Peugeot neuve Maroc
Leapmotor neuve Maroc
Foton neuve Maroc
XPENG neuve Maroc
Jetour neuve Maroc
Fiat neuve Maroc
BMW neuve Maroc
Jaecoo neuve Maroc
KGM neuve Maroc
Modèles neufs populaires
BMW X5 neuve Maroc
BMW X3 neuve Maroc
Citroën Berlingo neuve Maroc
Citroën C5 Aircross neuve Maroc
Dacia Duster neuve Maroc
Dacia Bigster neuve Maroc
Ford Kuga neuve Maroc
Ford Territory neuve Maroc
Hyundai Kona neuve Maroc
Hyundai Santa Fe neuve Maroc
Kia EV5 neuve Maroc
Kia Sportage neuve Maroc
Mercedes-Benz Classe GLE neuve Maroc
Mercedes-Benz EQE neuve Maroc
Opel Mokka neuve Maroc
Opel Frontera neuve Maroc
Peugeot 2008 neuve Maroc
Peugeot 208 neuve Maroc
Renault 5 E-Tech neuve Maroc
Renault Master neuve Maroc
Toyota Yaris neuve Maroc
Toyota RAV-4 neuve Maroc
Volkswagen Tiguan neuve Maroc
Volkswagen Golf 8 neuve Maroc
Voitures occasion Maroc
Volkswagen occasion Maroc
Mercedes-Benz occasion Maroc
Renault occasion Maroc
Peugeot occasion Maroc
Dacia occasion Maroc
Hyundai occasion Maroc
Audi occasion Maroc
Ford occasion Maroc
BMW occasion Maroc
Fiat occasion Maroc
Kia occasion Maroc
Land Rover occasion Maroc
Citroën occasion Maroc
Toyota occasion Maroc
Opel occasion Maroc
Nissan occasion Maroc
Jeep occasion Maroc
Skoda occasion Maroc
Seat occasion Maroc
Porsche occasion Maroc
Volvo occasion Maroc
Alfa Romeo occasion Maroc
Honda occasion Maroc
Jaguar occasion Maroc
A propos
Accueil
Qui sommes-nous?
Offres Premium
Offres Premium Pro
Votre publicité sur MOTEUR.MA
Showrooms Pro
Dernières promotions 2026
La Comparaison des voitures neuves
Demander le prix de votre voiture
Service Bi3 lia
Les emissions
Actualités Auto
Forum d'aide automobile
Notre réseau de partenaires
Conditions générales d'utilisation
Conditions générales de vente
Contactez-nous
Ils parlent de nous - Presse
Plan du site
بالعــربيـة
© 2009-2026 MOTEUR.ma : Guide d'achat des voitures neuves et d'occasion au Maroc
Conformément à la loi 09-08, vous disposez d'un droit d'accès, de rectification et d'opposition au traitement de vos données personnelles. Ce traitement a été autorisé par la CNDP sous le numéro D-W-219/2017
Le site MOTEUR.ma ne joue que le rôle d'intermédiaire entre acheteurs et vendeurs. Nous n'intervenons pas dans les transactions d'achat et de vente. En conséquence, ne peut être tenu responsable de tous problèmes survenus après le déroulement des transactions entre les deux parties.

In [151]:
from selenium.webdriver.common.by import By

prixs = driver.find_elements(By.XPATH, "//*[contains(text(),'MAD')]")

for p in prixs:
    print(p.text)

200,000 MAD
48,000 MAD
73,000 MAD
50,000 MAD
112,000 MAD





269,000 MAD
95,000 MAD
270,000 MAD

In [152]:
from selenium.webdriver.common.by import By
import re

prix = None

try:
    prixs = driver.find_elements(By.XPATH, "//*[contains(text(),'MAD')]")

    for p in prixs:
        texte = p.text.strip()

        if re.search(r"\d[\d,]*\s*MAD", texte):
            prix = re.search(r"\d[\d,]*", texte).group()
            break

except:
    prix = None

In [153]:
voitures.append({
    "Prix": prix,
    "Marque": marque,
    "Modele": modele,
    "Annee": annee,
    "Kilometrage": kilometrage,
    "Carburant": carburant,
    "Transmission": transmission,
    "URL": url
})

NameError: name 'voitures' is not defined

In [154]:
df = pd.DataFrame(voitures)
df.head()

NameError: name 'voitures' is not defined

In [155]:
from selenium.webdriver.common.by import By

elements = driver.find_elements(By.XPATH, "//*")

for e in elements:
    txt = e.text.strip()
    if "200,000 MAD" in txt:
        print(e.tag_name, e.get_attribute("class"))

html no-js
body ltr
div horizontalMenucontainer
section sptb
div container
div row
div col-xl-8 col-lg-8 col-md-12
div row
div col-12 col-xl-6 col-lg-6 col-md-6
div card
div card-body p-0
ul list-unstyled
li d-flex gap-3 p-3 border-bottom
div flex-grow-1
p text-primary font-weight-bold mb-1

In [156]:
print(df.head())
print(df.info())

   Prix   Marque     Modele Annee Kilometrage Carburant Transmission  \
0  None  Citroën   Berlingo  2021         250    Diesel     Manuelle
1  None      Kia    Picanto  2006           0   Essence     Manuelle
2  None      BMW    Série 3  2012       1,000    Diesel     Manuelle
3  None      Kia    Picanto  2006         888   Essence     Manuelle
4  None    Cupra  Formentor  2023         108    Diesel  Automatique

                                                 URL
0  https://www.moteur.ma/fr/voiture/achat-voiture...
1  https://www.moteur.ma/fr/voiture/achat-voiture...
2  https://www.moteur.ma/fr/voiture/achat-voiture...
3  https://www.moteur.ma/fr/voiture/achat-voiture...
4  https://www.moteur.ma/fr/voiture/achat-voiture...
<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Prix          0 non-null      object
 1   Marque        29 non-null     object
 2   Modele        29 non-null     str
 3   Annee         29 non-null     str
 4   Kilometrage   29 non-null     str
 5   Carburant     29 non-null     object
 6   Transmission  29 non-null     str
 7   URL           29 non-null     str
dtypes: object(3), str(5)
memory usage: 1.9+ KB
None

In [157]:
from selenium.webdriver.common.by import By

driver.get(df["URL"][0])

import time
time.sleep(3)

elements = driver.find_elements(By.XPATH, "//*[contains(text(),'MAD')]")

print("Nombre :", len(elements))

for i, e in enumerate(elements):
    print("="*30)
    print(i)
    print("Texte :", e.text)
    print("Tag :", e.tag_name)
    print("Classe :", e.get_attribute("class"))

Nombre : 23
==============================
0
Texte : 105,000 MAD
Tag : p
Classe : text-primary font-weight-bold mb-1
==============================
1
Texte : 200,000 MAD
Tag : p
Classe : text-primary font-weight-bold mb-1
==============================
2
Texte : 48,000 MAD
Tag : p
Classe : text-primary font-weight-bold mb-1
==============================
3
Texte : 73,000 MAD
Tag : p
Classe : text-primary font-weight-bold mb-1
==============================
4
Texte : 50,000 MAD
Tag : p
Classe : text-primary font-weight-bold mb-1
==============================
5
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
6
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
7
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
8
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
9
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
10
Texte : 135,000 MAD
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
11
Texte : 79,000 MAD
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
12
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
13
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
14
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
15
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
16
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
17
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
18
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
19
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
20
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
21
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0
==============================
22
Texte :
Tag : h4
Classe : text-primary font-weight-bold pb-2 my-0

In [158]:
prices = []

for e in elements:
    if e.text.strip() != "":
        prices.append(e.text.strip())

print("Nombre de prix :", len(prices))

for p in prices:
    print(p)

Nombre de prix : 7
105,000 MAD
200,000 MAD
48,000 MAD
73,000 MAD
50,000 MAD
135,000 MAD
79,000 MAD

In [159]:
prices = []

for e in elements:
    if e.text.strip() != "":
        prices.append(e.text.strip())

print(prices)

['105,000 MAD', '200,000 MAD', '48,000 MAD', '73,000 MAD', '50,000 MAD', '135,000 MAD', '79,000 MAD']

In [160]:
e = elements[0]
print(e.find_element(By.XPATH, "..").get_attribute("outerHTML"))

<div class="flex-grow-1">
                                            <a href="https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509315/citroen-c5.html" class="text-dark font-weight-semibold">
                                                Citroën C5
                                            </a>

                                            <p class="text-primary font-weight-bold mb-1">
                                                                                                    105,000 MAD
                                                                                            </p>

                                            <small class="text-muted">il y a 2 minutes</small>
                                        </div>

In [161]:
annonces = driver.find_elements(By.CLASS_NAME, "flex-grow-1")

print("Nombre annonces :", len(annonces))

Nombre annonces : 17

In [162]:
for i, annonce in enumerate(annonces[:5]):
    print("="*40)
    
    titre = annonce.find_element(By.TAG_NAME, "a").text
    url = annonce.find_element(By.TAG_NAME, "a").get_attribute("href")
    
    prix = annonce.find_element(By.TAG_NAME, "p").text
    
    print("Titre :", titre)
    print("Prix :", prix)
    print("URL :", url)

========================================

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"a"}
  (Session info: chrome=150.0.7871.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6f3640d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff6f3640d80+15600]
	chromedriver!(No symbol) [0x7ff6f319594d]
	chromedriver!(No symbol) [0x7ff6f31f08e9]
	chromedriver!(No symbol) [0x7ff6f31f0bec]
	chromedriver!(No symbol) [0x7ff6f31e476c]
	chromedriver!(No symbol) [0x7ff6f31e4616]
	chromedriver!(No symbol) [0x7ff6f323e01b]
	chromedriver!(No symbol) [0x7ff6f31e2e6c]
	chromedriver!(No symbol) [0x7ff6f31e3d93]
	chromedriver!GetHandleVerifier [0x7ff6f3c26431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff6f3c20a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff6f3c45865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff6f365dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff6f366661c+3ae9c]
	chromedriver!GetHandleVerifier [0x7ff6f364ab74+1f3f4]
	chromedriver!GetHandleVerifier [0x7ff6f364ad04+1f584]
	chromedriver!GetHandleVerifier [0x7ff6f362d9d7+2257]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

In [163]:
print(len(annonces))

17

In [164]:
data = []

for annonce in annonces:
    try:
        titre = annonce.find_element(By.TAG_NAME, "a").text
        url = annonce.find_element(By.TAG_NAME, "a").get_attribute("href")
        prix = annonce.find_element(By.TAG_NAME, "p").text

        data.append({
            "titre": titre,
            "prix": prix,
            "url": url
        })

    except:
        pass

print("Annonces récupérées :", len(data))

for d in data[:5]:
    print(d)

Annonces récupérées : 5
{'titre': 'Citroën C5', 'prix': '105,000 MAD', 'url': 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509315/citroen-c5.html'}
{'titre': 'Citroën Jumper', 'prix': '200,000 MAD', 'url': 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509203/citroen-jumper.html'}
{'titre': 'Citroën C5', 'prix': '48,000 MAD', 'url': 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509175/citroen-c5.html'}
{'titre': 'Citroën Berlingo', 'prix': '73,000 MAD', 'url': 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509129/citroen-berlingo.html'}
{'titre': 'Citroën C4', 'prix': '50,000 MAD', 'url': 'https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/509108/citroen-c4.html'}

In [165]:
df_annonces = pd.DataFrame(data)

In [166]:
import pandas as pd

df_annonces = pd.DataFrame(data)

df_annonces

,titre,prix,url
0,Citroën C5,"105,000 MAD",https://www.moteur.ma/fr/voiture/achat-voiture...
1,Citroën Jumper,"200,000 MAD",https://www.moteur.ma/fr/voiture/achat-voiture...
2,Citroën C5,"48,000 MAD",https://www.moteur.ma/fr/voiture/achat-voiture...
3,Citroën Berlingo,"73,000 MAD",https://www.moteur.ma/fr/voiture/achat-voiture...
4,Citroën C4,"50,000 MAD",https://www.moteur.ma/fr/voiture/achat-voiture...

In [167]:
df_annonces["prix"] = (
    df_annonces["prix"]
    .str.replace(" MAD", "")
    .str.replace(",", "")
    .astype(int)
)

df_annonces

              titre    prix                                                url
0        Citroën C5  105000  https://www.moteur.ma/fr/voiture/achat-voiture...
1    Citroën Jumper  200000  https://www.moteur.ma/fr/voiture/achat-voiture...
2        Citroën C5   48000  https://www.moteur.ma/fr/voiture/achat-voiture...
3  Citroën Berlingo   73000  https://www.moteur.ma/fr/voiture/achat-voiture...
4        Citroën C4   50000  https://www.moteur.ma/fr/voiture/achat-voiture...

In [168]:
df_annonces

              titre    prix                                                url
0        Citroën C5  105000  https://www.moteur.ma/fr/voiture/achat-voiture...
1    Citroën Jumper  200000  https://www.moteur.ma/fr/voiture/achat-voiture...
2        Citroën C5   48000  https://www.moteur.ma/fr/voiture/achat-voiture...
3  Citroën Berlingo   73000  https://www.moteur.ma/fr/voiture/achat-voiture...
4        Citroën C4   50000  https://www.moteur.ma/fr/voiture/achat-voiture...

In [169]:
url = df_annonces["url"][0]

driver.get(url)

import time
time.sleep(3)

In [170]:
texte = driver.find_element(By.TAG_NAME, "body").text

print(texte[:2000])

Neuf
Promotion
Émissions
Actualités
Occasion
Se connecter
Vendez Votre Voiture
0
العربية
Offres du moment
DFSK E5
magnite
chery tiggo 7 pro
dacia sandero stepway
opel astra
opel corsa
opel grandland
opel frontera
opel mokka
Seat Leon FR
Seat ibiza
Accueil
Occasion
Acheter une voiture d'occasion
Citroën C5
Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata

In [171]:
for url in df_annonces["url"]:
    driver.get(url)
    récupérer détails
    ajouter au dataset

SyntaxError: invalid syntax (1639014478.py, line 3)

In [172]:
url = df_annonces["url"][0]

driver.get(url)

import time
time.sleep(3)

In [173]:
texte = driver.find_element(By.TAG_NAME, "body").text

print(texte[:2000])

Neuf
Promotion
Émissions
Actualités
Occasion
Se connecter
Vendez Votre Voiture
0
العربية
Offres du moment
DFSK E5
magnite
chery tiggo 7 pro
dacia sandero stepway
opel astra
opel corsa
opel grandland
opel frontera
opel mokka
Seat Leon FR
Seat ibiza
Accueil
Occasion
Acheter une voiture d'occasion
Citroën C5
Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata

In [174]:
html = driver.page_source

for mot in ["Kilométrage", "km", "Diesel", "Essence", "Année", "2018"]:
    print(mot, mot in html)

Kilométrage True
km True
Diesel True
Essence True
Année True
2018 True

In [175]:
elements_km = driver.find_elements(By.XPATH, "//*[contains(text(),'km')]")

print("Nombre :", len(elements_km))

for e in elements_km[:10]:
    print("================")
    print(e.text)
    print(e.tag_name)
    print(e.get_attribute("class"))

Nombre : 2
================
230,000 km
td

================
À vendre Citroën C5 Diesel Automatique de Décembre 2013 en excellent état. - Kilométrage : 230 000 km - Boîte de vitesses : Automatique - Carburant : Diesel - Puissance fiscale : 8 CV Contactez-moi pour plus d'informations.
p

In [176]:
elements = driver.find_elements(By.XPATH, "//*[contains(text(),'Diesel') or contains(text(),'Essence') or contains(text(),'km') or contains(text(),'201')]")

print("Nombre :", len(elements))

for e in elements[:20]:
    print("================")
    print(e.text)
    print(e.tag_name)
    print(e.get_attribute("class"))

Nombre : 9
================

title

================

script

================
2014
td

================
230,000 km
td

================
Diesel
td

================
À vendre Citroën C5 Diesel Automatique de Décembre 2013 en excellent état. - Kilométrage : 230 000 km - Boîte de vitesses : Automatique - Carburant : Diesel - Puissance fiscale : 8 CV Contactez-moi pour plus d'informations.
p

================
Voitures Diesel neuves
a

================
Conformément à la loi 09-08, vous disposez d'un droit d'accès, de rectification et d'opposition au traitement de vos données personnelles. Ce traitement a été autorisé par la CNDP sous le numéro D-W-219/2017
Le site MOTEUR.ma ne joue que le rôle d'intermédiaire entre acheteurs et vendeurs. Nous n'intervenons pas dans les transactions d'achat et de vente. En conséquence, ne peut être tenu responsable de tous problèmes survenus après le déroulement des transactions entre les deux parties.
p
mb-0 fs-12
================

script

In [177]:
def extraire_details(url):

    driver.get(url)
    time.sleep(2)

    details = {
        "annee": None,
        "kilometrage": None,
        "carburant": None,
        "boite": None
    }

    # récupérer les td
    tds = driver.find_elements(By.TAG_NAME, "td")

    valeurs = [td.text.strip() for td in tds if td.text.strip()]

    for v in valeurs:
        if v.isdigit() and len(v) == 4:
            details["annee"] = v

        elif "km" in v:
            details["kilometrage"] = v

        elif v in ["Diesel", "Essence", "Hybride", "Electrique"]:
            details["carburant"] = v

    # description
    texte = driver.find_element(By.TAG_NAME,"body").text

    if "Boîte de vitesses :" in texte:
        boite = texte.split("Boîte de vitesses :")[1].split("-")[0]
        details["boite"] = boite.strip()

    return details

In [178]:
test = extraire_details(df_annonces["url"][0])

print(test)

{'annee': '2014', 'kilometrage': '230,000 km', 'carburant': 'Diesel', 'boite': 'Automatique'}

In [179]:
resultats = []

for url in df_annonces["url"]:
    resultats.append(extraire_details(url))

resultats

[{'annee': '2014',
  'kilometrage': '230,000 km',
  'carburant': 'Diesel',
  'boite': 'Automatique'},
 {'annee': '2021',
  'kilometrage': '221,000 km',
  'carburant': 'Diesel',
  'boite': None},
 {'annee': '2003',
  'kilometrage': '80,000 km',
  'carburant': 'Diesel',
  'boite': None},
 {'annee': '2010',
  'kilometrage': '311 km',
  'carburant': 'Diesel',
  'boite': None},
 {'annee': '2006',
  'kilometrage': '25,000 km',
  'carburant': 'Diesel',
  'boite': None}]

In [180]:
df_final = pd.concat(
    [df_annonces, pd.DataFrame(resultats)],
    axis=1
)

df_final

,titre,prix,url,annee,kilometrage,carburant,boite
0,Citroën C5,105000,https://www.moteur.ma/fr/voiture/achat-voiture...,2014,"230,000 km",Diesel,Automatique
1,Citroën Jumper,200000,https://www.moteur.ma/fr/voiture/achat-voiture...,2021,"221,000 km",Diesel,NaN
2,Citroën C5,48000,https://www.moteur.ma/fr/voiture/achat-voiture...,2003,"80,000 km",Diesel,NaN
3,Citroën Berlingo,73000,https://www.moteur.ma/fr/voiture/achat-voiture...,2010,311 km,Diesel,NaN
4,Citroën C4,50000,https://www.moteur.ma/fr/voiture/achat-voiture...,2006,"25,000 km",Diesel,NaN

In [181]:
df_final["kilometrage"] = (
    df_final["kilometrage"]
    .str.replace(" km","")
    .str.replace(",","")
    .astype(int)
)

df_final

,titre,prix,url,annee,kilometrage,carburant,boite
0,Citroën C5,105000,https://www.moteur.ma/fr/voiture/achat-voiture...,2014,230000,Diesel,Automatique
1,Citroën Jumper,200000,https://www.moteur.ma/fr/voiture/achat-voiture...,2021,221000,Diesel,NaN
2,Citroën C5,48000,https://www.moteur.ma/fr/voiture/achat-voiture...,2003,80000,Diesel,NaN
3,Citroën Berlingo,73000,https://www.moteur.ma/fr/voiture/achat-voiture...,2010,311,Diesel,NaN
4,Citroën C4,50000,https://www.moteur.ma/fr/voiture/achat-voiture...,2006,25000,Diesel,NaN

In [182]:
if "Automatique" in texte:
    details["boite"] = "Automatique"

elif "Manuelle" in texte:
    details["boite"] = "Manuelle"

NameError: name 'details' is not defined

In [183]:
df_final["marque"] = df_final["titre"].str.split().str[0]

df_final["modele"] = df_final["titre"].str.split().str[1:].str.join(" ")

df_final

,titre,prix,url,annee,kilometrage,carburant,boite,marque,modele
0,Citroën C5,105000,https://www.moteur.ma/fr/voiture/achat-voiture...,2014,230000,Diesel,Automatique,Citroën,C5
1,Citroën Jumper,200000,https://www.moteur.ma/fr/voiture/achat-voiture...,2021,221000,Diesel,NaN,Citroën,Jumper
2,Citroën C5,48000,https://www.moteur.ma/fr/voiture/achat-voiture...,2003,80000,Diesel,NaN,Citroën,C5
3,Citroën Berlingo,73000,https://www.moteur.ma/fr/voiture/achat-voiture...,2010,311,Diesel,NaN,Citroën,Berlingo
4,Citroën C4,50000,https://www.moteur.ma/fr/voiture/achat-voiture...,2006,25000,Diesel,NaN,Citroën,C4

In [184]:
df_final.to_csv("dataset_voitures_maroc.csv", index=False, encoding="utf-8-sig")

In [185]:
df_final.shape

(5, 9)

In [186]:
%whos

Variable                 Type             Data/Info
---------------------------------------------------
BeautifulSoup            type             <class 'bs4.BeautifulSoup'>
By                       type             <class 'selenium.webdriver.common.by.By'>
ChromeDriverManager      type             <class 'webdriver_manager<...>ome.ChromeDriverManager'>
NoSuchElementException   type             <class 'selenium.common.e<...>.NoSuchElementException'>
Options                  ABCMeta          <class 'selenium.webdrive<...>.chrome.options.Options'>
Service                  ABCMeta          <class 'selenium.webdrive<...>.chrome.service.Service'>
TimeoutException         type             <class 'selenium.common.e<...>ptions.TimeoutException'>
annee                    str              2013
annonce                  WebElement       <selenium.webdriver.remot<...>A577F6A95351954.e.7265")>
annonces                 list             n=17
annonces_recup           list             n=57
carburant                str              Diesel Transmission: Manuelle
compteur                 int              4
d                        dict             n=3
data                     list             n=5
dataset                  list             n=46
df                       DataFrame        Shape: (29, 8)
df_annonces              DataFrame        Shape: (5, 3)
df_erreurs               DataFrame        Shape: (57, 7)
df_final                 DataFrame        Shape: (5, 9)
donnees                  list             n=29
driver                   WebDriver        <selenium.webdriver.chrom<...>5575e5f47bc628d6a55259")>
e                        WebElement       <selenium.webdriver.remot<...>15CBFB76562C6EF.e.7475")>
elements                 list             n=9
elements_km              list             n=2
erreurs                  list             n=57
erreurs_finales          list             n=0
erreurs_restantes        list             n=57
extraire_annonce         function         <function extraire_annonce at 0x000001F81A51D3A0>
extraire_details         function         <function extraire_details at 0x000001F83E016020>
href                     str              https://www.moteur.ma/fr/<...>e/achat-voiture-occasion/
html                     str              <html class="no-js" lang=<...>: none;"></iframe></html>
i                        int              0
kilometrage              str
km                       str              220
lien                     WebElement       <selenium.webdriver.remot<...>E941FBD085A97E7.e.1961")>
liens                    list             n=90
liens_annonces           list             n=0
liens_page2              list             n=30
ligne                    str              Le site MOTEUR.ma ne joue<...>s entre les deux parties.
lignes                   list             n=504
m                        Match            <re.Match object; span=(2<...>288), match='Modèle: A4'>
marque                   str              Audi Modèle: A4
marques                  list             n=11
modele                   str              A4
mot                      str              2018
nettoyer_prix            function         <function nettoyer_prix at 0x000001F83E198C20>
options                  Options          <selenium.webdriver.chrom<...>ct at 0x000001F83E0BE5D0>
p                        str              79,000 MAD
page                     int              10
pd                       module           <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
prices                   list             n=7
prix                     str              50,000 MAD
prix_elements            list             n=20
prixs                    list             n=25
re                       module           <module 're' from 'C:\\Us<...>3\\Lib\\re\\__init__.py'>
recuperer_liens_page     function         <function recuperer_liens<...>ge at 0x000001F83A5AACA0>
resultats                list             n=5
separer_marque           function         <function separer_marque at 0x000001F83A5A8680>
soup                     BeautifulSoup    <html class="no-js" dir="<...>: none;"></iframe></html>
specs                    list             n=0
test                     dict             n=4
text                     str              Volkswagen Golf 7 للبيع س<...>s entre les deux parties.
texte                    str              Neuf\nPromotion\nÉmission<...>s entre les deux parties.
texte_page               str              Neuf\nPromotion\nÉmission<...>s entre les deux parties.
time                     module           <module 'time' (built-in)>
titre                    str              Citroën C4
tous_les_liens           list             n=289
transmission             str              Manuelle
txt                      str
url                      str              https://www.moteur.ma/fr/<...>ce/509108/citroen-c4.html
url_test                 str              https://www.moteur.ma/fr/<...>22/volkswagen-golf-7.html
urls                     list             n=30
webdriver                module           <module 'selenium.webdriv<...>\webdriver\\__init__.py'>

In [187]:
df.head()

,Prix,Marque,Modele,Annee,Kilometrage,Carburant,Transmission,URL
0,None,Citroën,Berlingo,2021,250,Diesel,Manuelle,https://www.moteur.ma/fr/voiture/achat-voiture...
1,None,Kia,Picanto,2006,0,Essence,Manuelle,https://www.moteur.ma/fr/voiture/achat-voiture...
2,None,BMW,Série 3,2012,"1,000",Diesel,Manuelle,https://www.moteur.ma/fr/voiture/achat-voiture...
3,None,Kia,Picanto,2006,888,Essence,Manuelle,https://www.moteur.ma/fr/voiture/achat-voiture...
4,None,Cupra,Formentor,2023,108,Diesel,Automatique,https://www.moteur.ma/fr/voiture/achat-voiture...

In [188]:
df.columns

Index(['Prix', 'Marque', 'Modele', 'Annee', 'Kilometrage', 'Carburant',
       'Transmission', 'URL'],
      dtype='str')

In [189]:
df.to_csv(
    "dataset_voitures_maroc_complet.csv",
    index=False,
    encoding="utf-8-sig"
)

In [190]:
len(dataset)

46

In [191]:
dataset[:2]

[{'Titre': 'Peugeot 3008',
  'Annee': '2020',
  'Kilometrage': '65,000',
  'Carburant': 'Diesel',
  'Transmission': 'Automatique'},
 {'Titre': 'Dacia Logan',
  'Annee': '2022',
  'Kilometrage': '31,500',
  'Carburant': 'Diesel',
  'Transmission': 'Manuelle'}]

In [192]:
df_complet = pd.DataFrame(dataset)

df_complet.head()

           Titre Annee Kilometrage Carburant Transmission
0   Peugeot 3008  2020      65,000    Diesel  Automatique
1    Dacia Logan  2022      31,500    Diesel     Manuelle
2     Citroën C3  2018     126,000    Diesel     Manuelle
3     Volvo XC40  2024      24,000   Essence  Automatique
4  Dacia Sandero  2021      26,000   Essence     Manuelle

In [193]:
df_complet.shape

(46, 5)

In [194]:
df_complet.to_csv(
    "dataset_voitures_maroc.csv",
    index=False,
    encoding="utf-8-sig"
)

In [195]:
pd.read_csv("dataset_voitures_maroc.csv").head()

           Titre  Annee Kilometrage Carburant Transmission
0   Peugeot 3008   2020      65,000    Diesel  Automatique
1    Dacia Logan   2022      31,500    Diesel     Manuelle
2     Citroën C3   2018     126,000    Diesel     Manuelle
3     Volvo XC40   2024      24,000   Essence  Automatique
4  Dacia Sandero   2021      26,000   Essence     Manuelle

In [196]:
test = extraire_annonce(tous_les_liens[0])
print(test)

{'Titre': 'Toyota RAV-4', 'Annee': '2014', 'Kilometrage': '156,000', 'Carburant': 'Diesel', 'Transmission': 'Manuelle'}

In [ ]:
dataset_complet = []

for i, lien in enumerate(tous_les_liens):
    try:
        print("Annonce", i+1, "/", len(tous_les_liens))

        resultat = extraire_annonce(lien)

        if resultat:
            dataset_complet.append(resultat)

    except Exception as e:
        print("Erreur :", i, e)

print("Total récupéré :", len(dataset_complet))

Annonce 1 / 289
Annonce 2 / 289
Annonce 3 / 289
Annonce 4 / 289
Annonce 5 / 289
Annonce 6 / 289
Annonce 7 / 289
Annonce 8 / 289
Annonce 9 / 289
Annonce 10 / 289
Annonce 11 / 289
Annonce 12 / 289
Annonce 13 / 289
Annonce 14 / 289
Annonce 15 / 289
Annonce 16 / 289
Annonce 17 / 289
Annonce 18 / 289
Annonce 19 / 289
Annonce 20 / 289
Annonce 21 / 289
Annonce 22 / 289
Annonce 23 / 289
Annonce 24 / 289
Annonce 25 / 289
Annonce 26 / 289
Annonce 27 / 289
Annonce 28 / 289
Annonce 29 / 289
Annonce 30 / 289
Annonce 31 / 289
Annonce 32 / 289
Annonce 33 / 289
Annonce 34 / 289
Annonce 35 / 289
Annonce 36 / 289
Annonce 37 / 289
Annonce 38 / 289
Annonce 39 / 289
Annonce 40 / 289
Erreur : 39 HTTPConnectionPool(host='localhost', port=64309): Read timed out. (read timeout=120)
Annonce 41 / 289
Erreur : 40 HTTPConnectionPool(host='localhost', port=64309): Read timed out. (read timeout=120)
Annonce 42 / 289
Erreur : 41 HTTPConnectionPool(host='localhost', port=64309): Read timed out. (read timeout=120)
Annonce 43 / 289
Erreur : 42 HTTPConnectionPool(host='localhost', port=64309): Read timed out. (read timeout=120)
Annonce 44 / 289
Erreur : 43 HTTPConnectionPool(host='localhost', port=64309): Read timed out. (read timeout=120)
Annonce 45 / 289

In [ ]:
df_complet = pd.DataFrame(dataset_complet)

df_complet.shape

In [ ]:
df_complet.to_csv(
    "dataset_voitures_maroc_final.csv",
    index=False,
    encoding="utf-8-sig"
)

In [ ]:
print("Liens :", len(tous_les_liens))
print("Récupérés :", len(dataset_complet))

In [ ]:
dataset_complet = []
erreurs = []

for i, lien in enumerate(tous_les_liens):
    try:
        print(i+1, "/", len(tous_les_liens))

        resultat = extraire_annonce(lien)

        if resultat:
            dataset_complet.append(resultat)
        else:
            erreurs.append(lien)

    except Exception as e:
        erreurs.append(lien)

print("OK :", len(dataset_complet))
print("Erreurs :", len(erreurs))

In [ ]:
def extraire_annonce_rapide(url):
    driver.get(url)
    time.sleep(1)

    annonce = {
        "URL": url,
        "Titre": None,
        "Annee": None,
        "Kilometrage": None,
        "Carburant": None,
        "Transmission": None
    }

    texte = driver.find_element(By.TAG_NAME, "body").text

    lignes = [x.strip() for x in texte.split("\n") if x.strip()]

    # Titre
    if "Acheter une voiture d'occasion" in lignes:
        try:
            idx = lignes.index("Acheter une voiture d'occasion")
            annonce["Titre"] = lignes[idx+1]
        except:
            pass

    # Année
    for ligne in lignes:
        if ligne.isdigit() and len(ligne) == 4:
            annonce["Annee"] = ligne
            break

    # Kilométrage
    for ligne in lignes:
        if "km" in ligne:
            annonce["Kilometrage"] = ligne.replace("km","").strip()
            break

    # Carburant
    for c in ["Diesel", "Essence", "Hybride", "Electrique"]:
        if c in texte:
            annonce["Carburant"] = c
            break

    # Transmission
    if "Automatique" in texte:
        annonce["Transmission"] = "Automatique"
    elif "Manuelle" in texte:
        annonce["Transmission"] = "Manuelle"

    return annonce

In [ ]:
dataset_130 = []

for i, lien in enumerate(tous_les_liens):
    try:
        print(i+1, "/", len(tous_les_liens))

        d = extraire_annonce_rapide(lien)
        
        if d["Titre"] is not None:
            dataset_130.append(d)

    except:
        pass

print("Total :", len(dataset_130))

In [ ]:
driver.get("https://www.moteur.ma/fr/voiture/occasion/")
time.sleep(3)

In [ ]:
cartes = driver.find_elements(By.XPATH, "//a[contains(@href,'detail-annonce')]")

print("Nombre :", len(cartes))

In [ ]:
driver.get("https://www.moteur.ma/fr/voiture/occasion/")
time.sleep(5)

In [ ]:
from selenium.webdriver.common.by import By

liens = []

elements = driver.find_elements(By.XPATH, "//a[contains(@href,'detail-annonce')]")

for e in elements:
    href = e.get_attribute("href")
    if href and href not in liens:
        liens.append(href)

print("Nombre liens :", len(liens))

In [1]:
print(driver.current_url)

NameError: name 'driver' is not defined

In [2]:
len(tous_les_liens)

NameError: name 'tous_les_liens' is not defined

In [3]:
import os

os.listdir()

['.ipynb_checkpoints',
 '01_scraping_moteur.ipynb',
 'annonce.html',
 'Car-Price-Prediction',
 'Car_Price_Prediction.ipynb',
 'data',
 'dataset_voitures.csv',
 'dataset_voitures_clean.csv',
 'dataset_voitures_maroc.csv',
 'dataset_voitures_maroc_complet.csv',
 'images',
 'models',
 'notebooks',
 'page.html',
 'README.md',
 'reports',
 'requirements.txt',
 'scraping',
 'voitures_moteur.csv',
 'voitures_moteur_ma.csv']

In [4]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

driver = webdriver.Chrome()

tous_les_liens = []

for page in range(1, 11):

    url = f"https://www.moteur.ma/fr/voiture/occasion/?page={page}"

    driver.get(url)
    time.sleep(3)

    elements = driver.find_elements(By.XPATH, "//a[contains(@href,'detail-annonce')]")

    for e in elements:
        lien = e.get_attribute("href")
        if lien and lien not in tous_les_liens:
            tous_les_liens.append(lien)

    print("Page", page, "Total liens :", len(tous_les_liens))

print("TOTAL FINAL :", len(tous_les_liens))

Page 1 Total liens : 0
Page 2 Total liens : 0
Page 3 Total liens : 0
Page 4 Total liens : 0
Page 5 Total liens : 0
Page 6 Total liens : 0
Page 7 Total liens : 0
Page 8 Total liens : 0
Page 9 Total liens : 0
Page 10 Total liens : 0
TOTAL FINAL : 0

In [5]:
driver.get("https://www.moteur.ma/fr/voiture/occasion/")
time.sleep(5)

In [6]:
print(driver.current_url)

https://www.moteur.ma/fr/neuf/

In [7]:
occasion = driver.find_elements(By.XPATH, "//a[contains(text(),'Occasion')]")

print("Trouvé :", len(occasion))

for o in occasion:
    print(o.get_attribute("href"))

Trouvé : 1
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/

In [8]:
driver.get(URL_QUE_TU_AS_TROUVEE)
time.sleep(5)

NameError: name 'URL_QUE_TU_AS_TROUVEE' is not defined

In [9]:
occasion = driver.find_elements(By.XPATH, "//a[contains(text(),'Occasion')]")

print("Trouvé :", len(occasion))

for o in occasion:
    print(o.get_attribute("href"))

Trouvé : 1
https://www.moteur.ma/fr/voiture/achat-voiture-occasion/

In [10]:
driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/")
time.sleep(5)

print(driver.current_url)

https://www.moteur.ma/fr/voiture/achat-voiture-occasion/

In [11]:
tous_les_liens = []

elements = driver.find_elements(By.XPATH, "//a[contains(@href,'detail-annonce')]")

for e in elements:
    lien = e.get_attribute("href")
    if lien and lien not in tous_les_liens:
        tous_les_liens.append(lien)

print("Nombre liens :", len(tous_les_liens))

Nombre liens : 30

In [12]:
tous_les_liens = []

for page in range(1, 7):   # 6 pages = environ 180 liens
    
    url = f"https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?page={page}"
    
    driver.get(url)
    time.sleep(3)

    elements = driver.find_elements(By.XPATH, "//a[contains(@href,'detail-annonce')]")

    for e in elements:
        lien = e.get_attribute("href")
        if lien and lien not in tous_les_liens:
            tous_les_liens.append(lien)

    print("Page", page, "→ Total liens :", len(tous_les_liens))

print("TOTAL FINAL :", len(tous_les_liens))

Page 1 → Total liens : 30
Page 2 → Total liens : 60
Page 3 → Total liens : 90
Page 4 → Total liens : 120
Page 5 → Total liens : 150
Page 6 → Total liens : 180
TOTAL FINAL : 180

In [13]:
dataset_180 = []

for i, lien in enumerate(tous_les_liens):

    try:
        driver.get(lien)
        time.sleep(1.5)

        texte = driver.find_element(By.TAG_NAME, "body").text

        voiture = {
            "URL": lien,
            "Texte": texte
        }

        dataset_180.append(voiture)

        print(i+1, "/", len(tous_les_liens), "OK")

    except Exception as e:
        print(i+1, "Erreur")

print("TOTAL :", len(dataset_180))

1 / 180 OK
2 / 180 OK
3 / 180 OK
4 / 180 OK
5 / 180 OK
6 / 180 OK
7 / 180 OK
8 / 180 OK
9 / 180 OK
10 / 180 OK
11 / 180 OK
12 / 180 OK
13 / 180 OK
14 / 180 OK
15 / 180 OK
16 / 180 OK
17 / 180 OK
18 / 180 OK
19 / 180 OK
20 / 180 OK
21 / 180 OK
22 / 180 OK
23 / 180 OK
24 / 180 OK
25 / 180 OK
26 / 180 OK
27 / 180 OK
28 / 180 OK
29 / 180 OK
30 / 180 OK
31 / 180 OK
32 / 180 OK
33 / 180 OK
34 / 180 OK
35 / 180 OK
36 / 180 OK
37 / 180 OK
38 / 180 OK
39 / 180 OK
40 / 180 OK
41 / 180 OK
42 / 180 OK
43 / 180 OK
44 / 180 OK
45 / 180 OK
46 / 180 OK
47 / 180 OK
48 / 180 OK
49 / 180 OK
50 / 180 OK
51 / 180 OK
52 / 180 OK
53 / 180 OK
54 / 180 OK
55 / 180 OK
56 / 180 OK
57 / 180 OK
58 / 180 OK
59 / 180 OK
60 / 180 OK
61 / 180 OK
62 / 180 OK
63 / 180 OK
64 / 180 OK
65 / 180 OK
66 / 180 OK
67 / 180 OK
68 / 180 OK
69 / 180 OK
70 / 180 OK
71 / 180 OK
72 / 180 OK
73 / 180 OK
74 / 180 OK
75 / 180 OK
76 / 180 OK
77 / 180 OK
78 / 180 OK
79 / 180 OK
80 / 180 OK
81 / 180 OK
82 / 180 OK
83 / 180 OK
84 / 180 OK
85 / 180 OK
86 / 180 OK
87 / 180 OK
88 / 180 OK
89 / 180 OK
90 / 180 OK
91 / 180 OK
92 / 180 OK
93 / 180 OK
94 / 180 OK
95 / 180 OK
96 / 180 OK
97 / 180 OK
98 / 180 OK
99 / 180 OK
100 / 180 OK
101 / 180 OK
102 / 180 OK
103 / 180 OK
104 / 180 OK
105 / 180 OK
106 / 180 OK
107 / 180 OK
108 / 180 OK
109 / 180 OK
110 / 180 OK
111 / 180 OK
112 / 180 OK
113 / 180 OK
114 / 180 OK
115 / 180 OK
116 / 180 OK
117 / 180 OK
118 / 180 OK
119 / 180 OK
120 / 180 OK
121 / 180 OK
122 / 180 OK
123 / 180 OK
124 / 180 OK
125 / 180 OK
126 Erreur
127 Erreur
128 Erreur
129 Erreur
130 Erreur
131 Erreur
132 Erreur
133 Erreur
134 Erreur
135 Erreur
136 Erreur
137 Erreur
138 Erreur
139 Erreur
140 Erreur
141 Erreur
142 Erreur
143 Erreur
144 Erreur
145 Erreur
146 Erreur
147 Erreur
148 Erreur
149 Erreur
150 Erreur
151 Erreur
152 Erreur
153 Erreur
154 Erreur
155 Erreur
156 Erreur
157 Erreur
158 Erreur
159 Erreur
160 Erreur
161 Erreur
162 Erreur
163 Erreur
164 Erreur
165 Erreur
166 Erreur
167 Erreur
168 Erreur
169 Erreur
170 Erreur
171 Erreur
172 Erreur
173 Erreur
174 Erreur
175 Erreur
176 Erreur
177 Erreur
178 Erreur
179 Erreur
180 Erreur
TOTAL : 125

In [14]:
import pandas as pd

df_125 = pd.DataFrame(dataset_180)

df_125.shape

(125, 2)

In [15]:
df_125.to_csv(
    "voitures_brut_125.csv",
    index=False,
    encoding="utf-8-sig"
)

In [16]:
df_125.head()

,URL,Texte
0,https://www.moteur.ma/fr/voiture/achat-voiture...,Neuf\nPromotion\nÉmissions\nActualités\nOccasi...
1,https://www.moteur.ma/fr/voiture/achat-voiture...,Neuf\nPromotion\nÉmissions\nActualités\nOccasi...
2,https://www.moteur.ma/fr/voiture/achat-voiture...,Neuf\nPromotion\nÉmissions\nActualités\nOccasi...
3,https://www.moteur.ma/fr/voiture/achat-voiture...,Neuf\nPromotion\nÉmissions\nActualités\nOccasi...
4,https://www.moteur.ma/fr/voiture/achat-voiture...,Neuf\nPromotion\nÉmissions\nActualités\nOccasi...

In [17]:
print(df_125["Texte"][0])

Neuf
Promotion
Émissions
Actualités
Occasion
Se connecter
Vendez Votre Voiture
0
العربية
Offres du moment
DFSK E5
magnite
chery tiggo 7 pro
dacia sandero stepway
opel astra
opel corsa
opel grandland
opel frontera
opel mokka
Seat Leon FR
Seat ibiza
Accueil
Occasion
Acheter une voiture d'occasion
Hyundai Accent
Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Marque
Abarth
Alfa Romeo
Alpine
Aston Martin
Audi
BAIC
Bentley
BMW
BYD
Changan
Chery
Chevrolet
Citroën
Cupra
Dacia
DEEPAL
DENZA
DFSK
Dongfeng
DS
EXEED
Ferrari
Fiat
Ford
Foton
GAC
GAZ
Geely
GWM
Honda
Hyundai
Isuzu
jac
Jaecoo
Jaguar
Jeep
Jetour
KGM
Kia
Land Rover
Leapmotor
Lexus
Lynk & Co
Mahindra
Maserati
Mazda
Mercedes-Benz
MG
Mini
Mitsubishi
Neo Motors
Nissan
Omoda
Opel
Peugeot
Porsche
Renault
ROX
Seat
Seres
Skoda
Smart
soueast
Ssangyong
Suzuki
Tata
Tesla
Toyota
Volkswagen
Volvo
XPENG
Zeekr
                            Modèle

                            Version
                         Hyundai Accent
Appeler pour le prix
Voiture
Laâyoune
Jul 18, 2026
1 vues
Aucune image disponible
Informations Véhicule
Marque: Hyundai Modèle: Accent
Année: 2018 Kilométrage: 141 km
Carburant: Diesel Transmission: Manuelle
Carrosserie: N/A Couleur: N/A
Nombre de portes 5 Puissance fiscale 6
Spécifications rapides
سيارة للبيع كارت ݣريز
Caractéristiques & Options
Premier propriétaire Véhicule préparé
Historique d'accidents Importation neuve
Statut de douane N/A
options
État du véhicule
Climatisation
Airbags
Fermeture centralisée
Vitres électriques
CD / MP3 / Bluetooth
Annonces Similaires
Hyundai ix35
135,000 MAD
il y a 27 minutes
Hyundai i30
145,000 MAD
il y a 49 minutes
Hyundai Tucson
79,000 MAD
il y a 49 minutes
Hyundai Tucson
290,000 MAD
il y a 1 heure
Hyundai Elantra
115,000 MAD
il y a 1 heure
Dernières annonces premium
Premium
Fiat Tipo
Casablanca 2018
138,000 MAD
Premium
Fiat 500
Agadir 2023
150,000 MAD
Premium
Mercedes-Benz Classe CLA
Casablanca 2019
310,000 MAD
Publié par
Abderrahim laâtabi
Vendeur depuis Jul 2026
Informations Contact
Laâyoune
Appeler maintenant
Prix Hyundai Accent neuve maroc
HYUNDAI Accent
À partir de
210 000 Dhs
3 Versions
Prix promotionnels du moment
Kia
K 2500
À partir de
209 800 Dhs
Kia
Seltos
À partir de
253 400 Dhs
Honda
HR-V
À partir de
323 000 Dhs
Citroën
Ami
À partir de
85 900 Dhs
Kia
Carnival
À partir de
484 500 Dhs
BAIC
BJ30e
À partir de
299 000 Dhs
Mahindra
XUV 3XO
À partir de
162 000 Dhs
Dernières voitures neuves
NOUVEAU
Citroën
C3
PLUS PACK ESSENCE BVM
173 900 Dhs
2026 · Citadine
NOUVEAU
Fiat
Grizzly
Fastback BEV
Prix sur demande
2026 · SUV et 4x4
NOUVEAU
Fiat
Grizzly
Fastback 1.2 Turbo Hybrid 48V
Prix sur demande
2026 · SUV et 4x4
Comparez les voitures neuves au Maroc
Analysez les prix, motorisations et équipements pour faire le meilleur choix.
أودي
كيو8
MHEV Executive V6 3,0L TDI 286...
أودي
كيو5 سبورتباك
40 TDI 204 S-Tronic quattro Sp...
أودي VS أودي
بيجو
408
1.2 Hybrid 145 AT GT
داسيا
لوجان
1.0 TCe 100 Essential
بيجو VS داسيا
بي واي دي
سيل يو
1.5 AT 323 Design
هوندا
إتش آر-في
1.5 i-MMD e:HEV 129 CVT Sport
بي واي دي VS هوندا
Toutes les comparaisons neuves
GUIDES PRIX VOITURES NEUVES AU MAROC
Voitures neuves Maroc
Voitures hybrides Maroc
Voitures électriques neuves Maroc
Voitures neuves moins de 200 000 DH
SUV neufs Maroc
Voitures Diesel neuves
Voitures essence maroc
Voitures automatiques Maroc
Voitures familiales neuves
Voitures neuves au Maroc
Zeekr neuve Maroc
BYD neuve Maroc
Tata neuve Maroc
Ford neuve Maroc
Hyundai neuve Maroc
Ferrari neuve Maroc
DFSK neuve Maroc
Omoda neuve Maroc
Seres neuve Maroc
Toyota neuve Maroc
Isuzu neuve Maroc
Volvo neuve Maroc
Seat neuve Maroc
Alfa Romeo neuve Maroc
Mahindra neuve Maroc
Jaguar neuve Maroc
Peugeot neuve Maroc
Leapmotor neuve Maroc
Foton neuve Maroc
XPENG neuve Maroc
Jetour neuve Maroc
Fiat neuve Maroc
BMW neuve Maroc
Jaecoo neuve Maroc
KGM neuve Maroc
Modèles neufs populaires
BMW X5 neuve Maroc
BMW X3 neuve Maroc
Citroën Berlingo neuve Maroc
Citroën C5 Aircross neuve Maroc
Dacia Duster neuve Maroc
Dacia Bigster neuve Maroc
Ford Kuga neuve Maroc
Ford Territory neuve Maroc
Hyundai Kona neuve Maroc
Hyundai Santa Fe neuve Maroc
Kia EV5 neuve Maroc
Kia Sportage neuve Maroc
Mercedes-Benz Classe GLE neuve Maroc
Mercedes-Benz EQE neuve Maroc
Opel Mokka neuve Maroc
Opel Frontera neuve Maroc
Peugeot 2008 neuve Maroc
Peugeot 208 neuve Maroc
Renault 5 E-Tech neuve Maroc
Renault Master neuve Maroc
Toyota Yaris neuve Maroc
Toyota RAV-4 neuve Maroc
Volkswagen Tiguan neuve Maroc
Volkswagen Golf 8 neuve Maroc
Voitures occasion Maroc
Volkswagen occasion Maroc
Mercedes-Benz occasion Maroc
Renault occasion Maroc
Peugeot occasion Maroc
Dacia occasion Maroc
Hyundai occasion Maroc
Audi occasion Maroc
Ford occasion Maroc
BMW occasion Maroc
Fiat occasion Maroc
Kia occasion Maroc
Land Rover occasion Maroc
Citroën occasion Maroc
Toyota occasion Maroc
Opel occasion Maroc
Nissan occasion Maroc
Jeep occasion Maroc
Skoda occasion Maroc
Seat occasion Maroc
Porsche occasion Maroc
Volvo occasion Maroc
Alfa Romeo occasion Maroc
Honda occasion Maroc
Jaguar occasion Maroc
A propos
Accueil
Qui sommes-nous?
Offres Premium
Offres Premium Pro
Votre publicité sur MOTEUR.MA
Showrooms Pro
Dernières promotions 2026
La Comparaison des voitures neuves
Demander le prix de votre voiture
Service Bi3 lia
Les emissions
Actualités Auto
Forum d'aide automobile
Notre réseau de partenaires
Conditions générales d'utilisation
Conditions générales de vente
Contactez-nous
Ils parlent de nous - Presse
Plan du site
بالعــربيـة
© 2009-2026 MOTEUR.ma : Guide d'achat des voitures neuves et d'occasion au Maroc
Conformément à la loi 09-08, vous disposez d'un droit d'accès, de rectification et d'opposition au traitement de vos données personnelles. Ce traitement a été autorisé par la CNDP sous le numéro D-W-219/2017
Le site MOTEUR.ma ne joue que le rôle d'intermédiaire entre acheteurs et vendeurs. Nous n'intervenons pas dans les transactions d'achat et de vente. En conséquence, ne peut être tenu responsable de tous problèmes survenus après le déroulement des transactions entre les deux parties.

In [18]:
import re
import pandas as pd

def extraire_infos(texte):

    voiture = {}

    # Marque + Modèle
    m = re.search(r"Marque:\s*(.*?)\s+Modèle:\s*(.*?)\n", texte)
    if m:
        voiture["Marque"] = m.group(1).strip()
        voiture["Modele"] = m.group(2).strip()
    else:
        voiture["Marque"] = None
        voiture["Modele"] = None

    # Année
    m = re.search(r"Année:\s*(\d{4})", texte)
    voiture["Annee"] = m.group(1) if m else None

    # Kilométrage
    m = re.search(r"Kilométrage:\s*([\d,\s]+)\s*km", texte)
    voiture["Kilometrage"] = m.group(1).strip() if m else None

    # Carburant
    m = re.search(r"Carburant:\s*(Diesel|Essence|Hybride|Electrique)", texte)
    voiture["Carburant"] = m.group(1) if m else None

    # Transmission
    m = re.search(r"Transmission:\s*(Automatique|Manuelle)", texte)
    voiture["Transmission"] = m.group(1) if m else None

    # Prix
    m = re.search(r"(\d{1,3}(?:,\d{3})*)\s*MAD", texte)
    voiture["Prix"] = m.group(1).replace(",","") if m else None

    return voiture


# Application sur les 125 annonces
resultats = []

for texte in df_125["Texte"]:
    resultats.append(extraire_infos(texte))


df_final = pd.DataFrame(resultats)

df_final.head()

          Marque    Modele Annee Kilometrage Carburant Transmission    Prix
0        Hyundai    Accent  2018         141    Diesel     Manuelle  135000
1  Mercedes-Benz  Classe A  2016     258,000    Diesel     Manuelle  159000
2            BMW   Série 1  2024      37,000    Diesel  Automatique  370000
3        Renault    Megane  2019      89,000    Diesel  Automatique  137000
4        Citroën  C-Elysée  2023     121,000    Diesel     Manuelle  130800

In [19]:
df_final.shape

(125, 7)

In [20]:
df_final.head(10)

          Marque    Modele Annee Kilometrage Carburant Transmission     Prix
0        Hyundai    Accent  2018         141    Diesel     Manuelle   135000
1  Mercedes-Benz  Classe A  2016     258,000    Diesel     Manuelle   159000
2            BMW   Série 1  2024      37,000    Diesel  Automatique   370000
3        Renault    Megane  2019      89,000    Diesel  Automatique   137000
4        Citroën  C-Elysée  2023     121,000    Diesel     Manuelle   130800
5        Peugeot      3008  2022      86,000    Diesel  Automatique    63000
6           Audi        A6  2019      20,000    Diesel  Automatique    22000
7           Audi        A6  2019       2,000    Diesel  Automatique  2200000
8  Mercedes-Benz  Classe A  2016     258,000    Diesel  Automatique   159000
9          Skoda   Octavia  2001     390,000    Diesel     Manuelle    55000

In [21]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Marque        125 non-null    str
 1   Modele        125 non-null    str
 2   Annee         125 non-null    str
 3   Kilometrage   125 non-null    str
 4   Carburant     125 non-null    str
 5   Transmission  125 non-null    str
 6   Prix          125 non-null    str
dtypes: str(7)
memory usage: 7.0 KB

In [22]:
df_final["Prix"] = pd.to_numeric(df_final["Prix"], errors="coerce")

df_final["Annee"] = pd.to_numeric(df_final["Annee"], errors="coerce")

df_final["Kilometrage"] = (
    df_final["Kilometrage"]
    .str.replace(",","")
    .astype(float)
)

In [23]:
df_final.head()

          Marque    Modele  Annee  Kilometrage Carburant Transmission    Prix
0        Hyundai    Accent   2018        141.0    Diesel     Manuelle  135000
1  Mercedes-Benz  Classe A   2016     258000.0    Diesel     Manuelle  159000
2            BMW   Série 1   2024      37000.0    Diesel  Automatique  370000
3        Renault    Megane   2019      89000.0    Diesel  Automatique  137000
4        Citroën  C-Elysée   2023     121000.0    Diesel     Manuelle  130800

In [24]:
df_final.to_csv(
    "dataset_voitures_maroc_final.csv",
    index=False,
    encoding="utf-8-sig"
)

In [25]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Marque        125 non-null    str
 1   Modele        125 non-null    str
 2   Annee         125 non-null    int64
 3   Kilometrage   125 non-null    float64
 4   Carburant     125 non-null    str
 5   Transmission  125 non-null    str
 6   Prix          125 non-null    int64
dtypes: float64(1), int64(2), str(4)
memory usage: 7.0 KB

In [26]:
df_final["Prix"] = pd.to_numeric(df_final["Prix"], errors="coerce")

df_final["Annee"] = pd.to_numeric(df_final["Annee"], errors="coerce")

df_final["Kilometrage"] = (
    df_final["Kilometrage"]
    .str.replace(",","")
    .astype(float)
)

AttributeError: Can only use .str accessor with string values, not floating

In [27]:
df_final["Kilometrage"] = pd.to_numeric(
    df_final["Kilometrage"],
    errors="coerce"
)

In [28]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Marque        125 non-null    str
 1   Modele        125 non-null    str
 2   Annee         125 non-null    int64
 3   Kilometrage   125 non-null    float64
 4   Carburant     125 non-null    str
 5   Transmission  125 non-null    str
 6   Prix          125 non-null    int64
dtypes: float64(1), int64(2), str(4)
memory usage: 7.0 KB

In [29]:
df_final.isnull().sum()

Marque          0
Modele          0
Annee           0
Kilometrage     0
Carburant       0
Transmission    0
Prix            0
dtype: int64

In [30]:
from selenium import webdriver
import time

driver = webdriver.Chrome()

In [31]:
driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/")
time.sleep(5)

In [32]:
print(driver.title)

Voiture occasion| Moteur.ma

In [33]:
tous_les_liens = []

for page in range(1, 21):   # 20 pages
    
    url = f"https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?page={page}"
    
    driver.get(url)
    time.sleep(3)

    elements = driver.find_elements(By.XPATH, "//a[contains(@href,'detail-annonce')]")

    for e in elements:
        lien = e.get_attribute("href")
        if lien and lien not in tous_les_liens:
            tous_les_liens.append(lien)

    print("Page", page, "→", len(tous_les_liens))

print("TOTAL LIENS :", len(tous_les_liens))

Page 1 → 30
Page 2 → 60
Page 3 → 90
Page 4 → 120
Page 5 → 150
Page 6 → 180
Page 7 → 210
Page 8 → 240
Page 9 → 270
Page 10 → 300
Page 11 → 330
Page 12 → 360
Page 13 → 390
Page 14 → 420
Page 15 → 450
Page 16 → 480
Page 17 → 510
Page 18 → 540
Page 19 → 570
Page 20 → 600
TOTAL LIENS : 600

In [ ]:
from selenium.common.exceptions import TimeoutException

driver.set_page_load_timeout(10)

dataset_600 = []

for i, lien in enumerate(tous_les_liens[:600]):

    try:
        driver.get(lien)
        time.sleep(1)

        texte = driver.find_element(By.TAG_NAME, "body").text

        dataset_600.append({
            "URL": lien,
            "Texte": texte
        })

        print(i+1, "OK - Total :", len(dataset_600))

    except TimeoutException:
        print(i+1, "Timeout")

    except Exception as e:
        print(i+1, "Erreur")

    # sauvegarde tous les 50
    if (i+1) % 50 == 0:
        pd.DataFrame(dataset_600).to_csv(
            f"backup_{i+1}.csv",
            index=False,
            encoding="utf-8-sig"
        )
        print("💾 Sauvegarde effectuée :", i+1)

print("FIN :", len(dataset_600))

In [1]:
import pandas as pd

pd.DataFrame(tous_les_liens, columns=["URL"]).to_csv(
    "liens_600.csv",
    index=False,
    encoding="utf-8-sig"
)

NameError: name 'tous_les_liens' is not defined

In [2]:
import os
os.listdir()

['.ipynb_checkpoints',
 '01_scraping_moteur.ipynb',
 'annonce.html',
 'Car-Price-Prediction',
 'Car_Price_Prediction.ipynb',
 'data',
 'dataset_voitures.csv',
 'dataset_voitures_clean.csv',
 'dataset_voitures_maroc.csv',
 'dataset_voitures_maroc_complet.csv',
 'dataset_voitures_maroc_final.csv',
 'images',
 'models',
 'notebooks',
 'page.html',
 'README.md',
 'reports',
 'requirements.txt',
 'scraping',
 'voitures_brut_125.csv',
 'voitures_moteur.csv',
 'voitures_moteur_ma.csv']

In [3]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# si driver existe déjà, on le garde
try:
    driver.current_url
except:
    driver = webdriver.Chrome()

tous_les_liens = []

for page in range(1, 21):

    url = f"https://www.moteur.ma/fr/voiture/achat-voiture-occasion/?page={page}"

    driver.get(url)
    time.sleep(3)

    elements = driver.find_elements(
        By.XPATH,
        "//a[contains(@href,'detail-annonce')]"
    )

    for e in elements:
        lien = e.get_attribute("href")
        if lien and lien not in tous_les_liens:
            tous_les_liens.append(lien)

    print("Page", page, "→", len(tous_les_liens))

print("TOTAL LIENS :", len(tous_les_liens))

Page 1 → 30
Page 2 → 60
Page 3 → 90
Page 4 → 120
Page 5 → 150
Page 6 → 180
Page 7 → 210
Page 8 → 240
Page 9 → 270
Page 10 → 300
Page 11 → 330
Page 12 → 360
Page 13 → 390
Page 14 → 420
Page 15 → 450
Page 16 → 480
Page 17 → 510
Page 18 → 540
Page 19 → 570
Page 20 → 600
TOTAL LIENS : 600

In [4]:
import pandas as pd

pd.DataFrame(
    tous_les_liens,
    columns=["URL"]
).to_csv(
    "liens_600.csv",
    index=False,
    encoding="utf-8-sig"
)

In [5]:
df_liens = pd.read_csv("liens_600.csv")

print(df_liens.shape)

(600, 1)

In [6]:
dataset_600 = []

for i, lien in enumerate(tous_les_liens):

    try:
        driver.get(lien)
        time.sleep(1)

        texte = driver.find_element(By.TAG_NAME, "body").text

        dataset_600.append({
            "URL": lien,
            "Texte": texte
        })

        print(i+1, "OK")

    except:
        print(i+1, "Erreur")

    if (i+1) % 50 == 0:
        pd.DataFrame(dataset_600).to_csv(
            f"backup_{i+1}.csv",
            index=False,
            encoding="utf-8-sig"
        )
        print("Sauvegarde", i+1)

print("FIN :", len(dataset_600))

1 OK
2 OK
3 OK
4 OK
5 OK
6 OK
7 OK
8 OK
9 OK
10 OK
11 OK
12 OK
13 OK
14 OK
15 OK
16 OK
17 OK
18 OK
19 OK
20 OK
21 OK
22 OK
23 OK
24 OK
25 OK
26 OK
27 OK
28 OK
29 OK
30 OK
31 OK
32 OK
33 OK
34 OK
35 OK
36 OK
37 OK
38 OK
39 OK
40 OK
41 OK
42 OK
43 OK
44 OK
45 OK
46 OK
47 OK
48 OK
49 OK
50 OK
Sauvegarde 50
51 OK
52 OK
53 OK
54 OK
55 OK
56 OK
57 OK
58 OK
59 OK
60 OK
61 OK
62 OK
63 OK
64 OK
65 OK
66 OK
67 OK
68 OK
69 OK
70 OK
71 OK
72 OK
73 OK
74 OK
75 OK
76 OK
77 OK
78 OK
79 OK
80 OK
81 OK
82 OK
83 OK
84 OK
85 Erreur
86 Erreur
87 Erreur
88 Erreur
89 Erreur
90 Erreur
91 Erreur
92 Erreur
93 Erreur
94 Erreur
95 Erreur
96 Erreur
97 Erreur
98 Erreur
99 Erreur
100 Erreur
Sauvegarde 100
101 Erreur
102 Erreur
103 Erreur
104 Erreur
105 Erreur
106 Erreur
107 Erreur
108 Erreur
109 Erreur
110 Erreur
111 Erreur
112 Erreur
113 Erreur
114 Erreur
115 Erreur
116 Erreur
117 Erreur
118 Erreur
119 Erreur
120 Erreur
121 Erreur
122 Erreur
123 Erreur
124 Erreur
125 Erreur
126 Erreur
127 Erreur
128 Erreur
129 Erreur
130 Erreur
131 Erreur
132 Erreur
133 Erreur
134 Erreur
135 Erreur
136 Erreur
137 Erreur
138 Erreur
139 Erreur
140 Erreur
141 Erreur
142 Erreur
143 Erreur
144 Erreur
145 Erreur
146 Erreur
147 Erreur
148 Erreur
149 Erreur
150 Erreur
Sauvegarde 150
151 Erreur
152 Erreur
153 Erreur
154 Erreur
155 Erreur
156 Erreur
157 Erreur
158 Erreur
159 Erreur
160 Erreur
161 Erreur
162 Erreur
163 Erreur
164 Erreur
165 Erreur
166 Erreur
167 Erreur
168 Erreur
169 Erreur
170 Erreur
171 Erreur
172 Erreur
173 Erreur
174 Erreur
175 Erreur
176 Erreur
177 Erreur
178 Erreur
179 Erreur
180 Erreur
181 Erreur
182 Erreur
183 Erreur
184 Erreur
185 Erreur
186 Erreur
187 Erreur
188 Erreur
189 Erreur
190 Erreur
191 Erreur
192 Erreur
193 Erreur
194 Erreur
195 Erreur
196 Erreur
197 Erreur
198 Erreur
199 Erreur
200 Erreur
Sauvegarde 200
201 Erreur
202 Erreur
203 Erreur
204 Erreur
205 Erreur
206 Erreur
207 Erreur
208 Erreur
209 Erreur
210 Erreur
211 Erreur
212 Erreur
213 Erreur
214 Erreur
215 Erreur
216 Erreur
217 Erreur
218 Erreur
219 Erreur
220 Erreur
221 Erreur
222 Erreur
223 Erreur
224 Erreur
225 Erreur
226 Erreur
227 Erreur
228 Erreur
229 Erreur
230 Erreur
231 Erreur
232 Erreur
233 Erreur
234 Erreur
235 Erreur
236 Erreur
237 Erreur
238 Erreur
239 Erreur
240 Erreur
241 Erreur
242 Erreur
243 Erreur
244 Erreur
245 Erreur
246 Erreur
247 Erreur
248 Erreur
249 Erreur
250 Erreur
Sauvegarde 250
251 Erreur
252 Erreur
253 Erreur
254 Erreur
255 Erreur
256 Erreur
257 Erreur
258 Erreur
259 Erreur
260 Erreur
261 Erreur
262 Erreur
263 Erreur
264 Erreur
265 Erreur
266 Erreur
267 Erreur
268 Erreur
269 Erreur
270 Erreur
271 Erreur
272 Erreur
273 Erreur
274 Erreur
275 Erreur
276 Erreur
277 Erreur
278 Erreur
279 Erreur
280 Erreur
281 Erreur
282 Erreur
283 Erreur
284 Erreur
285 Erreur
286 Erreur
287 Erreur
288 Erreur
289 Erreur
290 Erreur
291 Erreur
292 Erreur
293 Erreur
294 Erreur
295 Erreur
296 Erreur
297 Erreur
298 Erreur
299 Erreur
300 Erreur
Sauvegarde 300
301 Erreur
302 Erreur
303 Erreur
304 Erreur
305 Erreur
306 Erreur
307 Erreur
308 Erreur
309 Erreur
310 Erreur
311 Erreur
312 Erreur
313 Erreur
314 Erreur
315 Erreur
316 Erreur
317 Erreur
318 Erreur
319 Erreur
320 Erreur
321 Erreur
322 Erreur
323 Erreur
324 Erreur
325 Erreur
326 Erreur
327 Erreur
328 Erreur
329 Erreur
330 Erreur
331 Erreur
332 Erreur
333 Erreur
334 Erreur
335 Erreur
336 Erreur
337 Erreur
338 Erreur
339 Erreur
340 Erreur
341 Erreur
342 Erreur
343 Erreur
344 Erreur
345 Erreur
346 Erreur
347 Erreur
348 Erreur
349 Erreur
350 Erreur
Sauvegarde 350
351 Erreur
352 Erreur
353 Erreur
354 Erreur
355 Erreur
356 Erreur
357 Erreur
358 Erreur
359 Erreur
360 Erreur
361 Erreur
362 Erreur
363 Erreur
364 Erreur
365 Erreur
366 Erreur
367 Erreur
368 Erreur
369 Erreur
370 Erreur
371 Erreur
372 Erreur
373 Erreur
374 Erreur
375 Erreur
376 Erreur
377 Erreur
378 Erreur
379 Erreur
380 Erreur
381 Erreur
382 Erreur
383 Erreur
384 Erreur
385 Erreur
386 Erreur
387 Erreur
388 Erreur
389 Erreur
390 Erreur
391 Erreur
392 Erreur
393 Erreur
394 Erreur
395 Erreur
396 Erreur
397 Erreur
398 Erreur
399 Erreur
400 Erreur
Sauvegarde 400
401 Erreur
402 Erreur
403 Erreur
404 Erreur
405 Erreur
406 Erreur
407 Erreur
408 Erreur
409 Erreur
410 Erreur
411 Erreur
412 Erreur
413 Erreur
414 Erreur
415 Erreur
416 Erreur
417 Erreur
418 Erreur
419 Erreur
420 Erreur
421 Erreur
422 Erreur
423 Erreur
424 Erreur
425 Erreur
426 Erreur
427 Erreur
428 Erreur
429 Erreur
430 Erreur
431 Erreur
432 Erreur
433 Erreur
434 Erreur
435 Erreur
436 Erreur
437 Erreur
438 Erreur
439 Erreur
440 Erreur
441 Erreur
442 Erreur
443 Erreur
444 Erreur
445 Erreur
446 Erreur
447 Erreur
448 Erreur
449 Erreur
450 Erreur
Sauvegarde 450
451 Erreur
452 Erreur
453 Erreur
454 Erreur
455 Erreur
456 Erreur
457 Erreur
458 Erreur
459 Erreur
460 Erreur
461 Erreur
462 Erreur
463 Erreur
464 Erreur
465 Erreur
466 Erreur
467 Erreur
468 Erreur
469 Erreur
470 Erreur
471 Erreur
472 Erreur
473 Erreur
474 Erreur
475 Erreur
476 Erreur
477 Erreur
478 Erreur
479 Erreur
480 Erreur
481 Erreur
482 Erreur
483 Erreur
484 Erreur
485 Erreur
486 Erreur
487 Erreur
488 Erreur
489 Erreur
490 Erreur
491 Erreur
492 Erreur
493 Erreur
494 Erreur
495 Erreur
496 Erreur
497 Erreur
498 Erreur
499 Erreur
500 Erreur
Sauvegarde 500
501 Erreur
502 Erreur
503 Erreur
504 Erreur
505 Erreur
506 Erreur
507 Erreur
508 Erreur
509 Erreur
510 Erreur
511 Erreur
512 Erreur
513 Erreur
514 Erreur
515 Erreur
516 Erreur
517 Erreur
518 Erreur
519 Erreur
520 Erreur
521 Erreur
522 Erreur
523 Erreur
524 Erreur
525 Erreur
526 Erreur
527 Erreur
528 Erreur
529 Erreur
530 Erreur
531 Erreur
532 Erreur
533 Erreur
534 Erreur
535 Erreur
536 Erreur
537 Erreur
538 Erreur
539 Erreur
540 Erreur
541 Erreur
542 Erreur
543 Erreur
544 Erreur
545 Erreur
546 Erreur
547 Erreur
548 Erreur
549 Erreur
550 Erreur
Sauvegarde 550
551 Erreur
552 Erreur
553 Erreur
554 Erreur
555 Erreur
556 Erreur
557 Erreur
558 Erreur
559 Erreur
560 Erreur
561 Erreur
562 Erreur
563 Erreur
564 Erreur
565 Erreur
566 Erreur
567 Erreur
568 Erreur
569 Erreur
570 Erreur
571 Erreur
572 Erreur
573 Erreur
574 Erreur
575 Erreur
576 Erreur
577 Erreur
578 Erreur
579 Erreur
580 Erreur
581 Erreur
582 Erreur
583 Erreur
584 Erreur
585 Erreur
586 Erreur
587 Erreur
588 Erreur
589 Erreur
590 Erreur
591 Erreur
592 Erreur
593 Erreur
594 Erreur
595 Erreur
596 Erreur
597 Erreur
598 Erreur
599 Erreur
600 Erreur
Sauvegarde 600
FIN : 84

In [7]:
len(dataset_600)

84

In [8]:
import pandas as pd

pd.DataFrame(dataset_600).to_csv(
    "voitures_brut_84.csv",
    index=False,
    encoding="utf-8-sig"
)

In [9]:
liens_recuperes = [x["URL"] for x in dataset_600]

liens_restants = [
    x for x in tous_les_liens
    if x not in liens_recuperes
]

print("Restants :", len(liens_restants))

Restants : 516

In [10]:
from selenium.common.exceptions import TimeoutException
import time

driver.set_page_load_timeout(15)

nouvelles_donnees = []

for i, lien in enumerate(liens_restants):

    success = False

    for tentative in range(2):

        try:
            driver.get(lien)
            time.sleep(2)

            texte = driver.find_element(By.TAG_NAME, "body").text

            nouvelles_donnees.append({
                "URL": lien,
                "Texte": texte
            })

            print(i+1, "/", len(liens_restants), "OK")
            success = True
            break

        except Exception as e:
            print(i+1, "tentative", tentative+1, "échouée")
            time.sleep(3)

    if not success:
        print(i+1, "abandonnée")

    # sauvegarde chaque 50
    if (i+1) % 50 == 0:
        temp = dataset_600 + nouvelles_donnees
        
        pd.DataFrame(temp).to_csv(
            f"backup_total_{i+1}.csv",
            index=False,
            encoding="utf-8-sig"
        )
        
        print("💾 Sauvegarde :", len(temp))

InvalidSessionIdException: Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

In [11]:
try:
    driver.quit()
except:
    pass

In [12]:
from selenium import webdriver
import time

driver = webdriver.Chrome()

driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/")
time.sleep(5)

print(driver.title)

Voiture occasion| Moteur.ma

In [13]:
test_restants = liens_restants[:50]

nouvelles_donnees = []

for i, lien in enumerate(test_restants):

    try:
        driver.get(lien)
        time.sleep(2)

        texte = driver.find_element(By.TAG_NAME, "body").text

        nouvelles_donnees.append({
            "URL": lien,
            "Texte": texte
        })

        print(i+1, "OK")

    except Exception as e:
        print(i+1, "Erreur")

print("Récupérées :", len(nouvelles_donnees))

1 OK
2 OK
3 OK
4 OK
5 OK
6 OK
7 OK
8 OK
9 OK
10 OK
11 OK
12 OK
13 OK
14 OK
15 OK
16 OK
17 OK
18 OK
19 OK
20 OK
21 OK
22 OK
23 OK
24 OK
25 OK
26 OK
27 OK
28 OK
29 OK
30 OK
31 OK
32 OK
33 OK
34 OK
35 OK
36 OK
37 OK
38 OK
39 OK
40 OK
41 OK
42 OK
43 OK
44 OK
45 OK
46 OK
47 OK
48 OK
49 OK
50 OK
Récupérées : 50

In [14]:
dataset_total = dataset_600 + nouvelles_donnees

pd.DataFrame(dataset_total).to_csv(
    "voitures_brut_134.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Total sauvegardé :", len(dataset_total))

Total sauvegardé : 134

In [15]:
liens_restants2 = liens_restants[50:]

print(len(liens_restants2))

466

In [16]:
nouvelles_donnees2 = []

for i, lien in enumerate(liens_restants2):

    try:
        driver.get(lien)
        time.sleep(2)

        texte = driver.find_element(By.TAG_NAME, "body").text

        nouvelles_donnees2.append({
            "URL": lien,
            "Texte": texte
        })

        print(i+1, "OK")

    except:
        print(i+1, "Erreur")

    if (i+1) % 50 == 0:
        total = dataset_total + nouvelles_donnees2
        
        pd.DataFrame(total).to_csv(
            f"backup_{len(total)}.csv",
            index=False,
            encoding="utf-8-sig"
        )
        
        print("💾 Sauvegarde :", len(total))

print("Nouvelles :", len(nouvelles_donnees2))

1 OK
2 OK
3 OK
4 OK
5 OK
6 OK
7 OK
8 OK
9 OK
10 OK
11 OK
12 OK
13 OK
14 OK
15 OK
16 OK
17 OK
18 OK
19 OK
20 OK
21 OK
22 OK
23 OK
24 OK
25 OK
26 OK
27 OK
28 OK
29 OK
30 OK
31 OK
32 OK
33 OK
34 OK
35 OK
36 OK
37 OK
38 OK
39 OK
40 OK
41 Erreur
42 Erreur
43 Erreur
44 Erreur
45 Erreur
46 Erreur
47 Erreur
48 Erreur
49 Erreur
50 Erreur
💾 Sauvegarde : 174
51 Erreur
52 Erreur
53 Erreur
54 Erreur
55 Erreur
56 Erreur
57 Erreur
58 Erreur
59 Erreur
60 Erreur
61 Erreur
62 Erreur
63 Erreur
64 Erreur
65 Erreur
66 Erreur
67 Erreur
68 Erreur
69 Erreur
70 Erreur
71 Erreur
72 Erreur
73 Erreur
74 Erreur
75 Erreur
76 Erreur
77 Erreur
78 Erreur
79 Erreur
80 Erreur
81 Erreur
82 Erreur
83 Erreur
84 Erreur
85 Erreur
86 Erreur
87 Erreur
88 Erreur
89 Erreur
90 Erreur
91 Erreur
92 Erreur
93 Erreur
94 Erreur
95 Erreur
96 Erreur
97 Erreur
98 Erreur
99 Erreur
100 Erreur
💾 Sauvegarde : 174
101 Erreur
102 Erreur
103 Erreur
104 Erreur
105 Erreur
106 Erreur
107 Erreur
108 Erreur
109 Erreur
110 Erreur
111 Erreur
112 Erreur
113 Erreur
114 Erreur
115 Erreur
116 Erreur
117 Erreur
118 Erreur
119 Erreur
120 Erreur
121 Erreur
122 Erreur
123 Erreur
124 Erreur
125 Erreur
126 Erreur
127 Erreur
128 Erreur
129 Erreur
130 Erreur
131 Erreur
132 Erreur
133 Erreur
134 Erreur
135 Erreur
136 Erreur
137 Erreur
138 Erreur
139 Erreur
140 Erreur
141 Erreur
142 Erreur
143 Erreur
144 Erreur
145 Erreur
146 Erreur
147 Erreur
148 Erreur
149 Erreur
150 Erreur
💾 Sauvegarde : 174
151 Erreur
152 Erreur
153 Erreur
154 Erreur
155 Erreur
156 Erreur
157 Erreur
158 Erreur
159 Erreur
160 Erreur
161 Erreur
162 Erreur
163 Erreur
164 Erreur
165 Erreur
166 Erreur
167 Erreur
168 Erreur
169 Erreur
170 Erreur
171 Erreur
172 Erreur
173 Erreur
174 Erreur
175 Erreur
176 Erreur
177 Erreur
178 Erreur
179 Erreur
180 Erreur
181 Erreur
182 Erreur
183 Erreur
184 Erreur
185 Erreur
186 Erreur
187 Erreur
188 Erreur
189 Erreur
190 Erreur
191 Erreur
192 Erreur
193 Erreur
194 Erreur
195 Erreur
196 Erreur
197 Erreur
198 Erreur
199 Erreur
200 Erreur
💾 Sauvegarde : 174
201 Erreur
202 Erreur
203 Erreur
204 Erreur
205 Erreur
206 Erreur
207 Erreur
208 Erreur
209 Erreur
210 Erreur
211 Erreur
212 Erreur
213 Erreur
214 Erreur
215 Erreur
216 Erreur
217 Erreur
218 Erreur
219 Erreur
220 Erreur
221 Erreur
222 Erreur
223 Erreur
224 Erreur
225 Erreur
226 Erreur
227 Erreur
228 Erreur
229 Erreur
230 Erreur
231 Erreur
232 Erreur
233 Erreur
234 Erreur
235 Erreur
236 Erreur
237 Erreur
238 Erreur
239 Erreur
240 Erreur
241 Erreur
242 Erreur
243 Erreur
244 Erreur
245 Erreur
246 Erreur
247 Erreur
248 Erreur
249 Erreur
250 Erreur
💾 Sauvegarde : 174
251 Erreur
252 Erreur
253 Erreur
254 Erreur
255 Erreur
256 Erreur
257 Erreur
258 Erreur
259 Erreur
260 Erreur
261 Erreur
262 Erreur
263 Erreur
264 Erreur
265 Erreur
266 Erreur
267 Erreur
268 Erreur
269 Erreur
270 Erreur
271 Erreur
272 Erreur
273 Erreur
274 Erreur
275 Erreur
276 Erreur
277 Erreur
278 Erreur
279 Erreur
280 Erreur
281 Erreur
282 Erreur
283 Erreur
284 Erreur
285 Erreur
286 Erreur
287 Erreur
288 Erreur
289 Erreur
290 Erreur
291 Erreur
292 Erreur
293 Erreur
294 Erreur
295 Erreur
296 Erreur
297 Erreur
298 Erreur
299 Erreur
300 Erreur
💾 Sauvegarde : 174
301 Erreur
302 Erreur
303 Erreur
304 Erreur
305 Erreur
306 Erreur
307 Erreur
308 Erreur
309 Erreur
310 Erreur
311 Erreur
312 Erreur
313 Erreur
314 Erreur
315 Erreur
316 Erreur
317 Erreur
318 Erreur
319 Erreur
320 Erreur
321 Erreur
322 Erreur
323 Erreur
324 Erreur
325 Erreur
326 Erreur
327 Erreur
328 Erreur
329 Erreur
330 Erreur
331 Erreur
332 Erreur
333 Erreur
334 Erreur
335 Erreur
336 Erreur
337 Erreur
338 Erreur
339 Erreur
340 Erreur
341 Erreur
342 Erreur
343 Erreur
344 Erreur
345 Erreur
346 Erreur
347 Erreur
348 Erreur
349 Erreur
350 Erreur
💾 Sauvegarde : 174
351 Erreur
352 Erreur
353 Erreur
354 Erreur
355 Erreur
356 Erreur
357 Erreur
358 Erreur
359 Erreur
360 Erreur
361 Erreur
362 Erreur
363 Erreur
364 Erreur
365 Erreur
366 Erreur
367 Erreur
368 Erreur
369 Erreur
370 Erreur
371 Erreur
372 Erreur
373 Erreur
374 Erreur
375 Erreur
376 Erreur
377 Erreur
378 Erreur
379 Erreur
380 Erreur
381 Erreur
382 Erreur
383 Erreur
384 Erreur
385 Erreur
386 Erreur
387 Erreur
388 Erreur
389 Erreur
390 Erreur
391 Erreur
392 Erreur
393 Erreur
394 Erreur
395 Erreur
396 Erreur
397 Erreur
398 Erreur
399 Erreur
400 Erreur
💾 Sauvegarde : 174
401 Erreur
402 Erreur
403 Erreur
404 Erreur
405 Erreur
406 Erreur
407 Erreur
408 Erreur
409 Erreur
410 Erreur
411 Erreur
412 Erreur
413 Erreur
414 Erreur
415 Erreur
416 Erreur
417 Erreur
418 Erreur
419 Erreur
420 Erreur
421 Erreur
422 Erreur
423 Erreur
424 Erreur
425 Erreur
426 Erreur
427 Erreur
428 Erreur
429 Erreur
430 Erreur
431 Erreur
432 Erreur
433 Erreur
434 Erreur
435 Erreur
436 Erreur
437 Erreur
438 Erreur
439 Erreur
440 Erreur
441 Erreur
442 Erreur
443 Erreur
444 Erreur
445 Erreur
446 Erreur
447 Erreur
448 Erreur
449 Erreur
450 Erreur
💾 Sauvegarde : 174
451 Erreur
452 Erreur
453 Erreur
454 Erreur
455 Erreur
456 Erreur
457 Erreur
458 Erreur
459 Erreur
460 Erreur
461 Erreur
462 Erreur
463 Erreur
464 Erreur
465 Erreur
466 Erreur
Nouvelles : 40

In [17]:
dataset_total = dataset_total + nouvelles_donnees2

pd.DataFrame(dataset_total).to_csv(
    "voitures_brut_174.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Total :", len(dataset_total))

Total : 174

In [18]:
print("Liens restants :", len(liens_restants2))

Liens restants : 466

In [19]:
nouvelles_donnees3 = []

for i, lien in enumerate(liens_restants3[:50]):

    try:
        driver.get(lien)
        time.sleep(2)

        texte = driver.find_element(By.TAG_NAME, "body").text

        nouvelles_donnees3.append({
            "URL": lien,
            "Texte": texte
        })

        print(i+1, "OK")

    except:
        print(i+1, "Erreur")

print("Récupérées :", len(nouvelles_donnees3))

NameError: name 'liens_restants3' is not defined

In [20]:
print(len(dataset_total))
print(len(nouvelles_donnees2))
print(len(liens_restants2))

174
40
466

In [21]:
liens_restants3 = liens_restants2[40:]

print("À traiter :", len(liens_restants3))

À traiter : 426

In [22]:
nouvelles_donnees3 = []

for i, lien in enumerate(liens_restants3[:50]):

    try:
        driver.get(lien)
        time.sleep(2)

        texte = driver.find_element(By.TAG_NAME, "body").text

        nouvelles_donnees3.append({
            "URL": lien,
            "Texte": texte
        })

        print(i+1, "OK")

    except:
        print(i+1, "Erreur")

print("Récupérées :", len(nouvelles_donnees3))

1 Erreur
2 Erreur
3 Erreur
4 Erreur
5 Erreur
6 Erreur
7 Erreur
8 Erreur
9 Erreur
10 Erreur
11 Erreur
12 Erreur
13 Erreur
14 Erreur
15 Erreur
16 Erreur
17 Erreur
18 Erreur
19 Erreur
20 Erreur
21 Erreur
22 Erreur
23 Erreur
24 Erreur
25 Erreur
26 Erreur
27 Erreur
28 Erreur
29 Erreur
30 Erreur
31 Erreur
32 Erreur
33 Erreur
34 Erreur
35 Erreur
36 Erreur
37 Erreur
38 Erreur
39 Erreur
40 Erreur
41 Erreur
42 Erreur
43 Erreur
44 Erreur
45 Erreur
46 Erreur
47 Erreur
48 Erreur
49 Erreur
50 Erreur
Récupérées : 0

In [23]:
print(driver.title)

InvalidSessionIdException: Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff788040d25+155a5]
	chromedriver!GetHandleVerifier [0x7ff788040d80+15600]
	chromedriver!(No symbol) [0x7ff787b95736]
	chromedriver!(No symbol) [0x7ff787be1ed6]
	chromedriver!(No symbol) [0x7ff787c190d2]
	chromedriver!(No symbol) [0x7ff787c12ef2]
	chromedriver!(No symbol) [0x7ff787c126b2]
	chromedriver!(No symbol) [0x7ff787b5de1b]
	chromedriver!(No symbol) [0x7ff787b5e472]
	chromedriver!(No symbol) [0x7ff787b5ea35]
	chromedriver!GetHandleVerifier [0x7ff788626431+5facb1]
	chromedriver!GetHandleVerifier [0x7ff788620a9b+5f531b]
	chromedriver!GetHandleVerifier [0x7ff788645865+61a0e5]
	chromedriver!GetHandleVerifier [0x7ff78805dace+3234e]
	chromedriver!GetHandleVerifier [0x7ff78806661c+3ae9c]
	chromedriver!(No symbol) [0x7ff787b5d39c]
	chromedriver!GetHandleVerifier [0x7ff788803d88+7d8608]
	KERNEL32!BaseThreadInitThunk [0x7ffc7949e957+17]
	ntdll!RtlUserThreadStart [0x7ffc7b40ad6c+2c]

In [24]:
from selenium import webdriver
import time

driver = webdriver.Chrome()

driver.get("https://www.moteur.ma/fr/voiture/achat-voiture-occasion/")
time.sleep(5)

print(driver.title)

Voiture occasion| Moteur.ma

In [25]:
import pandas as pd

print("Total actuel :", len(dataset_total))

pd.DataFrame(dataset_total).to_csv(
    "voitures_brut_174.csv",
    index=False,
    encoding="utf-8-sig"
)

Total actuel : 174

In [26]:
driver.get(liens_restants3[0])
time.sleep(5)

print(driver.title)

Mercedes-Benz Classe GLA Mercedes GLA 200d 2023 Diesel occasion 509249Rabat_phrase Maroc| Moteur.ma

In [27]:
nouvelles_donnees3 = []

for i, lien in enumerate(liens_restants3[:20]):

    try:
        driver.get(lien)
        time.sleep(3)

        texte = driver.find_element(By.TAG_NAME, "body").text

        nouvelles_donnees3.append({
            "URL": lien,
            "Texte": texte
        })

        print(i+1, "OK")

    except Exception as e:
        print(i+1, "Erreur")

print("Récupérées :", len(nouvelles_donnees3))

1 OK
2 OK
3 OK
4 OK
5 OK
6 OK
7 OK
8 OK
9 OK
10 OK
11 OK
12 OK
13 OK
14 OK
15 OK
16 OK
17 OK
18 OK
19 OK
20 OK
Récupérées : 20

In [28]:
dataset_total = dataset_total + nouvelles_donnees3

print("Total actuel :", len(dataset_total))

Total actuel : 194

In [29]:
import pandas as pd

pd.DataFrame(dataset_total).to_csv(
    "voitures_brut_194.csv",
    index=False,
    encoding="utf-8-sig"
)

In [30]:
liens_restants4 = liens_restants3[20:]

print("Restants :", len(liens_restants4))

Restants : 406

In [31]:
nouvelles_donnees4 = []

for i, lien in enumerate(liens_restants4[:20]):

    try:
        driver.get(lien)
        time.sleep(3)

        texte = driver.find_element(By.TAG_NAME, "body").text

        nouvelles_donnees4.append({
            "URL": lien,
            "Texte": texte
        })

        print(i+1, "OK")

    except Exception as e:
        print(i+1, "Erreur")

print("Récupérées :", len(nouvelles_donnees4))

1 OK
2 OK
3 OK
4 OK
5 OK
6 OK
7 OK
8 OK
9 OK
10 OK
11 OK
12 OK
13 OK
14 OK
15 OK
16 OK
17 OK
18 OK
19 OK
20 OK
Récupérées : 20

In [32]:
dataset_total = dataset_total + nouvelles_donnees4
print("Total actuel :", len(dataset_total))

Total actuel : 214

In [33]:
liens_restants5 = liens_restants4[20:]

print("Restants :", len(liens_restants5))

Restants : 386

In [34]:
nouvelles_donnees5 = []

for i, lien in enumerate(liens_restants5[:20]):

    try:
        driver.get(lien)
        time.sleep(3)

        texte = driver.find_element(By.TAG_NAME, "body").text

        nouvelles_donnees5.append({
            "URL": lien,
            "Texte": texte
        })

        print(i+1, "OK")

    except:
        print(i+1, "Erreur")

print("Récupérées :", len(nouvelles_donnees5))

1 OK
2 OK
3 OK
4 OK
5 OK
6 OK
7 OK
8 OK
9 OK
10 OK
11 OK
12 OK
13 OK
14 OK
15 OK
16 OK
17 OK
18 OK
19 OK
20 OK
Récupérées : 20

In [35]:
print("Nombre total :", len(dataset_total))

Nombre total : 214

In [36]:
dataset_total = dataset_total + nouvelles_donnees5

print("Total actuel :", len(dataset_total))

Total actuel : 234

In [37]:
nouvelles_donnees6 = []

for i, lien in enumerate(liens_restants5[:35]):

    try:
        driver.get(lien)
        time.sleep(3)

        texte = driver.find_element(By.TAG_NAME, "body").text

        nouvelles_donnees6.append({
            "URL": lien,
            "Texte": texte
        })

        print(i+1, "OK")

    except:
        print(i+1, "Erreur")

print("Récupérées :", len(nouvelles_donnees6))

1 OK
2 OK
3 OK
4 OK
5 OK
6 OK
7 OK
8 OK
9 OK
10 OK
11 OK
12 OK
13 OK
14 OK
15 OK
16 OK
17 OK
18 OK
19 OK
20 OK
21 OK
22 OK
23 OK
24 OK
25 OK
26 OK
27 OK
28 OK
29 OK
30 OK
31 OK
32 OK
33 OK
34 OK
35 OK
Récupérées : 35

In [38]:
dataset_total = dataset_total + nouvelles_donnees6

print("Total :", len(dataset_total))

Total : 269

In [39]:
liens_restants6 = liens_restants5[35:]

print("Liens restants :", len(liens_restants6))

Liens restants : 351

In [40]:
nouvelles_donnees7 = []

for i, lien in enumerate(liens_restants6[:35]):

    try:
        driver.get(lien)
        time.sleep(3)

        texte = driver.find_element(By.TAG_NAME, "body").text

        nouvelles_donnees7.append({
            "URL": lien,
            "Texte": texte
        })

        print(i+1, "OK")

    except:
        print(i+1, "Erreur")

print("Récupérées :", len(nouvelles_donnees7))

1 OK
2 OK
3 OK
4 OK
5 OK
6 OK
7 OK
8 OK
9 OK
10 OK
11 OK
12 OK
13 OK
14 OK
15 OK
16 OK
17 OK
18 OK
19 OK
20 OK
21 OK
22 OK
23 OK
24 OK
25 OK
26 OK
27 OK
28 OK
29 OK
30 OK
31 OK
32 OK
33 OK
34 OK
35 OK
Récupérées : 35

In [41]:
dataset_total = dataset_total + nouvelles_donnees7

print("Total final :", len(dataset_total))

Total final : 304

In [42]:
pd.DataFrame(dataset_total).to_csv(
    "voitures_moteur_300.csv",
    index=False,
    encoding="utf-8-sig"
)

In [43]:
df_brut = pd.DataFrame(dataset_total)

print(df_brut.shape)
print(df_brut.columns)

(304, 2)
Index(['URL', 'Texte'], dtype='str')

In [44]:
df_brut.head(1)

,URL,Texte
0,https://www.moteur.ma/fr/voiture/achat-voiture...,Neuf\nPromotion\nÉmissions\nActualités\nOccasi...

In [45]:
import re
import pandas as pd

def extraire_infos(row):
    texte = row["Texte"]

    resultat = {}

    # URL
    resultat["URL"] = row["URL"]

    # Marque + modèle
    m = re.search(r"Marque:\s*(.*?)\s+Modèle:\s*(.*)", texte)
    if m:
        resultat["Marque"] = m.group(1)
        resultat["Modele"] = m.group(2).split("\n")[0]
    else:
        resultat["Marque"] = None
        resultat["Modele"] = None

    # Année
    annee = re.search(r"Année:\s*(\d{4})", texte)
    resultat["Annee"] = annee.group(1) if annee else None

    # Kilométrage
    km = re.search(r"Kilométrage:\s*([\d\s,]+)", texte)
    resultat["Kilometrage"] = km.group(1).replace(",", "") if km else None

    # Carburant
    carburant = re.search(r"Carburant:\s*(\w+)", texte)
    resultat["Carburant"] = carburant.group(1) if carburant else None

    # Transmission
    boite = re.search(r"Transmission:\s*(\w+)", texte)
    resultat["Transmission"] = boite.group(1) if boite else None

    return resultat


df_final = df_brut.apply(extraire_infos, axis=1, result_type="expand")

df_final.head()

,URL,Marque,Modele,Annee,Kilometrage,Carburant,Transmission
0,https://www.moteur.ma/fr/voiture/achat-voiture...,Dacia,Sandero,2024,61000,Diesel,Manuelle
1,https://www.moteur.ma/fr/voiture/achat-voiture...,Audi,A1,2018,120000,Diesel,Automatique
2,https://www.moteur.ma/fr/voiture/achat-voiture...,Opel,Astra,2012,316000,Diesel,Manuelle
3,https://www.moteur.ma/fr/voiture/achat-voiture...,Volkswagen,Passat,2015,200000,Diesel,Manuelle
4,https://www.moteur.ma/fr/voiture/achat-voiture...,Dacia,Logan,2014,280000,Diesel,Manuelle

In [46]:
def extraire_prix(texte):
    prix = re.search(r"(\d{1,3}(?:,\d{3})*)\s*MAD", texte)

    if prix:
        return int(prix.group(1).replace(",", ""))
    else:
        return None


df_final["Prix"] = df_brut["Texte"].apply(extraire_prix)

df_final.head()

,URL,Marque,Modele,Annee,Kilometrage,Carburant,Transmission,Prix
0,https://www.moteur.ma/fr/voiture/achat-voiture...,Dacia,Sandero,2024,61000,Diesel,Manuelle,79000
1,https://www.moteur.ma/fr/voiture/achat-voiture...,Audi,A1,2018,120000,Diesel,Automatique,195000
2,https://www.moteur.ma/fr/voiture/achat-voiture...,Opel,Astra,2012,316000,Diesel,Manuelle,93000
3,https://www.moteur.ma/fr/voiture/achat-voiture...,Volkswagen,Passat,2015,200000,Diesel,Manuelle,163000
4,https://www.moteur.ma/fr/voiture/achat-voiture...,Dacia,Logan,2014,280000,Diesel,Manuelle,68000

In [47]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   URL           304 non-null    str
 1   Marque        304 non-null    str
 2   Modele        304 non-null    str
 3   Annee         304 non-null    str
 4   Kilometrage   304 non-null    str
 5   Carburant     304 non-null    str
 6   Transmission  304 non-null    str
 7   Prix          304 non-null    int64
dtypes: int64(1), str(7)
memory usage: 19.1 KB

In [48]:
df_final.isnull().sum()

URL             0
Marque          0
Modele          0
Annee           0
Kilometrage     0
Carburant       0
Transmission    0
Prix            0
dtype: int64

In [49]:
def extraire_prix(texte):
    prix = re.search(r"(\d{1,3}(?:,\d{3})*)\s*MAD", texte)

    if prix:
        return int(prix.group(1).replace(",", ""))
    else:
        return None


df_final["Prix"] = df_brut["Texte"].apply(extraire_prix)

df_final.head()

,URL,Marque,Modele,Annee,Kilometrage,Carburant,Transmission,Prix
0,https://www.moteur.ma/fr/voiture/achat-voiture...,Dacia,Sandero,2024,61000,Diesel,Manuelle,79000
1,https://www.moteur.ma/fr/voiture/achat-voiture...,Audi,A1,2018,120000,Diesel,Automatique,195000
2,https://www.moteur.ma/fr/voiture/achat-voiture...,Opel,Astra,2012,316000,Diesel,Manuelle,93000
3,https://www.moteur.ma/fr/voiture/achat-voiture...,Volkswagen,Passat,2015,200000,Diesel,Manuelle,163000
4,https://www.moteur.ma/fr/voiture/achat-voiture...,Dacia,Logan,2014,280000,Diesel,Manuelle,68000

In [50]:
df_final.isnull().sum()

URL             0
Marque          0
Modele          0
Annee           0
Kilometrage     0
Carburant       0
Transmission    0
Prix            0
dtype: int64

In [51]:
df_final["Annee"] = pd.to_numeric(df_final["Annee"], errors="coerce")
df_final["Kilometrage"] = pd.to_numeric(df_final["Kilometrage"], errors="coerce")
df_final["Prix"] = pd.to_numeric(df_final["Prix"], errors="coerce")

df_final = df_final.dropna()

print(df_final.shape)

(304, 8)

In [52]:
df_final.to_csv(
    "dataset_voitures_maroc_final.csv",
    index=False,
    encoding="utf-8-sig"
)

In [53]:
df_brut = pd.DataFrame(dataset_total)

print(df_brut.shape)
print(df_brut.columns)

(304, 2)
Index(['URL', 'Texte'], dtype='str')

In [54]:
df_final = df_brut.apply(extraire_infos, axis=1, result_type="expand")

df_final["Prix"] = df_brut["Texte"].apply(extraire_prix)

print(df_final.shape)

(304, 8)

In [55]:
df_final.to_csv(
    "dataset_voitures_maroc_final_304.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Sauvegarde terminée ✅")

Sauvegarde terminée ✅